from linker.EFAProgram import efaProgram

## UDWeave version: 6f85520 (2025-11-06)

## Global constants

@efaProgram
def EFA_Broadcast(efa):
  efa.code_level = 'machine'
  state0 = efa.State("udweave_init") #Only one state code 
  efa.add_initId(state0.state_id)
  ## Static declarations
  ## Scoped Variable "num_children" uses Register X16, scope (0)
  ## Scoped Variable "nwid_stride" uses Register X17, scope (0)
  ## Scoped Variable "ndid_stride" uses Register X18, scope (0)
  ## Scoped Variable "cont" uses Register X19, scope (0)
  ## Scoped Variable "val1" uses Register X20, scope (0)
  ## Scoped Variable "val2" uses Register X21, scope (0)
  ## Scoped Variable "val3" uses Register X22, scope (0)
  ## Scoped Variable "val4" uses Register X23, scope (0)
  ## Scoped Variable "sync_value" uses Register X16, scope (0)
  ## Scoped Variable "num_pending_ack" uses Register X17, scope (0)
  ## Scoped Variable "accum_value" uses Register X18, scope (0)
  ## Scoped Variable "num_values" uses Register X19, scope (0)
  ## Scoped Variable "num_lanes" uses Register X20, scope (0)
  ## Scoped Variable "val1" uses Register X21, scope (0)
  ## Scoped Variable "val2" uses Register X22, scope (0)
  ## Scoped Variable "counter_offset" uses Register X23, scope (0)
  ## Scoped Variable "val1_offset" uses Register X24, scope (0)
  ## Scoped Variable "val2_offset" uses Register X25, scope (0)
  ## Scoped Variable "num_pending_ack" uses Register X16, scope (0)
  ## Scoped Variable "num_values" uses Register X17, scope (0)
  ## Scoped Variable "accum_value" uses Register X18, scope (0)
  ## Scoped Variable "val1" uses Register X19, scope (0)
  ## Scoped Variable "val2" uses Register X20, scope (0)
  ## Scoped Variable "cont" uses Register X21, scope (0)
  ## Scoped Variable "accum_value" uses Register X16, scope (0)
  ## Scoped Variable "val1" uses Register X17, scope (0)
  ## Scoped Variable "val2" uses Register X18, scope (0)
  
  ########################################################
  ###### Writing code for thread KnaryBroadcastNode ######
  ########################################################
  # Writing code for event KnaryBroadcastNode::global_init
  tranKnaryBroadcastNode__global_init = efa.writeEvent('KnaryBroadcastNode::global_init')
  tranKnaryBroadcastNode__global_init.writeAction(f"__entry: sli X8 X24 32") 
  tranKnaryBroadcastNode__global_init.writeAction(f"sri X24 X24 32") 
  tranKnaryBroadcastNode__global_init.writeAction(f"sri X8 X25 32") 
  tranKnaryBroadcastNode__global_init.writeAction(f"bneiu X25 0 __if_global_init_2_post") 
  ## If k is zero, set it to 32 (default fanout value)

  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_0_true: movir X25 32") 
  ## Copy the operands to the send buffer in local memory

  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_2_post: addi X7 X26 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"sri X2 X27 20") 
  tranKnaryBroadcastNode__global_init.writeAction(f"andi X27 X27 7") 
  tranKnaryBroadcastNode__global_init.writeAction(f"addi X27 X27 2") 
  tranKnaryBroadcastNode__global_init.writeAction(f"bcpyol X8 X26 X27") 
  tranKnaryBroadcastNode__global_init.writeAction(f"div X24 X25 X18") 
  tranKnaryBroadcastNode__global_init.writeAction(f"ceqi X18 X28 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"clt X24 X25 X29") 
  tranKnaryBroadcastNode__global_init.writeAction(f"or X28 X29 X28") 
  tranKnaryBroadcastNode__global_init.writeAction(f"beqiu X28 0 __if_global_init_8_post") 
  ## If the number of nodes is less than fan out parameter k, set ndid_stride to 1

  ## so that each node sends to one child node at leavels of the tree

  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_6_true: movir X18 1") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_8_post: sli X18 X28 6") 
  tranKnaryBroadcastNode__global_init.writeAction(f"sli X28 X17 5") 
  tranKnaryBroadcastNode__global_init.writeAction(f"sli X25 X28 32") 
  tranKnaryBroadcastNode__global_init.writeAction(f"or X28 X18 X28") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movrl X28 0(X26) 0 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movir X16 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movir X28 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"evlb X28 KnaryBroadcastNode::broadcast_nodes") 
  tranKnaryBroadcastNode__global_init.writeAction(f"evi X28 X28 255 4") 
  tranKnaryBroadcastNode__global_init.writeAction(f"ev X28 X28 X0 X0 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"addi X0 X29 0")  # This is for casting. May be used later on
  tranKnaryBroadcastNode__global_init.writeAction(f"evi X2 X19 KnaryBroadcastNode::global_sync 1") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movir X30 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__for_global_init_12_condition: bleu X24 X30 __for_global_init_14_post") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__for_global_init_13_body: add X30 X18 X31") 
  tranKnaryBroadcastNode__global_init.writeAction(f"bgtu X24 X31 __if_global_init_20_post") 
  ## Last child, adjust the ndid_stride to cover all remaining nodes

  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_18_true: sli X25 X31 32") 
  tranKnaryBroadcastNode__global_init.writeAction(f"add X31 X24 X31") 
  tranKnaryBroadcastNode__global_init.writeAction(f"sub X31 X30 X31") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movrl X31 0(X26) 0 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_20_post: ev X28 X28 X29 X29 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"bnei X27 3 __if_global_init_25_false") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_24_true: send_wcont X28 X19 X26 3") 
  tranKnaryBroadcastNode__global_init.writeAction(f"jmp __if_global_init_26_post") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_25_false: bnei X27 4 __if_global_init_31_false") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_30_true: send_wcont X28 X19 X26 4") 
  tranKnaryBroadcastNode__global_init.writeAction(f"jmp __if_global_init_26_post") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_31_false: bnei X27 5 __if_global_init_37_false") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_36_true: send_wcont X28 X19 X26 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"jmp __if_global_init_26_post") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_37_false: bnei X27 6 __if_global_init_43_false") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_42_true: send_wcont X28 X19 X26 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"jmp __if_global_init_26_post") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_43_false: send_wcont X28 X19 X26 8") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__if_global_init_26_post: add X29 X17 X29") 
  tranKnaryBroadcastNode__global_init.writeAction(f"addi X16 X16 1") 
  tranKnaryBroadcastNode__global_init.writeAction(f"add X30 X18 X30") 
  tranKnaryBroadcastNode__global_init.writeAction(f"jmp __for_global_init_12_condition") 
  tranKnaryBroadcastNode__global_init.writeAction(f"__for_global_init_14_post: addi X1 X19 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movir X20 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movir X21 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movir X22 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"movir X23 0") 
  tranKnaryBroadcastNode__global_init.writeAction(f"yield") 
  
  # Writing code for event KnaryBroadcastNode::global_sync
  tranKnaryBroadcastNode__global_sync = efa.writeEvent('KnaryBroadcastNode::global_sync')
  tranKnaryBroadcastNode__global_sync.writeAction(f"__entry: sri X2 X30 20") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"andi X30 X30 7") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"addi X30 X30 2") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"blei X30 4 __if_global_sync_2_post") 
  ## Up to 4 values supported

  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_0_true: movir X30 4") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_2_post: movir X28 0") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__for_global_sync_3_condition: ble X30 X28 __for_global_sync_5_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__for_global_sync_4_body: bnei X28 0 __if_global_sync_8_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_6_true: add X20 X8 X20") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_8_post: bnei X28 1 __if_global_sync_14_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_12_true: add X21 X9 X21") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_14_post: bnei X28 2 __if_global_sync_20_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_18_true: add X22 X10 X22") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_20_post: bnei X28 3 __if_global_sync_26_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_24_true: add X23 X11 X23") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_26_post: addi X28 X28 1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"jmp __for_global_sync_3_condition") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__for_global_sync_5_post: subi X16 X16 1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"bleiu X16 0 __if_global_sync_35_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_33_true: yield") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_35_post: addi X7 X28 8") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"movrl X20 0(X28) 0 8") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"movrl X21 8(X28) 0 8") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"bgti X30 2 __if_global_sync_37_false") 
  ## Two or less than two values to send back

  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_36_true: movir X24 -1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"sri X24 X24 1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"send_wcont X19 X24 X28 2") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"yield_terminate") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"jmp __if_global_sync_38_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_37_false: bnei X30 3 __if_global_sync_43_false") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_42_true: movrl X22 16(X28) 0 8") 
  ## Three values to send back

  tranKnaryBroadcastNode__global_sync.writeAction(f"movir X24 -1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"sri X24 X24 1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"send_wcont X19 X24 X28 3") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"yield_terminate") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"jmp __if_global_sync_38_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_43_false: bnei X30 4 __if_global_sync_49_false") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_48_true: movrl X22 16(X28) 0 8") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"movrl X23 24(X28) 0 8") 
  ## Four values to send back

  tranKnaryBroadcastNode__global_sync.writeAction(f"movir X24 -1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"sri X24 X24 1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"send_wcont X19 X24 X28 4") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"yield_terminate") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"jmp __if_global_sync_38_post") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_49_false: print 'Error: Unsupported number of values %lu in global_sync.' X30") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"movrl X22 16(X28) 0 8") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"movrl X23 24(X28) 0 8") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"movir X24 -1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"sri X24 X24 1") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"send_wcont X19 X24 X28 4") 
  tranKnaryBroadcastNode__global_sync.writeAction(f"__if_global_sync_38_post: yield_terminate") 
  
  # Writing code for event KnaryBroadcastNode::broadcast_nodes
  tranKnaryBroadcastNode__broadcast_nodes = efa.writeEvent('KnaryBroadcastNode::broadcast_nodes')
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__entry: movir X28 -1") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sri X28 X28 32") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"and X8 X28 X28") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sri X8 X30 32") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"bleu X30 X28 __if_broadcast_nodes_4_false") 
  ## If the number of nodes is less than fan out parameter k, set ndid_stride to 1

  ## so that each node sends to one child node at leavels of the tree

  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_3_true: movir X18 1") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_5_post") 
  ## Calculate the stride between node IDs for each level of the broadcast tree

  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_4_false: div X28 X30 X18") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_5_post: sli X18 X24 6") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sli X24 X17 5") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"bneiu X18 1 __if_broadcast_nodes_10_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_9_true: addi X9 X24 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"addi X0 X25 0")  # This is for casting. May be used later on
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"evi X2 X19 KnaryBroadcastNode::node_sync 1") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X16 0") 
  ## Copy the operands to the send buffer in local memory

  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sri X2 X26 20") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"andi X26 X26 7") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X29 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__for_broadcast_nodes_15_condition: bleu X28 X29 __for_broadcast_nodes_17_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__for_broadcast_nodes_16_body: ev X24 X24 X25 X25 8") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"bnei X26 9 __if_broadcast_nodes_35_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_34_true: sendops_wcont X24 X19 X10 9") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_33_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_35_false: bnei X26 2 __if_broadcast_nodes_37_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_36_true: sendops_wcont X24 X19 X10 2") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_33_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_37_false: bnei X26 8 __if_broadcast_nodes_39_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_38_true: sendops_wcont X24 X19 X10 8") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_33_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_39_false: bnei X26 7 __if_broadcast_nodes_41_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_40_true: sendops_wcont X24 X19 X10 7") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_33_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_41_false: bnei X26 6 __if_broadcast_nodes_43_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_42_true: sendops_wcont X24 X19 X10 6") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_33_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_43_false: bnei X26 5 __if_broadcast_nodes_45_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_44_true: sendops_wcont X24 X19 X10 5") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_33_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_45_false: bnei X26 4 __if_broadcast_nodes_47_false") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_46_true: sendops_wcont X24 X19 X10 4") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __if_broadcast_nodes_33_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_47_false: sendops_wcont X24 X19 X10 3") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_33_post: add X25 X17 X25") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"addi X16 X16 1") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"add X29 X18 X29") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __for_broadcast_nodes_15_condition") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__for_broadcast_nodes_17_post: jmp __if_broadcast_nodes_11_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_10_false: addi X7 X29 8") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X24 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"evlb X24 KnaryBroadcastNode::broadcast_nodes") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"evi X24 X24 255 4") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"ev X24 X24 X0 X0 8") 
  ## Copy the operands to the send buffer in local memory

  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_21_true: sri X2 X25 20") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"andi X25 X25 7") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"addi X25 X25 2") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"bcpyol X8 X29 X25") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sli X18 X25 6") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sli X25 X17 5") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sli X30 X25 32") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"or X25 X18 X25") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movrl X25 0(X29) 0 8") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"addi X0 X25 0")  # This is for casting. May be used later on
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"evi X2 X19 KnaryBroadcastNode::node_sync 1") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X16 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X26 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__for_broadcast_nodes_24_condition: bleu X28 X26 __if_broadcast_nodes_11_post") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__for_broadcast_nodes_25_body: add X26 X18 X27") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"bgtu X28 X27 __if_broadcast_nodes_32_post") 
  ## Last child, adjust the ndid_stride to cover all remaining nodes

  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_30_true: sub X28 X26 X27") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"sli X30 X31 32") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"or X31 X27 X27") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movrl X27 0(X29) 0 8") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_32_post: ev X24 X24 X25 X25 8") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"send_wcont X24 X19 X29 8") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"add X25 X17 X25") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"addi X16 X16 1") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"add X26 X18 X26") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"jmp __for_broadcast_nodes_24_condition") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"__if_broadcast_nodes_11_post: addi X1 X19 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X20 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X21 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X22 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"movir X23 0") 
  tranKnaryBroadcastNode__broadcast_nodes.writeAction(f"yield") 
  
  # Writing code for event KnaryBroadcastNode::node_sync
  tranKnaryBroadcastNode__node_sync = efa.writeEvent('KnaryBroadcastNode::node_sync')
  tranKnaryBroadcastNode__node_sync.writeAction(f"__entry: sri X2 X28 20") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"andi X28 X28 7") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"addi X28 X28 2") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"blei X28 4 __if_node_sync_2_post") 
  ## Up to 4 values supported

  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_0_true: movir X28 4") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_2_post: movir X30 0") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__for_node_sync_3_condition: ble X28 X30 __for_node_sync_5_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__for_node_sync_4_body: bnei X30 0 __if_node_sync_8_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_6_true: add X20 X8 X20") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_8_post: bnei X30 1 __if_node_sync_14_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_12_true: add X21 X9 X21") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_14_post: bnei X30 2 __if_node_sync_20_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_18_true: add X22 X10 X22") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_20_post: bnei X30 3 __if_node_sync_26_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_24_true: add X23 X11 X23") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_26_post: addi X30 X30 1") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"jmp __for_node_sync_3_condition") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__for_node_sync_5_post: subi X16 X16 1") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"bleiu X16 0 __if_node_sync_35_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_33_true: yield") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_35_post: addi X7 X30 8") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"movrl X20 0(X30) 0 8") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"movrl X21 8(X30) 0 8") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"bgti X28 2 __if_node_sync_37_false") 
  ## Two or less than two values to send back

  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_36_true: send_wcont X19 X2 X30 2") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"yield_terminate") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"jmp __if_node_sync_38_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_37_false: bnei X28 3 __if_node_sync_43_false") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_42_true: movrl X22 16(X30) 0 8") 
  ## Three values to send back

  tranKnaryBroadcastNode__node_sync.writeAction(f"send_wcont X19 X2 X30 3") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"yield_terminate") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"jmp __if_node_sync_38_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_43_false: bnei X28 4 __if_node_sync_49_false") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_48_true: movrl X22 16(X30) 0 8") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"movrl X23 24(X30) 0 8") 
  ## Four values to send back

  tranKnaryBroadcastNode__node_sync.writeAction(f"send_wcont X19 X2 X30 4") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"yield_terminate") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"jmp __if_node_sync_38_post") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_49_false: print 'Error: Unsupported number of values %lu in node_sync.' X28") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"movrl X22 16(X30) 0 8") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"movrl X23 24(X30) 0 8") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"send_wcont X19 X2 X30 4") 
  tranKnaryBroadcastNode__node_sync.writeAction(f"__if_node_sync_38_post: yield_terminate") 
  
  
  ################################################
  ###### Writing code for thread GlobalSync ######
  ################################################
  # Writing code for event GlobalSync::global_init
  tranGlobalSync__global_init = efa.writeEvent('GlobalSync::global_init')
  tranGlobalSync__global_init.writeAction(f"__entry: addi X9 X16 0") 
  tranGlobalSync__global_init.writeAction(f"movir X18 0") 
  tranGlobalSync__global_init.writeAction(f"movir X21 0") 
  tranGlobalSync__global_init.writeAction(f"movir X22 0") 
  tranGlobalSync__global_init.writeAction(f"addi X11 X23 0") 
  tranGlobalSync__global_init.writeAction(f"addi X10 X19 0") 
  tranGlobalSync__global_init.writeAction(f"addi X8 X20 0") 
  tranGlobalSync__global_init.writeAction(f"blei X19 3 __if_global_init_6_true") 
  ## Up to 4 values supported

  tranGlobalSync__global_init.writeAction(f"__if_global_init_3_true: movir X19 3") 
  tranGlobalSync__global_init.writeAction(f"print 'Warning: Limiting number of values to %lu in global_sync.' X19") 
  ## Calculate the number of nodes involved in the global sync

  ## based on the number of lanes

  tranGlobalSync__global_init.writeAction(f"__if_global_init_6_true: movir X26 2048") 
  tranGlobalSync__global_init.writeAction(f"div X8 X26 X27") 
  tranGlobalSync__global_init.writeAction(f"mod X8 X26 X26") 
  tranGlobalSync__global_init.writeAction(f"beqi X26 0 __if_global_init_11_post") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_9_true: addi X27 X27 1") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_11_post: movir X26 32") 
  tranGlobalSync__global_init.writeAction(f"bgt X26 X27 __if_global_init_16_false") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_15_true: addi X7 X26 8") 
  tranGlobalSync__global_init.writeAction(f"movrl X27 0(X26) 0 8") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_18_true: movir X28 0") 
  tranGlobalSync__global_init.writeAction(f"evlb X28 NodeSync::node_bcst") 
  tranGlobalSync__global_init.writeAction(f"evi X28 X28 255 4") 
  tranGlobalSync__global_init.writeAction(f"ev X28 X28 X0 X0 8") 
  tranGlobalSync__global_init.writeAction(f"movrl X28 8(X26) 0 8") 
  tranGlobalSync__global_init.writeAction(f"movir X28 0") 
  tranGlobalSync__global_init.writeAction(f"addi X8 X29 0")  # This is for casting. May be used later on
  tranGlobalSync__global_init.writeAction(f"or X28 X29 X28") 
  tranGlobalSync__global_init.writeAction(f"movrl X28 16(X26) 0 8") 
  tranGlobalSync__global_init.writeAction(f"movrl X19 24(X26) 0 8") 
  ## Copy the operands to the send buffer in local memory

  tranGlobalSync__global_init.writeAction(f"__if_global_init_21_true: addi X26 X28 32") 
  tranGlobalSync__global_init.writeAction(f"bcpyol X11 X28 X19") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_24_true: movir X28 0") 
  tranGlobalSync__global_init.writeAction(f"evlb X28 KnaryBroadcastNode::global_init") 
  tranGlobalSync__global_init.writeAction(f"evi X28 X28 255 4") 
  tranGlobalSync__global_init.writeAction(f"ev X28 X28 X0 X0 8") 
  tranGlobalSync__global_init.writeAction(f"send_wret X28 GlobalSync::global_sync X26 8 X29") 
  tranGlobalSync__global_init.writeAction(f"movir X17 1") 
  tranGlobalSync__global_init.writeAction(f"jmp __if_global_init_17_post") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_16_false: movir X26 0") 
  tranGlobalSync__global_init.writeAction(f"evlb X26 NodeSync::node_bcst") 
  tranGlobalSync__global_init.writeAction(f"evi X26 X26 255 4") 
  tranGlobalSync__global_init.writeAction(f"ev X26 X26 X0 X0 8") 
  tranGlobalSync__global_init.writeAction(f"addi X0 X28 0")  # This is for casting. May be used later on
  tranGlobalSync__global_init.writeAction(f"addi X7 X29 8") 
  tranGlobalSync__global_init.writeAction(f"movir X30 0") 
  tranGlobalSync__global_init.writeAction(f"addi X8 X31 0")  # This is for casting. May be used later on
  tranGlobalSync__global_init.writeAction(f"or X30 X31 X30") 
  tranGlobalSync__global_init.writeAction(f"movrl X30 0(X29) 0 8") 
  tranGlobalSync__global_init.writeAction(f"movrl X19 8(X29) 0 8") 
  ## Copy the operands to the send buffer in local memory

  tranGlobalSync__global_init.writeAction(f"__if_global_init_33_true: addi X29 X30 16") 
  tranGlobalSync__global_init.writeAction(f"bcpyol X11 X30 X19") 
  tranGlobalSync__global_init.writeAction(f"movir X30 0") 
  tranGlobalSync__global_init.writeAction(f"__for_global_init_36_condition: ble X27 X30 __for_global_init_38_post") 
  tranGlobalSync__global_init.writeAction(f"__for_global_init_37_body: ev X26 X26 X28 X28 8") 
  tranGlobalSync__global_init.writeAction(f"send_wret X26 GlobalSync::global_sync X29 8 X31") 
  tranGlobalSync__global_init.writeAction(f"addi X28 X28 2048") 
  tranGlobalSync__global_init.writeAction(f"addi X30 X30 1") 
  tranGlobalSync__global_init.writeAction(f"jmp __for_global_init_36_condition") 
  tranGlobalSync__global_init.writeAction(f"__for_global_init_38_post: addi X27 X17 0") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_17_post: blei X19 1 __if_global_init_47_post") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_45_true: addi X12 X24 0") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_47_post: blei X19 2 __if_global_init_50_post") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_48_true: addi X13 X25 0") 
  tranGlobalSync__global_init.writeAction(f"__if_global_init_50_post: yield") 
  
  # Writing code for event GlobalSync::global_sync
  tranGlobalSync__global_sync = efa.writeEvent('GlobalSync::global_sync')
  tranGlobalSync__global_sync.writeAction(f"__entry: add X18 X8 X18") 
  tranGlobalSync__global_sync.writeAction(f"blei X19 1 __if_global_sync_2_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_0_true: add X21 X9 X21") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_2_post: blei X19 2 __if_global_sync_5_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_3_true: add X22 X10 X22") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_5_post: subi X17 X17 1") 
  tranGlobalSync__global_sync.writeAction(f"blei X17 0 __if_global_sync_11_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_9_true: yield") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_11_post: beq X18 X16 __if_global_sync_13_false") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_12_true: movir X27 0") 
  tranGlobalSync__global_sync.writeAction(f"evlb X27 GlobalSync::global_init") 
  tranGlobalSync__global_sync.writeAction(f"evi X27 X27 255 4") 
  tranGlobalSync__global_sync.writeAction(f"ev X27 X27 X0 X0 8") 
  tranGlobalSync__global_sync.writeAction(f"addi X7 X26 8") 
  tranGlobalSync__global_sync.writeAction(f"movrl X20 0(X26) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"movrl X16 8(X26) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"movrl X19 16(X26) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"movrl X23 24(X26) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"blei X19 1 __if_global_sync_20_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_18_true: movrl X24 32(X26) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_20_post: blei X19 2 __if_global_sync_23_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_21_true: movrl X25 40(X26) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_23_post: send_wcont X27 X1 X26 8") 
  tranGlobalSync__global_sync.writeAction(f"yield_terminate") 
  tranGlobalSync__global_sync.writeAction(f"jmp __if_global_sync_14_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_13_false: addi X7 X27 8") 
  tranGlobalSync__global_sync.writeAction(f"movrl X18 0(X27) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"blei X19 1 __if_global_sync_29_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_27_true: movrl X21 8(X27) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_29_post: blei X19 2 __if_global_sync_35_post") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_33_true: movrl X22 16(X27) 0 8") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_35_post: movir X26 -1") 
  tranGlobalSync__global_sync.writeAction(f"sri X26 X26 1") 
  tranGlobalSync__global_sync.writeAction(f"send_wcont X1 X26 X27 8") 
  tranGlobalSync__global_sync.writeAction(f"yield_terminate") 
  tranGlobalSync__global_sync.writeAction(f"__if_global_sync_14_post: yield") 
  
  
  ##############################################
  ###### Writing code for thread NodeSync ######
  ##############################################
  # Writing code for event NodeSync::node_bcst
  tranNodeSync__node_bcst = efa.writeEvent('NodeSync::node_bcst')
  tranNodeSync__node_bcst.writeAction(f"__if_node_bcst_0_true: sli X8 X22 32") 
  tranNodeSync__node_bcst.writeAction(f"sri X22 X22 32") 
  tranNodeSync__node_bcst.writeAction(f"sri X8 X23 32") 
  tranNodeSync__node_bcst.writeAction(f"add X22 X23 X22") 
  tranNodeSync__node_bcst.writeAction(f"addi X0 X23 2048") 
  tranNodeSync__node_bcst.writeAction(f"addi X23 X23 0")  # This is for casting. May be used later on
  tranNodeSync__node_bcst.writeAction(f"ble X23 X22 __if_node_bcst_4_false") 
  tranNodeSync__node_bcst.writeAction(f"__if_node_bcst_3_true: addi X0 X24 0")  # This is for casting. May be used later on
  tranNodeSync__node_bcst.writeAction(f"sub X22 X24 X23") 
  tranNodeSync__node_bcst.writeAction(f"jmp __if_node_bcst_5_post") 
  tranNodeSync__node_bcst.writeAction(f"__if_node_bcst_4_false: movir X23 2048") 
  tranNodeSync__node_bcst.writeAction(f"__if_node_bcst_5_post: sari X23 X22 63") 
  tranNodeSync__node_bcst.writeAction(f"sri X22 X22 58") 
  tranNodeSync__node_bcst.writeAction(f"add X22 X23 X22") 
  tranNodeSync__node_bcst.writeAction(f"sari X22 X22 6") 
  tranNodeSync__node_bcst.writeAction(f"sari X23 X24 63") 
  tranNodeSync__node_bcst.writeAction(f"sri X24 X24 58") 
  tranNodeSync__node_bcst.writeAction(f"add X24 X23 X24") 
  tranNodeSync__node_bcst.writeAction(f"andi X24 X24 -64") 
  tranNodeSync__node_bcst.writeAction(f"sub X23 X24 X24") 
  tranNodeSync__node_bcst.writeAction(f"beqi X24 0 __if_node_bcst_11_post") 
  tranNodeSync__node_bcst.writeAction(f"__if_node_bcst_9_true: addi X22 X22 1") 
  tranNodeSync__node_bcst.writeAction(f"__if_node_bcst_11_post: addi X0 X24 0")  # This is for casting. May be used later on
  tranNodeSync__node_bcst.writeAction(f"movir X23 0") 
  tranNodeSync__node_bcst.writeAction(f"evlb X23 UpdownSync::ud_entry") 
  tranNodeSync__node_bcst.writeAction(f"evi X23 X23 255 4") 
  tranNodeSync__node_bcst.writeAction(f"ev X23 X23 X0 X0 8") 
  tranNodeSync__node_bcst.writeAction(f"addi X7 X25 8") 
  tranNodeSync__node_bcst.writeAction(f"movrl X8 0(X25) 0 8") 
  tranNodeSync__node_bcst.writeAction(f"movrl X9 8(X25) 0 8") 
  tranNodeSync__node_bcst.writeAction(f"addi X25 X26 16") 
  tranNodeSync__node_bcst.writeAction(f"addi X9 X17 0") 
  tranNodeSync__node_bcst.writeAction(f"bcpyol X10 X26 X17") 
  tranNodeSync__node_bcst.writeAction(f"movir X26 0") 
  tranNodeSync__node_bcst.writeAction(f"__for_node_bcst_12_condition: ble X22 X26 __for_node_bcst_14_post") 
  tranNodeSync__node_bcst.writeAction(f"__for_node_bcst_13_body: ev X23 X23 X24 X24 8") 
  tranNodeSync__node_bcst.writeAction(f"send_wret X23 NodeSync::node_sync X25 8 X27") 
  tranNodeSync__node_bcst.writeAction(f"addi X24 X24 64") 
  tranNodeSync__node_bcst.writeAction(f"addi X26 X26 1") 
  tranNodeSync__node_bcst.writeAction(f"jmp __for_node_bcst_12_condition") 
  tranNodeSync__node_bcst.writeAction(f"__for_node_bcst_14_post: addi X22 X16 0") 
  tranNodeSync__node_bcst.writeAction(f"addi X1 X21 0") 
  tranNodeSync__node_bcst.writeAction(f"movir X18 0") 
  tranNodeSync__node_bcst.writeAction(f"movir X19 0") 
  tranNodeSync__node_bcst.writeAction(f"movir X20 0") 
  tranNodeSync__node_bcst.writeAction(f"yield") 
  
  # Writing code for event NodeSync::node_sync
  tranNodeSync__node_sync = efa.writeEvent('NodeSync::node_sync')
  tranNodeSync__node_sync.writeAction(f"__entry: add X18 X8 X18") 
  tranNodeSync__node_sync.writeAction(f"blei X17 0 __if_node_sync_2_post") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_0_true: add X19 X9 X19") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_2_post: blei X17 1 __if_node_sync_5_post") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_3_true: add X20 X10 X20") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_5_post: subi X16 X16 1") 
  tranNodeSync__node_sync.writeAction(f"blei X16 0 __if_node_sync_11_post") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_9_true: yield") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_11_post: addi X7 X22 8") 
  tranNodeSync__node_sync.writeAction(f"movrl X18 0(X22) 0 8") 
  tranNodeSync__node_sync.writeAction(f"blei X17 0 __if_node_sync_14_post") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_12_true: movrl X19 8(X22) 0 8") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_14_post: blei X17 1 __if_node_sync_17_post") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_15_true: movrl X20 16(X22) 0 8") 
  tranNodeSync__node_sync.writeAction(f"__if_node_sync_17_post: movir X26 -1") 
  tranNodeSync__node_sync.writeAction(f"sri X26 X26 1") 
  tranNodeSync__node_sync.writeAction(f"send_wcont X21 X26 X22 8") 
  tranNodeSync__node_sync.writeAction(f"yield_terminate") 
  
  
  ################################################
  ###### Writing code for thread UpdownSync ######
  ################################################
  # Writing code for event UpdownSync::ud_entry
  tranUpdownSync__ud_entry = efa.writeEvent('UpdownSync::ud_entry')
  tranUpdownSync__ud_entry.writeAction(f"__entry: movir X19 10") 
  tranUpdownSync__ud_entry.writeAction(f"movir X20 12288") 
  tranUpdownSync__ud_entry.writeAction(f"sli X20 X20 16") 
  tranUpdownSync__ud_entry.writeAction(f"or X20 X0 X20") 
  tranUpdownSync__ud_entry.writeAction(f"movir X21 0") 
  tranUpdownSync__ud_entry.writeAction(f"evlb X21 UpdownSync::ud_loop") 
  tranUpdownSync__ud_entry.writeAction(f"evi X21 X21 255 4") 
  tranUpdownSync__ud_entry.writeAction(f"ev X21 X21 X20 X20 8") 
  tranUpdownSync__ud_entry.writeAction(f"addi X7 X20 8") 
  tranUpdownSync__ud_entry.writeAction(f"movrl X19 0(X20) 0 8") 
  tranUpdownSync__ud_entry.writeAction(f"movrl X8 8(X20) 0 8") 
  tranUpdownSync__ud_entry.writeAction(f"movrl X9 16(X20) 0 8") 
  tranUpdownSync__ud_entry.writeAction(f"addi X20 X19 24") 
  tranUpdownSync__ud_entry.writeAction(f"bcpyol X10 X19 X9") 
  tranUpdownSync__ud_entry.writeAction(f"send_wcont X21 X1 X20 8") 
  tranUpdownSync__ud_entry.writeAction(f"yield_terminate") 
  
  # Writing code for event UpdownSync::ud_loop
  tranUpdownSync__ud_loop = efa.writeEvent('UpdownSync::ud_loop')
  tranUpdownSync__ud_loop.writeAction(f"__entry: subi X8 X21 1") 
  tranUpdownSync__ud_loop.writeAction(f"bneiu X21 0 __if_ud_loop_2_post") 
  ## Get lane 0 nwid of the current UpDown

  tranUpdownSync__ud_loop.writeAction(f"__if_ud_loop_0_true: sri X0 X20 6") 
  tranUpdownSync__ud_loop.writeAction(f"sli X20 X20 6") 
  tranUpdownSync__ud_loop.writeAction(f"movir X19 0") 
  tranUpdownSync__ud_loop.writeAction(f"evlb X19 UpdownSync::ud_accum") 
  tranUpdownSync__ud_loop.writeAction(f"evi X19 X19 255 4") 
  tranUpdownSync__ud_loop.writeAction(f"ev X19 X19 X20 X20 8") 
  tranUpdownSync__ud_loop.writeAction(f"addi X7 X20 8") 
  tranUpdownSync__ud_loop.writeAction(f"movrl X9 0(X20) 0 8") 
  tranUpdownSync__ud_loop.writeAction(f"movrl X10 8(X20) 0 8") 
  tranUpdownSync__ud_loop.writeAction(f"addi X20 X22 16") 
  tranUpdownSync__ud_loop.writeAction(f"bcpyol X11 X22 X10") 
  tranUpdownSync__ud_loop.writeAction(f"send_wcont X19 X1 X20 8") 
  tranUpdownSync__ud_loop.writeAction(f"yield_terminate") 
  tranUpdownSync__ud_loop.writeAction(f"__if_ud_loop_2_post: movir X19 12288") 
  tranUpdownSync__ud_loop.writeAction(f"sli X19 X19 16") 
  tranUpdownSync__ud_loop.writeAction(f"or X19 X0 X19") 
  tranUpdownSync__ud_loop.writeAction(f"movir X20 0") 
  tranUpdownSync__ud_loop.writeAction(f"evlb X20 UpdownSync::ud_loop") 
  tranUpdownSync__ud_loop.writeAction(f"evi X20 X20 255 4") 
  tranUpdownSync__ud_loop.writeAction(f"ev X20 X20 X19 X19 8") 
  tranUpdownSync__ud_loop.writeAction(f"addi X7 X19 8") 
  tranUpdownSync__ud_loop.writeAction(f"movrl X21 0(X19) 0 8") 
  tranUpdownSync__ud_loop.writeAction(f"addi X19 X21 8") 
  tranUpdownSync__ud_loop.writeAction(f"addi X10 X22 2") 
  tranUpdownSync__ud_loop.writeAction(f"bcpyol X9 X21 X22") 
  tranUpdownSync__ud_loop.writeAction(f"send_wcont X20 X1 X19 8") 
  tranUpdownSync__ud_loop.writeAction(f"yield_terminate") 
  
  # Writing code for event UpdownSync::ud_accum
  tranUpdownSync__ud_accum = efa.writeEvent('UpdownSync::ud_accum')
  tranUpdownSync__ud_accum.writeAction(f"__entry: movir X16 0") 
  tranUpdownSync__ud_accum.writeAction(f"movir X17 0") 
  tranUpdownSync__ud_accum.writeAction(f"movir X18 0") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_0_true: sli X8 X20 32") 
  tranUpdownSync__ud_accum.writeAction(f"sari X20 X20 32") 
  tranUpdownSync__ud_accum.writeAction(f"sari X8 X19 32") 
  tranUpdownSync__ud_accum.writeAction(f"add X20 X19 X20") 
  tranUpdownSync__ud_accum.writeAction(f"addi X0 X19 64") 
  tranUpdownSync__ud_accum.writeAction(f"addi X19 X19 0")  # This is for casting. May be used later on
  tranUpdownSync__ud_accum.writeAction(f"ble X19 X20 __if_ud_accum_4_false") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_3_true: addi X0 X21 0")  # This is for casting. May be used later on
  tranUpdownSync__ud_accum.writeAction(f"sub X20 X21 X19") 
  tranUpdownSync__ud_accum.writeAction(f"jmp __if_ud_accum_5_post") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_4_false: movir X19 64") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_5_post: addi X7 X20 0") 
  tranUpdownSync__ud_accum.writeAction(f"movir X21 0") 
  tranUpdownSync__ud_accum.writeAction(f"__for_ud_accum_9_condition: ble X19 X21 __for_ud_accum_11_post") 
  tranUpdownSync__ud_accum.writeAction(f"__for_ud_accum_10_body: add X20 X10 X22") 
  tranUpdownSync__ud_accum.writeAction(f"movlr 0(X22) X23 0 8") 
  tranUpdownSync__ud_accum.writeAction(f"add X16 X23 X16") 
  tranUpdownSync__ud_accum.writeAction(f"bleiu X9 1 __if_ud_accum_17_post") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_15_true: add X20 X11 X22") 
  tranUpdownSync__ud_accum.writeAction(f"movlr 0(X22) X23 0 8") 
  tranUpdownSync__ud_accum.writeAction(f"add X17 X23 X17") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_17_post: bleiu X9 2 __if_ud_accum_23_post") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_21_true: add X20 X12 X22") 
  tranUpdownSync__ud_accum.writeAction(f"movlr 0(X22) X23 0 8") 
  tranUpdownSync__ud_accum.writeAction(f"add X18 X23 X18") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_23_post: movir X23 65536") 
  tranUpdownSync__ud_accum.writeAction(f"add X20 X23 X20") 
  tranUpdownSync__ud_accum.writeAction(f"addi X21 X21 1") 
  tranUpdownSync__ud_accum.writeAction(f"jmp __for_ud_accum_9_condition") 
  ## Send the accumulated values back to the parent node

  tranUpdownSync__ud_accum.writeAction(f"__for_ud_accum_11_post: bleiu X9 2 __if_ud_accum_31_false") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_30_true: movir X20 -1") 
  tranUpdownSync__ud_accum.writeAction(f"sri X20 X20 1") 
  tranUpdownSync__ud_accum.writeAction(f"sendr3_wcont X1 X20 X16 X17 X18") 
  tranUpdownSync__ud_accum.writeAction(f"jmp __if_ud_accum_32_post") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_31_false: bleiu X9 1 __if_ud_accum_34_false") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_33_true: movir X20 -1") 
  tranUpdownSync__ud_accum.writeAction(f"sri X20 X20 1") 
  tranUpdownSync__ud_accum.writeAction(f"sendr_wcont X1 X20 X16 X17") 
  tranUpdownSync__ud_accum.writeAction(f"jmp __if_ud_accum_32_post") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_34_false: movir X20 -1") 
  tranUpdownSync__ud_accum.writeAction(f"sri X20 X20 1") 
  tranUpdownSync__ud_accum.writeAction(f"sendr_wcont X1 X20 X16 X16") 
  tranUpdownSync__ud_accum.writeAction(f"__if_ud_accum_32_post: yield_terminate") 
  