from linker.EFAProgram import efaProgram
from linker.EFAsections.StaticDataSection import staticDataType

@efaProgram
def efaProgram_LinkableBroadcast(efa):

    ## init_null_state
    init_null_state = efa.State("init_null_state")
    efa.add_state(init_null_state)
    efa.add_initId(init_null_state.state_id)

    ## Add event ids and names:

    ## KnaryBroadcastNode__global_init
    KnaryBroadcastNode__global_init = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "KnaryBroadcastNode__global_init")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___entry: sli X8 X24 32")
    KnaryBroadcastNode__global_init.writeAction("sri X24 X24 32")
    KnaryBroadcastNode__global_init.writeAction("sri X8 X25 32")
    KnaryBroadcastNode__global_init.writeAction("bneiu X25 0 EFA_Broadcast_vjmvd___if_global_init_2_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_0_true: movir X25 32")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_2_post: addi X7 X26 8")
    KnaryBroadcastNode__global_init.writeAction("sri X2 X27 20")
    KnaryBroadcastNode__global_init.writeAction("andi X27 X27 7")
    KnaryBroadcastNode__global_init.writeAction("addi X27 X27 2")
    KnaryBroadcastNode__global_init.writeAction("bcpyol X8 X26 X27")
    KnaryBroadcastNode__global_init.writeAction("div X24 X25 X18")
    KnaryBroadcastNode__global_init.writeAction("ceqi X18 X28 0")
    KnaryBroadcastNode__global_init.writeAction("clt X24 X25 X29")
    KnaryBroadcastNode__global_init.writeAction("or X28 X29 X28")
    KnaryBroadcastNode__global_init.writeAction("beqiu X28 0 EFA_Broadcast_vjmvd___if_global_init_8_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_6_true: movir X18 1")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_8_post: sli X18 X28 6")
    KnaryBroadcastNode__global_init.writeAction("sli X28 X17 5")
    KnaryBroadcastNode__global_init.writeAction("sli X25 X28 32")
    KnaryBroadcastNode__global_init.writeAction("or X28 X18 X28")
    KnaryBroadcastNode__global_init.writeAction("movrl X28 0(X26) 0 8")
    KnaryBroadcastNode__global_init.writeAction("movir X16 0")
    KnaryBroadcastNode__global_init.writeAction("movir X28 0")
    KnaryBroadcastNode__global_init.writeAction("evlb X28 KnaryBroadcastNode__broadcast_nodes")
    KnaryBroadcastNode__global_init.writeAction("evi X28 X28 255 4")
    KnaryBroadcastNode__global_init.writeAction("ev X28 X28 X0 X0 8")
    KnaryBroadcastNode__global_init.writeAction("addi X0 X29 0")
    KnaryBroadcastNode__global_init.writeAction("evi X2 X19 KnaryBroadcastNode__global_sync 1")
    KnaryBroadcastNode__global_init.writeAction("movir X30 0")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___for_global_init_12_condition: bleu X24 X30 EFA_Broadcast_vjmvd___for_global_init_14_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___for_global_init_13_body: add X30 X18 X31")
    KnaryBroadcastNode__global_init.writeAction("bgtu X24 X31 EFA_Broadcast_vjmvd___if_global_init_20_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_18_true: sli X25 X31 32")
    KnaryBroadcastNode__global_init.writeAction("add X31 X24 X31")
    KnaryBroadcastNode__global_init.writeAction("sub X31 X30 X31")
    KnaryBroadcastNode__global_init.writeAction("movrl X31 0(X26) 0 8")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_20_post: ev X28 X28 X29 X29 8")
    KnaryBroadcastNode__global_init.writeAction("bnei X27 3 EFA_Broadcast_vjmvd___if_global_init_25_false")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_24_true: send_wcont X28 X19 X26 3")
    KnaryBroadcastNode__global_init.writeAction("jmp EFA_Broadcast_vjmvd___if_global_init_26_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_25_false: bnei X27 4 EFA_Broadcast_vjmvd___if_global_init_31_false")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_30_true: send_wcont X28 X19 X26 4")
    KnaryBroadcastNode__global_init.writeAction("jmp EFA_Broadcast_vjmvd___if_global_init_26_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_31_false: bnei X27 5 EFA_Broadcast_vjmvd___if_global_init_37_false")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_36_true: send_wcont X28 X19 X26 8")
    KnaryBroadcastNode__global_init.writeAction("jmp EFA_Broadcast_vjmvd___if_global_init_26_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_37_false: bnei X27 6 EFA_Broadcast_vjmvd___if_global_init_43_false")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_42_true: send_wcont X28 X19 X26 8")
    KnaryBroadcastNode__global_init.writeAction("jmp EFA_Broadcast_vjmvd___if_global_init_26_post")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_43_false: send_wcont X28 X19 X26 8")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_26_post: add X29 X17 X29")
    KnaryBroadcastNode__global_init.writeAction("addi X16 X16 1")
    KnaryBroadcastNode__global_init.writeAction("add X30 X18 X30")
    KnaryBroadcastNode__global_init.writeAction("jmp EFA_Broadcast_vjmvd___for_global_init_12_condition")
    KnaryBroadcastNode__global_init.writeAction("EFA_Broadcast_vjmvd___for_global_init_14_post: addi X1 X19 0")
    KnaryBroadcastNode__global_init.writeAction("movir X20 0")
    KnaryBroadcastNode__global_init.writeAction("movir X21 0")
    KnaryBroadcastNode__global_init.writeAction("movir X22 0")
    KnaryBroadcastNode__global_init.writeAction("movir X23 0")
    KnaryBroadcastNode__global_init.writeAction("yield")

    ## KnaryBroadcastNode__global_sync
    KnaryBroadcastNode__global_sync = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "KnaryBroadcastNode__global_sync")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___entry: sri X2 X30 20")
    KnaryBroadcastNode__global_sync.writeAction("andi X30 X30 7")
    KnaryBroadcastNode__global_sync.writeAction("addi X30 X30 2")
    KnaryBroadcastNode__global_sync.writeAction("blei X30 4 EFA_Broadcast_vjmvd___if_global_sync_2_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_0_true: movir X30 4")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_2_post: movir X28 0")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___for_global_sync_3_condition: ble X30 X28 EFA_Broadcast_vjmvd___for_global_sync_5_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___for_global_sync_4_body: bnei X28 0 EFA_Broadcast_vjmvd___if_global_sync_8_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_6_true: add X20 X8 X20")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_8_post: bnei X28 1 EFA_Broadcast_vjmvd___if_global_sync_14_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_12_true: add X21 X9 X21")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_14_post: bnei X28 2 EFA_Broadcast_vjmvd___if_global_sync_20_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_18_true: add X22 X10 X22")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_20_post: bnei X28 3 EFA_Broadcast_vjmvd___if_global_sync_26_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_24_true: add X23 X11 X23")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_26_post: addi X28 X28 1")
    KnaryBroadcastNode__global_sync.writeAction("jmp EFA_Broadcast_vjmvd___for_global_sync_3_condition")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___for_global_sync_5_post: subi X16 X16 1")
    KnaryBroadcastNode__global_sync.writeAction("bleiu X16 0 EFA_Broadcast_vjmvd___if_global_sync_35_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_33_true: yield")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_35_post: addi X7 X28 8")
    KnaryBroadcastNode__global_sync.writeAction("movrl X20 0(X28) 0 8")
    KnaryBroadcastNode__global_sync.writeAction("movrl X21 8(X28) 0 8")
    KnaryBroadcastNode__global_sync.writeAction("bgti X30 2 EFA_Broadcast_vjmvd___if_global_sync_37_false")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_36_true: movir X24 -1")
    KnaryBroadcastNode__global_sync.writeAction("sri X24 X24 1")
    KnaryBroadcastNode__global_sync.writeAction("send_wcont X19 X24 X28 2")
    KnaryBroadcastNode__global_sync.writeAction("yield_terminate")
    KnaryBroadcastNode__global_sync.writeAction("jmp EFA_Broadcast_vjmvd___if_global_sync_38_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_37_false: bnei X30 3 EFA_Broadcast_vjmvd___if_global_sync_43_false")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_42_true: movrl X22 16(X28) 0 8")
    KnaryBroadcastNode__global_sync.writeAction("movir X24 -1")
    KnaryBroadcastNode__global_sync.writeAction("sri X24 X24 1")
    KnaryBroadcastNode__global_sync.writeAction("send_wcont X19 X24 X28 3")
    KnaryBroadcastNode__global_sync.writeAction("yield_terminate")
    KnaryBroadcastNode__global_sync.writeAction("jmp EFA_Broadcast_vjmvd___if_global_sync_38_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_43_false: bnei X30 4 EFA_Broadcast_vjmvd___if_global_sync_49_false")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_48_true: movrl X22 16(X28) 0 8")
    KnaryBroadcastNode__global_sync.writeAction("movrl X23 24(X28) 0 8")
    KnaryBroadcastNode__global_sync.writeAction("movir X24 -1")
    KnaryBroadcastNode__global_sync.writeAction("sri X24 X24 1")
    KnaryBroadcastNode__global_sync.writeAction("send_wcont X19 X24 X28 4")
    KnaryBroadcastNode__global_sync.writeAction("yield_terminate")
    KnaryBroadcastNode__global_sync.writeAction("jmp EFA_Broadcast_vjmvd___if_global_sync_38_post")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_49_false: print 'Error: Unsupported number of values %lu in global_sync.' X30")
    KnaryBroadcastNode__global_sync.writeAction("movrl X22 16(X28) 0 8")
    KnaryBroadcastNode__global_sync.writeAction("movrl X23 24(X28) 0 8")
    KnaryBroadcastNode__global_sync.writeAction("movir X24 -1")
    KnaryBroadcastNode__global_sync.writeAction("sri X24 X24 1")
    KnaryBroadcastNode__global_sync.writeAction("send_wcont X19 X24 X28 4")
    KnaryBroadcastNode__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_38_post: yield_terminate")

    ## KnaryBroadcastNode__broadcast_nodes
    KnaryBroadcastNode__broadcast_nodes = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "KnaryBroadcastNode__broadcast_nodes")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___entry: movir X28 -1")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sri X28 X28 32")
    KnaryBroadcastNode__broadcast_nodes.writeAction("and X8 X28 X28")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sri X8 X30 32")
    KnaryBroadcastNode__broadcast_nodes.writeAction("bleu X30 X28 EFA_Broadcast_vjmvd___if_broadcast_nodes_4_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_3_true: movir X18 1")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_5_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_4_false: div X28 X30 X18")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_5_post: sli X18 X24 6")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sli X24 X17 5")
    KnaryBroadcastNode__broadcast_nodes.writeAction("bneiu X18 1 EFA_Broadcast_vjmvd___if_broadcast_nodes_10_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_9_true: addi X9 X24 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("addi X0 X25 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("evi X2 X19 KnaryBroadcastNode__node_sync 1")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X16 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sri X2 X26 20")
    KnaryBroadcastNode__broadcast_nodes.writeAction("andi X26 X26 7")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X29 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___for_broadcast_nodes_15_condition: bleu X28 X29 EFA_Broadcast_vjmvd___for_broadcast_nodes_17_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___for_broadcast_nodes_16_body: ev X24 X24 X25 X25 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("bnei X26 9 EFA_Broadcast_vjmvd___if_broadcast_nodes_35_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_34_true: sendops_wcont X24 X19 X10 9")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_35_false: bnei X26 2 EFA_Broadcast_vjmvd___if_broadcast_nodes_37_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_36_true: sendops_wcont X24 X19 X10 2")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_37_false: bnei X26 8 EFA_Broadcast_vjmvd___if_broadcast_nodes_39_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_38_true: sendops_wcont X24 X19 X10 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_39_false: bnei X26 7 EFA_Broadcast_vjmvd___if_broadcast_nodes_41_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_40_true: sendops_wcont X24 X19 X10 7")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_41_false: bnei X26 6 EFA_Broadcast_vjmvd___if_broadcast_nodes_43_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_42_true: sendops_wcont X24 X19 X10 6")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_43_false: bnei X26 5 EFA_Broadcast_vjmvd___if_broadcast_nodes_45_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_44_true: sendops_wcont X24 X19 X10 5")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_45_false: bnei X26 4 EFA_Broadcast_vjmvd___if_broadcast_nodes_47_false")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_46_true: sendops_wcont X24 X19 X10 4")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_47_false: sendops_wcont X24 X19 X10 3")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_33_post: add X25 X17 X25")
    KnaryBroadcastNode__broadcast_nodes.writeAction("addi X16 X16 1")
    KnaryBroadcastNode__broadcast_nodes.writeAction("add X29 X18 X29")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___for_broadcast_nodes_15_condition")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___for_broadcast_nodes_17_post: jmp EFA_Broadcast_vjmvd___if_broadcast_nodes_11_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_10_false: addi X7 X29 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X24 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("evlb X24 KnaryBroadcastNode__broadcast_nodes")
    KnaryBroadcastNode__broadcast_nodes.writeAction("evi X24 X24 255 4")
    KnaryBroadcastNode__broadcast_nodes.writeAction("ev X24 X24 X0 X0 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_21_true: sri X2 X25 20")
    KnaryBroadcastNode__broadcast_nodes.writeAction("andi X25 X25 7")
    KnaryBroadcastNode__broadcast_nodes.writeAction("addi X25 X25 2")
    KnaryBroadcastNode__broadcast_nodes.writeAction("bcpyol X8 X29 X25")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sli X18 X25 6")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sli X25 X17 5")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sli X30 X25 32")
    KnaryBroadcastNode__broadcast_nodes.writeAction("or X25 X18 X25")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movrl X25 0(X29) 0 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("addi X0 X25 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("evi X2 X19 KnaryBroadcastNode__node_sync 1")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X16 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X26 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___for_broadcast_nodes_24_condition: bleu X28 X26 EFA_Broadcast_vjmvd___if_broadcast_nodes_11_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___for_broadcast_nodes_25_body: add X26 X18 X27")
    KnaryBroadcastNode__broadcast_nodes.writeAction("bgtu X28 X27 EFA_Broadcast_vjmvd___if_broadcast_nodes_32_post")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_30_true: sub X28 X26 X27")
    KnaryBroadcastNode__broadcast_nodes.writeAction("sli X30 X31 32")
    KnaryBroadcastNode__broadcast_nodes.writeAction("or X31 X27 X27")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movrl X27 0(X29) 0 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_32_post: ev X24 X24 X25 X25 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("send_wcont X24 X19 X29 8")
    KnaryBroadcastNode__broadcast_nodes.writeAction("add X25 X17 X25")
    KnaryBroadcastNode__broadcast_nodes.writeAction("addi X16 X16 1")
    KnaryBroadcastNode__broadcast_nodes.writeAction("add X26 X18 X26")
    KnaryBroadcastNode__broadcast_nodes.writeAction("jmp EFA_Broadcast_vjmvd___for_broadcast_nodes_24_condition")
    KnaryBroadcastNode__broadcast_nodes.writeAction("EFA_Broadcast_vjmvd___if_broadcast_nodes_11_post: addi X1 X19 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X20 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X21 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X22 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("movir X23 0")
    KnaryBroadcastNode__broadcast_nodes.writeAction("yield")

    ## KnaryBroadcastNode__node_sync
    KnaryBroadcastNode__node_sync = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "KnaryBroadcastNode__node_sync")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___entry: sri X2 X28 20")
    KnaryBroadcastNode__node_sync.writeAction("andi X28 X28 7")
    KnaryBroadcastNode__node_sync.writeAction("addi X28 X28 2")
    KnaryBroadcastNode__node_sync.writeAction("blei X28 4 EFA_Broadcast_vjmvd___if_node_sync_2_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_0_true: movir X28 4")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_2_post: movir X30 0")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___for_node_sync_3_condition: ble X28 X30 EFA_Broadcast_vjmvd___for_node_sync_5_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___for_node_sync_4_body: bnei X30 0 EFA_Broadcast_vjmvd___if_node_sync_8_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_6_true: add X20 X8 X20")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_8_post: bnei X30 1 EFA_Broadcast_vjmvd___if_node_sync_14_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_12_true: add X21 X9 X21")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_14_post: bnei X30 2 EFA_Broadcast_vjmvd___if_node_sync_20_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_18_true: add X22 X10 X22")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_20_post: bnei X30 3 EFA_Broadcast_vjmvd___if_node_sync_26_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_24_true: add X23 X11 X23")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_26_post: addi X30 X30 1")
    KnaryBroadcastNode__node_sync.writeAction("jmp EFA_Broadcast_vjmvd___for_node_sync_3_condition")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___for_node_sync_5_post: subi X16 X16 1")
    KnaryBroadcastNode__node_sync.writeAction("bleiu X16 0 EFA_Broadcast_vjmvd___if_node_sync_35_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_33_true: yield")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_35_post: addi X7 X30 8")
    KnaryBroadcastNode__node_sync.writeAction("movrl X20 0(X30) 0 8")
    KnaryBroadcastNode__node_sync.writeAction("movrl X21 8(X30) 0 8")
    KnaryBroadcastNode__node_sync.writeAction("bgti X28 2 EFA_Broadcast_vjmvd___if_node_sync_37_false")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_36_true: send_wcont X19 X2 X30 2")
    KnaryBroadcastNode__node_sync.writeAction("yield_terminate")
    KnaryBroadcastNode__node_sync.writeAction("jmp EFA_Broadcast_vjmvd___if_node_sync_38_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_37_false: bnei X28 3 EFA_Broadcast_vjmvd___if_node_sync_43_false")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_42_true: movrl X22 16(X30) 0 8")
    KnaryBroadcastNode__node_sync.writeAction("send_wcont X19 X2 X30 3")
    KnaryBroadcastNode__node_sync.writeAction("yield_terminate")
    KnaryBroadcastNode__node_sync.writeAction("jmp EFA_Broadcast_vjmvd___if_node_sync_38_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_43_false: bnei X28 4 EFA_Broadcast_vjmvd___if_node_sync_49_false")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_48_true: movrl X22 16(X30) 0 8")
    KnaryBroadcastNode__node_sync.writeAction("movrl X23 24(X30) 0 8")
    KnaryBroadcastNode__node_sync.writeAction("send_wcont X19 X2 X30 4")
    KnaryBroadcastNode__node_sync.writeAction("yield_terminate")
    KnaryBroadcastNode__node_sync.writeAction("jmp EFA_Broadcast_vjmvd___if_node_sync_38_post")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_49_false: print 'Error: Unsupported number of values %lu in node_sync.' X28")
    KnaryBroadcastNode__node_sync.writeAction("movrl X22 16(X30) 0 8")
    KnaryBroadcastNode__node_sync.writeAction("movrl X23 24(X30) 0 8")
    KnaryBroadcastNode__node_sync.writeAction("send_wcont X19 X2 X30 4")
    KnaryBroadcastNode__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_38_post: yield_terminate")

    ## GlobalSync__global_init
    GlobalSync__global_init = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "GlobalSync__global_init")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___entry: addi X9 X16 0")
    GlobalSync__global_init.writeAction("movir X18 0")
    GlobalSync__global_init.writeAction("movir X21 0")
    GlobalSync__global_init.writeAction("movir X22 0")
    GlobalSync__global_init.writeAction("addi X11 X23 0")
    GlobalSync__global_init.writeAction("addi X10 X19 0")
    GlobalSync__global_init.writeAction("addi X8 X20 0")
    GlobalSync__global_init.writeAction("blei X19 3 EFA_Broadcast_vjmvd___if_global_init_6_true")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_3_true: movir X19 3")
    GlobalSync__global_init.writeAction("print 'Warning: Limiting number of values to %lu in global_sync.' X19")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_6_true: movir X26 2048")
    GlobalSync__global_init.writeAction("div X8 X26 X27")
    GlobalSync__global_init.writeAction("mod X8 X26 X26")
    GlobalSync__global_init.writeAction("beqi X26 0 EFA_Broadcast_vjmvd___if_global_init_11_post")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_9_true: addi X27 X27 1")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_11_post: movir X26 32")
    GlobalSync__global_init.writeAction("bgt X26 X27 EFA_Broadcast_vjmvd___if_global_init_16_false")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_15_true: addi X7 X26 8")
    GlobalSync__global_init.writeAction("movrl X27 0(X26) 0 8")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_18_true: movir X28 0")
    GlobalSync__global_init.writeAction("evlb X28 NodeSync__node_bcst")
    GlobalSync__global_init.writeAction("evi X28 X28 255 4")
    GlobalSync__global_init.writeAction("ev X28 X28 X0 X0 8")
    GlobalSync__global_init.writeAction("movrl X28 8(X26) 0 8")
    GlobalSync__global_init.writeAction("movir X28 0")
    GlobalSync__global_init.writeAction("addi X8 X29 0")
    GlobalSync__global_init.writeAction("or X28 X29 X28")
    GlobalSync__global_init.writeAction("movrl X28 16(X26) 0 8")
    GlobalSync__global_init.writeAction("movrl X19 24(X26) 0 8")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_21_true: addi X26 X28 32")
    GlobalSync__global_init.writeAction("bcpyol X11 X28 X19")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_24_true: movir X28 0")
    GlobalSync__global_init.writeAction("evlb X28 KnaryBroadcastNode__global_init")
    GlobalSync__global_init.writeAction("evi X28 X28 255 4")
    GlobalSync__global_init.writeAction("ev X28 X28 X0 X0 8")
    GlobalSync__global_init.writeAction("send_wret X28 GlobalSync__global_sync X26 8 X29")
    GlobalSync__global_init.writeAction("movir X17 1")
    GlobalSync__global_init.writeAction("jmp EFA_Broadcast_vjmvd___if_global_init_17_post")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_16_false: movir X26 0")
    GlobalSync__global_init.writeAction("evlb X26 NodeSync__node_bcst")
    GlobalSync__global_init.writeAction("evi X26 X26 255 4")
    GlobalSync__global_init.writeAction("ev X26 X26 X0 X0 8")
    GlobalSync__global_init.writeAction("addi X0 X28 0")
    GlobalSync__global_init.writeAction("addi X7 X29 8")
    GlobalSync__global_init.writeAction("movir X30 0")
    GlobalSync__global_init.writeAction("addi X8 X31 0")
    GlobalSync__global_init.writeAction("or X30 X31 X30")
    GlobalSync__global_init.writeAction("movrl X30 0(X29) 0 8")
    GlobalSync__global_init.writeAction("movrl X19 8(X29) 0 8")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_33_true: addi X29 X30 16")
    GlobalSync__global_init.writeAction("bcpyol X11 X30 X19")
    GlobalSync__global_init.writeAction("movir X30 0")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___for_global_init_36_condition: ble X27 X30 EFA_Broadcast_vjmvd___for_global_init_38_post")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___for_global_init_37_body: ev X26 X26 X28 X28 8")
    GlobalSync__global_init.writeAction("send_wret X26 GlobalSync__global_sync X29 8 X31")
    GlobalSync__global_init.writeAction("addi X28 X28 2048")
    GlobalSync__global_init.writeAction("addi X30 X30 1")
    GlobalSync__global_init.writeAction("jmp EFA_Broadcast_vjmvd___for_global_init_36_condition")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___for_global_init_38_post: addi X27 X17 0")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_17_post: blei X19 1 EFA_Broadcast_vjmvd___if_global_init_47_post")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_45_true: addi X12 X24 0")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_47_post: blei X19 2 EFA_Broadcast_vjmvd___if_global_init_50_post")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_48_true: addi X13 X25 0")
    GlobalSync__global_init.writeAction("EFA_Broadcast_vjmvd___if_global_init_50_post: yield")

    ## GlobalSync__global_sync
    GlobalSync__global_sync = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "GlobalSync__global_sync")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___entry: add X18 X8 X18")
    GlobalSync__global_sync.writeAction("blei X19 1 EFA_Broadcast_vjmvd___if_global_sync_2_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_0_true: add X21 X9 X21")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_2_post: blei X19 2 EFA_Broadcast_vjmvd___if_global_sync_5_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_3_true: add X22 X10 X22")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_5_post: subi X17 X17 1")
    GlobalSync__global_sync.writeAction("blei X17 0 EFA_Broadcast_vjmvd___if_global_sync_11_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_9_true: yield")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_11_post: beq X18 X16 EFA_Broadcast_vjmvd___if_global_sync_13_false")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_12_true: movir X27 0")
    GlobalSync__global_sync.writeAction("evlb X27 GlobalSync__global_init")
    GlobalSync__global_sync.writeAction("evi X27 X27 255 4")
    GlobalSync__global_sync.writeAction("ev X27 X27 X0 X0 8")
    GlobalSync__global_sync.writeAction("addi X7 X26 8")
    GlobalSync__global_sync.writeAction("movrl X20 0(X26) 0 8")
    GlobalSync__global_sync.writeAction("movrl X16 8(X26) 0 8")
    GlobalSync__global_sync.writeAction("movrl X19 16(X26) 0 8")
    GlobalSync__global_sync.writeAction("movrl X23 24(X26) 0 8")
    GlobalSync__global_sync.writeAction("blei X19 1 EFA_Broadcast_vjmvd___if_global_sync_20_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_18_true: movrl X24 32(X26) 0 8")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_20_post: blei X19 2 EFA_Broadcast_vjmvd___if_global_sync_23_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_21_true: movrl X25 40(X26) 0 8")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_23_post: send_wcont X27 X1 X26 8")
    GlobalSync__global_sync.writeAction("yield_terminate")
    GlobalSync__global_sync.writeAction("jmp EFA_Broadcast_vjmvd___if_global_sync_14_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_13_false: addi X7 X27 8")
    GlobalSync__global_sync.writeAction("movrl X18 0(X27) 0 8")
    GlobalSync__global_sync.writeAction("blei X19 1 EFA_Broadcast_vjmvd___if_global_sync_29_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_27_true: movrl X21 8(X27) 0 8")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_29_post: blei X19 2 EFA_Broadcast_vjmvd___if_global_sync_35_post")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_33_true: movrl X22 16(X27) 0 8")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_35_post: movir X26 -1")
    GlobalSync__global_sync.writeAction("sri X26 X26 1")
    GlobalSync__global_sync.writeAction("send_wcont X1 X26 X27 8")
    GlobalSync__global_sync.writeAction("yield_terminate")
    GlobalSync__global_sync.writeAction("EFA_Broadcast_vjmvd___if_global_sync_14_post: yield")

    ## NodeSync__node_bcst
    NodeSync__node_bcst = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "NodeSync__node_bcst")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___if_node_bcst_0_true: sli X8 X22 32")
    NodeSync__node_bcst.writeAction("sri X22 X22 32")
    NodeSync__node_bcst.writeAction("sri X8 X23 32")
    NodeSync__node_bcst.writeAction("add X22 X23 X22")
    NodeSync__node_bcst.writeAction("addi X0 X23 2048")
    NodeSync__node_bcst.writeAction("addi X23 X23 0")
    NodeSync__node_bcst.writeAction("ble X23 X22 EFA_Broadcast_vjmvd___if_node_bcst_4_false")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___if_node_bcst_3_true: addi X0 X24 0")
    NodeSync__node_bcst.writeAction("sub X22 X24 X23")
    NodeSync__node_bcst.writeAction("jmp EFA_Broadcast_vjmvd___if_node_bcst_5_post")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___if_node_bcst_4_false: movir X23 2048")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___if_node_bcst_5_post: sari X23 X22 63")
    NodeSync__node_bcst.writeAction("sri X22 X22 58")
    NodeSync__node_bcst.writeAction("add X22 X23 X22")
    NodeSync__node_bcst.writeAction("sari X22 X22 6")
    NodeSync__node_bcst.writeAction("sari X23 X24 63")
    NodeSync__node_bcst.writeAction("sri X24 X24 58")
    NodeSync__node_bcst.writeAction("add X24 X23 X24")
    NodeSync__node_bcst.writeAction("andi X24 X24 -64")
    NodeSync__node_bcst.writeAction("sub X23 X24 X24")
    NodeSync__node_bcst.writeAction("beqi X24 0 EFA_Broadcast_vjmvd___if_node_bcst_11_post")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___if_node_bcst_9_true: addi X22 X22 1")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___if_node_bcst_11_post: addi X0 X24 0")
    NodeSync__node_bcst.writeAction("movir X23 0")
    NodeSync__node_bcst.writeAction("evlb X23 UpdownSync__ud_entry")
    NodeSync__node_bcst.writeAction("evi X23 X23 255 4")
    NodeSync__node_bcst.writeAction("ev X23 X23 X0 X0 8")
    NodeSync__node_bcst.writeAction("addi X7 X25 8")
    NodeSync__node_bcst.writeAction("movrl X8 0(X25) 0 8")
    NodeSync__node_bcst.writeAction("movrl X9 8(X25) 0 8")
    NodeSync__node_bcst.writeAction("addi X25 X26 16")
    NodeSync__node_bcst.writeAction("addi X9 X17 0")
    NodeSync__node_bcst.writeAction("bcpyol X10 X26 X17")
    NodeSync__node_bcst.writeAction("movir X26 0")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___for_node_bcst_12_condition: ble X22 X26 EFA_Broadcast_vjmvd___for_node_bcst_14_post")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___for_node_bcst_13_body: ev X23 X23 X24 X24 8")
    NodeSync__node_bcst.writeAction("send_wret X23 NodeSync__node_sync X25 8 X27")
    NodeSync__node_bcst.writeAction("addi X24 X24 64")
    NodeSync__node_bcst.writeAction("addi X26 X26 1")
    NodeSync__node_bcst.writeAction("jmp EFA_Broadcast_vjmvd___for_node_bcst_12_condition")
    NodeSync__node_bcst.writeAction("EFA_Broadcast_vjmvd___for_node_bcst_14_post: addi X22 X16 0")
    NodeSync__node_bcst.writeAction("addi X1 X21 0")
    NodeSync__node_bcst.writeAction("movir X18 0")
    NodeSync__node_bcst.writeAction("movir X19 0")
    NodeSync__node_bcst.writeAction("movir X20 0")
    NodeSync__node_bcst.writeAction("yield")

    ## NodeSync__node_sync
    NodeSync__node_sync = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "NodeSync__node_sync")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___entry: add X18 X8 X18")
    NodeSync__node_sync.writeAction("blei X17 0 EFA_Broadcast_vjmvd___if_node_sync_2_post")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_0_true: add X19 X9 X19")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_2_post: blei X17 1 EFA_Broadcast_vjmvd___if_node_sync_5_post")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_3_true: add X20 X10 X20")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_5_post: subi X16 X16 1")
    NodeSync__node_sync.writeAction("blei X16 0 EFA_Broadcast_vjmvd___if_node_sync_11_post")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_9_true: yield")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_11_post: addi X7 X22 8")
    NodeSync__node_sync.writeAction("movrl X18 0(X22) 0 8")
    NodeSync__node_sync.writeAction("blei X17 0 EFA_Broadcast_vjmvd___if_node_sync_14_post")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_12_true: movrl X19 8(X22) 0 8")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_14_post: blei X17 1 EFA_Broadcast_vjmvd___if_node_sync_17_post")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_15_true: movrl X20 16(X22) 0 8")
    NodeSync__node_sync.writeAction("EFA_Broadcast_vjmvd___if_node_sync_17_post: movir X26 -1")
    NodeSync__node_sync.writeAction("sri X26 X26 1")
    NodeSync__node_sync.writeAction("send_wcont X21 X26 X22 8")
    NodeSync__node_sync.writeAction("yield_terminate")

    ## UpdownSync__ud_entry
    UpdownSync__ud_entry = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "UpdownSync__ud_entry")
    UpdownSync__ud_entry.writeAction("EFA_Broadcast_vjmvd___entry: movir X19 10")
    UpdownSync__ud_entry.writeAction("movir X20 12288")
    UpdownSync__ud_entry.writeAction("sli X20 X20 16")
    UpdownSync__ud_entry.writeAction("or X20 X0 X20")
    UpdownSync__ud_entry.writeAction("movir X21 0")
    UpdownSync__ud_entry.writeAction("evlb X21 UpdownSync__ud_loop")
    UpdownSync__ud_entry.writeAction("evi X21 X21 255 4")
    UpdownSync__ud_entry.writeAction("ev X21 X21 X20 X20 8")
    UpdownSync__ud_entry.writeAction("addi X7 X20 8")
    UpdownSync__ud_entry.writeAction("movrl X19 0(X20) 0 8")
    UpdownSync__ud_entry.writeAction("movrl X8 8(X20) 0 8")
    UpdownSync__ud_entry.writeAction("movrl X9 16(X20) 0 8")
    UpdownSync__ud_entry.writeAction("addi X20 X19 24")
    UpdownSync__ud_entry.writeAction("bcpyol X10 X19 X9")
    UpdownSync__ud_entry.writeAction("send_wcont X21 X1 X20 8")
    UpdownSync__ud_entry.writeAction("yield_terminate")

    ## UpdownSync__ud_loop
    UpdownSync__ud_loop = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "UpdownSync__ud_loop")
    UpdownSync__ud_loop.writeAction("EFA_Broadcast_vjmvd___entry: subi X8 X21 1")
    UpdownSync__ud_loop.writeAction("bneiu X21 0 EFA_Broadcast_vjmvd___if_ud_loop_2_post")
    UpdownSync__ud_loop.writeAction("EFA_Broadcast_vjmvd___if_ud_loop_0_true: sri X0 X20 6")
    UpdownSync__ud_loop.writeAction("sli X20 X20 6")
    UpdownSync__ud_loop.writeAction("movir X19 0")
    UpdownSync__ud_loop.writeAction("evlb X19 UpdownSync__ud_accum")
    UpdownSync__ud_loop.writeAction("evi X19 X19 255 4")
    UpdownSync__ud_loop.writeAction("ev X19 X19 X20 X20 8")
    UpdownSync__ud_loop.writeAction("addi X7 X20 8")
    UpdownSync__ud_loop.writeAction("movrl X9 0(X20) 0 8")
    UpdownSync__ud_loop.writeAction("movrl X10 8(X20) 0 8")
    UpdownSync__ud_loop.writeAction("addi X20 X22 16")
    UpdownSync__ud_loop.writeAction("bcpyol X11 X22 X10")
    UpdownSync__ud_loop.writeAction("send_wcont X19 X1 X20 8")
    UpdownSync__ud_loop.writeAction("yield_terminate")
    UpdownSync__ud_loop.writeAction("EFA_Broadcast_vjmvd___if_ud_loop_2_post: movir X19 12288")
    UpdownSync__ud_loop.writeAction("sli X19 X19 16")
    UpdownSync__ud_loop.writeAction("or X19 X0 X19")
    UpdownSync__ud_loop.writeAction("movir X20 0")
    UpdownSync__ud_loop.writeAction("evlb X20 UpdownSync__ud_loop")
    UpdownSync__ud_loop.writeAction("evi X20 X20 255 4")
    UpdownSync__ud_loop.writeAction("ev X20 X20 X19 X19 8")
    UpdownSync__ud_loop.writeAction("addi X7 X19 8")
    UpdownSync__ud_loop.writeAction("movrl X21 0(X19) 0 8")
    UpdownSync__ud_loop.writeAction("addi X19 X21 8")
    UpdownSync__ud_loop.writeAction("addi X10 X22 2")
    UpdownSync__ud_loop.writeAction("bcpyol X9 X21 X22")
    UpdownSync__ud_loop.writeAction("send_wcont X20 X1 X19 8")
    UpdownSync__ud_loop.writeAction("yield_terminate")

    ## UpdownSync__ud_accum
    UpdownSync__ud_accum = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "UpdownSync__ud_accum")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___entry: movir X16 0")
    UpdownSync__ud_accum.writeAction("movir X17 0")
    UpdownSync__ud_accum.writeAction("movir X18 0")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_0_true: sli X8 X20 32")
    UpdownSync__ud_accum.writeAction("sari X20 X20 32")
    UpdownSync__ud_accum.writeAction("sari X8 X19 32")
    UpdownSync__ud_accum.writeAction("add X20 X19 X20")
    UpdownSync__ud_accum.writeAction("addi X0 X19 64")
    UpdownSync__ud_accum.writeAction("addi X19 X19 0")
    UpdownSync__ud_accum.writeAction("ble X19 X20 EFA_Broadcast_vjmvd___if_ud_accum_4_false")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_3_true: addi X0 X21 0")
    UpdownSync__ud_accum.writeAction("sub X20 X21 X19")
    UpdownSync__ud_accum.writeAction("jmp EFA_Broadcast_vjmvd___if_ud_accum_5_post")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_4_false: movir X19 64")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_5_post: addi X7 X20 0")
    UpdownSync__ud_accum.writeAction("movir X21 0")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___for_ud_accum_9_condition: ble X19 X21 EFA_Broadcast_vjmvd___for_ud_accum_11_post")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___for_ud_accum_10_body: add X20 X10 X22")
    UpdownSync__ud_accum.writeAction("movlr 0(X22) X23 0 8")
    UpdownSync__ud_accum.writeAction("add X16 X23 X16")
    UpdownSync__ud_accum.writeAction("bleiu X9 1 EFA_Broadcast_vjmvd___if_ud_accum_17_post")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_15_true: add X20 X11 X22")
    UpdownSync__ud_accum.writeAction("movlr 0(X22) X23 0 8")
    UpdownSync__ud_accum.writeAction("add X17 X23 X17")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_17_post: bleiu X9 2 EFA_Broadcast_vjmvd___if_ud_accum_23_post")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_21_true: add X20 X12 X22")
    UpdownSync__ud_accum.writeAction("movlr 0(X22) X23 0 8")
    UpdownSync__ud_accum.writeAction("add X18 X23 X18")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_23_post: movir X23 65536")
    UpdownSync__ud_accum.writeAction("add X20 X23 X20")
    UpdownSync__ud_accum.writeAction("addi X21 X21 1")
    UpdownSync__ud_accum.writeAction("jmp EFA_Broadcast_vjmvd___for_ud_accum_9_condition")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___for_ud_accum_11_post: bleiu X9 2 EFA_Broadcast_vjmvd___if_ud_accum_31_false")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_30_true: movir X20 -1")
    UpdownSync__ud_accum.writeAction("sri X20 X20 1")
    UpdownSync__ud_accum.writeAction("sendr3_wcont X1 X20 X16 X17 X18")
    UpdownSync__ud_accum.writeAction("jmp EFA_Broadcast_vjmvd___if_ud_accum_32_post")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_31_false: bleiu X9 1 EFA_Broadcast_vjmvd___if_ud_accum_34_false")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_33_true: movir X20 -1")
    UpdownSync__ud_accum.writeAction("sri X20 X20 1")
    UpdownSync__ud_accum.writeAction("sendr_wcont X1 X20 X16 X17")
    UpdownSync__ud_accum.writeAction("jmp EFA_Broadcast_vjmvd___if_ud_accum_32_post")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_34_false: movir X20 -1")
    UpdownSync__ud_accum.writeAction("sri X20 X20 1")
    UpdownSync__ud_accum.writeAction("sendr_wcont X1 X20 X16 X16")
    UpdownSync__ud_accum.writeAction("EFA_Broadcast_vjmvd___if_ud_accum_32_post: yield_terminate")