from EFA_v2 import EFA, State, Transition

def efaProgram_PagerankMsrEFA(efa):

    ## init_null_state with ID 0
    init_null_state_0 = State()
    efa.add_state(init_null_state_0)
    efa.add_initId(init_null_state_0.state_id)

    ## Add event ids and names:
    efa.add_name(0, 'Broadcast__broadcast_global')
    efa.add_name(1, 'Broadcast__broadcast_node')
    efa.add_name(2, 'Broadcast__broadcast_ud')
    efa.add_name(3, 'Broadcast__broadcast_ud_fin')
    efa.add_name(4, 'Broadcast__broadcast_node_fin')
    efa.add_name(5, 'Broadcast__broadcast_global_fin')
    efa.add_name(6, 'Broadcast__broadcast_value_to_scratchpad')
    efa.add_name(7, 'pr__map_shuffle_reduce')
    efa.add_name(8, 'pr__finish_init_udkvmsr')
    efa.add_name(9, 'pr__broadcast_global')
    efa.add_name(10, 'pr__broadcast_node')
    efa.add_name(11, 'pr__broadcast_ud')
    efa.add_name(12, 'pr__broadcast_ud_fin')
    efa.add_name(13, 'pr__broadcast_node_fin')
    efa.add_name(14, 'pr__broadcast_global_fin')
    efa.add_name(15, 'pr__broadcast_value_to_scratchpad')
    efa.add_name(16, 'pr__init_input_kvset_on_lane')
    efa.add_name(17, 'pr__init_output_kvset_on_lane')
    efa.add_name(18, 'pr__init_sp_lane')
    efa.add_name(19, 'pr__init_global_master')
    efa.add_name(20, 'pr__global_master')
    efa.add_name(21, 'pr__cache_flush')
    efa.add_name(22, 'pr__cache_flush_return')
    efa.add_name(23, 'pr__init_node_master')
    efa.add_name(24, 'pr__node_master')
    efa.add_name(25, 'pr__termiante_node_master')
    efa.add_name(26, 'pr__init_updown_master')
    efa.add_name(27, 'pr__updown_master')
    efa.add_name(28, 'pr__terminate_updown_master')
    efa.add_name(29, 'pr__lane_master_init')
    efa.add_name(30, 'pr__lane_master_loop')
    efa.add_name(31, 'pr__lane_master_read_partition')
    efa.add_name(32, 'pr__lane_master_get_next_return')
    efa.add_name(33, 'pr__lane_master_terminate')
    efa.add_name(34, 'pr__init_global_snyc')
    efa.add_name(35, 'pr__init_node_sync')
    efa.add_name(36, 'pr__ud_accumulate')
    efa.add_name(37, 'pr__global_sync_return')
    efa.add_name(38, 'pr__node_sync_return')
    efa.add_name(39, 'pr__ud_entry')
    efa.add_name(40, 'pr__ud_delay')
    efa.add_name(41, 'pr__kv_map_emit')
    efa.add_name(42, 'pr__kv_reduce_emit')
    efa.add_name(43, 'pr__kv_map_return')
    efa.add_name(44, 'pr__init_reduce_thread')
    efa.add_name(45, 'pr__combine_get_pair')
    efa.add_name(46, 'pr__combine_put_pair_ack')
    efa.add_name(47, 'pr__kv_reduce_return')
    efa.add_name(48, 'pr__combine_flush_lane')
    efa.add_name(49, 'pr__combine_flush_ack')
    efa.add_name(50, 'updown_init')
    efa.add_name(51, 'updown_terminate')
    efa.add_name(52, 'pr__kv_map')
    efa.add_name(53, 'pr__map_load_return')

    ## Broadcast__broadcast_global with ID 0
    Broadcast__broadcast_global_0 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 0)
    Broadcast__broadcast_global_0.writeAction("addi X8 X27 0")
    Broadcast__broadcast_global_0.writeAction("sri X27 X25 11")
    Broadcast__broadcast_global_0.writeAction("movir X16 16384")
    Broadcast__broadcast_global_0.writeAction("bgt X25 X16 GenLinkableBroadcast_bpvbz_max_child_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("andi X27 X16 2047")
    Broadcast__broadcast_global_0.writeAction("beqi X16 0 GenLinkableBroadcast_bpvbz_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("addi X25 X25 1")
    Broadcast__broadcast_global_0.writeAction("jmp GenLinkableBroadcast_bpvbz_modular_eq_zero")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_bpvbz_max_child_modular_eq_zero: mov_imm2reg X25 16384")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_bpvbz_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_global_0.writeAction("evlb X28 1")
    Broadcast__broadcast_global_0.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_global_0.writeAction("GenLinkableBroadcast_bpvbz_broadcast_loop: lshift X17 X16 11")
    Broadcast__broadcast_global_0.writeAction("add X0 X16 X16")
    Broadcast__broadcast_global_0.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_global_0.writeAction("sendops_wret X28 5 X8 8 X16")
    Broadcast__broadcast_global_0.writeAction("addi X17 X17 1")
    Broadcast__broadcast_global_0.writeAction("blt X17 X25 GenLinkableBroadcast_bpvbz_broadcast_loop")
    Broadcast__broadcast_global_0.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_global_0.writeAction("yield")

    ## Broadcast__broadcast_node with ID 1
    Broadcast__broadcast_node_1 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 1)
    Broadcast__broadcast_node_1.writeAction("addi X1 X29 0")
    Broadcast__broadcast_node_1.writeAction("sri X8 X25 6")
    Broadcast__broadcast_node_1.writeAction("movir X16 32")
    Broadcast__broadcast_node_1.writeAction("bgt X25 X16 GenLinkableBroadcast_bpvbz_max_child_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("andi X8 X16 63")
    Broadcast__broadcast_node_1.writeAction("beqi X16 0 GenLinkableBroadcast_bpvbz_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("addi X25 X25 1")
    Broadcast__broadcast_node_1.writeAction("jmp GenLinkableBroadcast_bpvbz_modular_eq_zero")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_bpvbz_max_child_modular_eq_zero: mov_imm2reg X25 32")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_bpvbz_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_node_1.writeAction("evlb X28 2")
    Broadcast__broadcast_node_1.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_node_1.writeAction("GenLinkableBroadcast_bpvbz_broadcast_loop: lshift X17 X16 6")
    Broadcast__broadcast_node_1.writeAction("add X0 X16 X16")
    Broadcast__broadcast_node_1.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_node_1.writeAction("sendops_wret X28 4 X8 8 X16")
    Broadcast__broadcast_node_1.writeAction("addi X17 X17 1")
    Broadcast__broadcast_node_1.writeAction("blt X17 X25 GenLinkableBroadcast_bpvbz_broadcast_loop")
    Broadcast__broadcast_node_1.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_node_1.writeAction("yield")

    ## Broadcast__broadcast_ud with ID 2
    Broadcast__broadcast_ud_2 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 2)
    Broadcast__broadcast_ud_2.writeAction("addi X1 X29 0")
    Broadcast__broadcast_ud_2.writeAction("movir X25 64")
    Broadcast__broadcast_ud_2.writeAction("bgt X8 X25 GenLinkableBroadcast_bpvbz_modular_eq_zero")
    Broadcast__broadcast_ud_2.writeAction("addi X8 X25 0")
    Broadcast__broadcast_ud_2.writeAction("GenLinkableBroadcast_bpvbz_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_ud_2.writeAction("ev X28 X28 X9 X9 1")
    Broadcast__broadcast_ud_2.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_ud_2.writeAction("GenLinkableBroadcast_bpvbz_broadcast_loop: add X0 X17 X16")
    Broadcast__broadcast_ud_2.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_ud_2.writeAction("sendops_wret X28 3 X10 6 X16")
    Broadcast__broadcast_ud_2.writeAction("addi X17 X17 1")
    Broadcast__broadcast_ud_2.writeAction("blt X17 X25 GenLinkableBroadcast_bpvbz_broadcast_loop")
    Broadcast__broadcast_ud_2.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_ud_2.writeAction("yield")

    ## Broadcast__broadcast_ud_fin with ID 3
    Broadcast__broadcast_ud_fin_3 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 3)
    Broadcast__broadcast_ud_fin_3.writeAction("addi X26 X26 1")
    Broadcast__broadcast_ud_fin_3.writeAction("blt X26 X25 GenLinkableBroadcast_bpvbz_continue")
    Broadcast__broadcast_ud_fin_3.writeAction("movir X30 -1")
    Broadcast__broadcast_ud_fin_3.writeAction("sri X30 X30 1")
    Broadcast__broadcast_ud_fin_3.writeAction("sendr_wcont X29 X30 X0 X2 ")
    Broadcast__broadcast_ud_fin_3.writeAction("yield_terminate")
    Broadcast__broadcast_ud_fin_3.writeAction("GenLinkableBroadcast_bpvbz_continue: yield")

    ## Broadcast__broadcast_node_fin with ID 4
    Broadcast__broadcast_node_fin_4 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 4)
    Broadcast__broadcast_node_fin_4.writeAction("addi X26 X26 1")
    Broadcast__broadcast_node_fin_4.writeAction("blt X26 X25 GenLinkableBroadcast_bpvbz_continue")
    Broadcast__broadcast_node_fin_4.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_node_fin_4.writeAction("yield_terminate")
    Broadcast__broadcast_node_fin_4.writeAction("GenLinkableBroadcast_bpvbz_continue: yield")

    ## Broadcast__broadcast_global_fin with ID 5
    Broadcast__broadcast_global_fin_5 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 5)
    Broadcast__broadcast_global_fin_5.writeAction("addi X26 X26 1")
    Broadcast__broadcast_global_fin_5.writeAction("beq X26 X25 GenLinkableBroadcast_bpvbz_global_bcst_finish")
    Broadcast__broadcast_global_fin_5.writeAction("yield")
    Broadcast__broadcast_global_fin_5.writeAction("GenLinkableBroadcast_bpvbz_global_bcst_finish: sendr_reply X0 X2 X16")
    Broadcast__broadcast_global_fin_5.writeAction("yieldt")

    ## Broadcast__broadcast_value_to_scratchpad with ID 6
    Broadcast__broadcast_value_to_scratchpad_6 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 6)
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("sri X8 X16 32")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("add X7 X16 X16")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("andi X8 X17 15")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("bcpyol X9 X16 X17")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("sendr_reply X1 X2 X16")
    Broadcast__broadcast_value_to_scratchpad_6.writeAction("yieldt")

    ## pr__map_shuffle_reduce with ID 7
    pr__map_shuffle_reduce_7 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 7)
    pr__map_shuffle_reduce_7.writeAction("addi X7 X20 112")
    pr__map_shuffle_reduce_7.writeAction("addi X1 X31 0")
    pr__map_shuffle_reduce_7.writeAction("move X31 0(X20) 0 8")
    pr__map_shuffle_reduce_7.writeAction("addi X8 X16 0")
    pr__map_shuffle_reduce_7.writeAction("addi X10 X27 0")
    pr__map_shuffle_reduce_7.writeAction("mul X9 X27 X19")
    pr__map_shuffle_reduce_7.writeAction("addi X2 X21 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X21 8")
    pr__map_shuffle_reduce_7.writeAction("addi X7 X20 192")
    pr__map_shuffle_reduce_7.writeAction("addi X11 X29 0")
    pr__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    pr__map_shuffle_reduce_7.writeAction("sendr_wcont X21 X21 X16 X19 ")
    pr__map_shuffle_reduce_7.writeAction("evi X2 X30 255 4")
    pr__map_shuffle_reduce_7.writeAction("evlb X30 9")
    pr__map_shuffle_reduce_7.writeAction("movir X17 128")
    pr__map_shuffle_reduce_7.writeAction("add X7 X17 X17")
    pr__map_shuffle_reduce_7.writeAction("movrl X27 0(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("movir X18 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X18 18")
    pr__map_shuffle_reduce_7.writeAction("movrl X18 8(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("movrl X27  16(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("movrl X0 24(X17) 0 8")
    pr__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8")
    pr__map_shuffle_reduce_7.writeAction("addi X17 X20 8")
    pr__map_shuffle_reduce_7.writeAction("movir X18 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X18 16")
    pr__map_shuffle_reduce_7.writeAction("movrl X18 0(X20) 1 8")
    pr__map_shuffle_reduce_7.writeAction("addi X11 X29 0")
    pr__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    pr__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8")
    pr__map_shuffle_reduce_7.writeAction("addi X17 X20 8")
    pr__map_shuffle_reduce_7.writeAction("movir X18 0")
    pr__map_shuffle_reduce_7.writeAction("evlb X18 17")
    pr__map_shuffle_reduce_7.writeAction("movrl X18 0(X20) 1 8")
    pr__map_shuffle_reduce_7.writeAction("addi X12 X29 0")
    pr__map_shuffle_reduce_7.writeAction("bcpylli X29 X20 16")
    pr__map_shuffle_reduce_7.writeAction("send_wcont X30 X21 X17 8 ")
    pr__map_shuffle_reduce_7.writeAction("movir X26 0")
    pr__map_shuffle_reduce_7.writeAction("addi X9 X19 0")
    pr__map_shuffle_reduce_7.writeAction("yield")

    ## pr__finish_init_udkvmsr with ID 8
    pr__finish_init_udkvmsr_8 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 8)
    pr__finish_init_udkvmsr_8.writeAction("perflog 1 0 'UDKVMSR Initializat Finished.' ")
    pr__finish_init_udkvmsr_8.writeAction("addi X26 X26 1")
    pr__finish_init_udkvmsr_8.writeAction("bgei X26 4 GenMSRPagerankEFA_xvlsl_finish_initialize_udkvmsr")
    pr__finish_init_udkvmsr_8.writeAction("yield")
    pr__finish_init_udkvmsr_8.writeAction("GenMSRPagerankEFA_xvlsl_finish_initialize_udkvmsr: addi X2 X30 0")
    pr__finish_init_udkvmsr_8.writeAction("evlb X30 19")
    pr__finish_init_udkvmsr_8.writeAction("sendr_wcont X30 X31 X16 X19")
    pr__finish_init_udkvmsr_8.writeAction("yield")

    ## pr__broadcast_global with ID 9
    pr__broadcast_global_9 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 9)
    pr__broadcast_global_9.writeAction("addi X8 X27 0")
    pr__broadcast_global_9.writeAction("sri X27 X25 11")
    pr__broadcast_global_9.writeAction("movir X16 16384")
    pr__broadcast_global_9.writeAction("bgt X25 X16 GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero")
    pr__broadcast_global_9.writeAction("andi X27 X16 2047")
    pr__broadcast_global_9.writeAction("beqi X16 0 GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__broadcast_global_9.writeAction("addi X25 X25 1")
    pr__broadcast_global_9.writeAction("jmp GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__broadcast_global_9.writeAction("GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero: mov_imm2reg X25 16384")
    pr__broadcast_global_9.writeAction("GenMSRPagerankEFA_xvlsl_modular_eq_zero: evi X2 X28 255 4")
    pr__broadcast_global_9.writeAction("evlb X28 10")
    pr__broadcast_global_9.writeAction("mov_imm2reg X17 0")
    pr__broadcast_global_9.writeAction("GenMSRPagerankEFA_xvlsl_broadcast_loop: lshift X17 X16 11")
    pr__broadcast_global_9.writeAction("add X0 X16 X16")
    pr__broadcast_global_9.writeAction("ev X28 X28 X16 X16 8")
    pr__broadcast_global_9.writeAction("sendops_wret X28 14 X8 8 X16")
    pr__broadcast_global_9.writeAction("addi X17 X17 1")
    pr__broadcast_global_9.writeAction("blt X17 X25 GenMSRPagerankEFA_xvlsl_broadcast_loop")
    pr__broadcast_global_9.writeAction("mov_imm2reg X26 0")
    pr__broadcast_global_9.writeAction("yield")

    ## pr__broadcast_node with ID 10
    pr__broadcast_node_10 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 10)
    pr__broadcast_node_10.writeAction("addi X1 X29 0")
    pr__broadcast_node_10.writeAction("sri X8 X25 6")
    pr__broadcast_node_10.writeAction("movir X16 32")
    pr__broadcast_node_10.writeAction("bgt X25 X16 GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero")
    pr__broadcast_node_10.writeAction("andi X8 X16 63")
    pr__broadcast_node_10.writeAction("beqi X16 0 GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__broadcast_node_10.writeAction("addi X25 X25 1")
    pr__broadcast_node_10.writeAction("jmp GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__broadcast_node_10.writeAction("GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero: mov_imm2reg X25 32")
    pr__broadcast_node_10.writeAction("GenMSRPagerankEFA_xvlsl_modular_eq_zero: evi X2 X28 255 4")
    pr__broadcast_node_10.writeAction("evlb X28 11")
    pr__broadcast_node_10.writeAction("mov_imm2reg X17 0")
    pr__broadcast_node_10.writeAction("GenMSRPagerankEFA_xvlsl_broadcast_loop: lshift X17 X16 6")
    pr__broadcast_node_10.writeAction("add X0 X16 X16")
    pr__broadcast_node_10.writeAction("ev X28 X28 X16 X16 8")
    pr__broadcast_node_10.writeAction("sendops_wret X28 13 X8 8 X16")
    pr__broadcast_node_10.writeAction("addi X17 X17 1")
    pr__broadcast_node_10.writeAction("blt X17 X25 GenMSRPagerankEFA_xvlsl_broadcast_loop")
    pr__broadcast_node_10.writeAction("mov_imm2reg X26 0")
    pr__broadcast_node_10.writeAction("yield")

    ## pr__broadcast_ud with ID 11
    pr__broadcast_ud_11 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 11)
    pr__broadcast_ud_11.writeAction("addi X1 X29 0")
    pr__broadcast_ud_11.writeAction("movir X25 64")
    pr__broadcast_ud_11.writeAction("bgt X8 X25 GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__broadcast_ud_11.writeAction("addi X8 X25 0")
    pr__broadcast_ud_11.writeAction("GenMSRPagerankEFA_xvlsl_modular_eq_zero: evi X2 X28 255 4")
    pr__broadcast_ud_11.writeAction("ev X28 X28 X9 X9 1")
    pr__broadcast_ud_11.writeAction("mov_imm2reg X17 0")
    pr__broadcast_ud_11.writeAction("GenMSRPagerankEFA_xvlsl_broadcast_loop: add X0 X17 X16")
    pr__broadcast_ud_11.writeAction("ev X28 X28 X16 X16 8")
    pr__broadcast_ud_11.writeAction("sendops_wret X28 12 X10 6 X16")
    pr__broadcast_ud_11.writeAction("addi X17 X17 1")
    pr__broadcast_ud_11.writeAction("blt X17 X25 GenMSRPagerankEFA_xvlsl_broadcast_loop")
    pr__broadcast_ud_11.writeAction("mov_imm2reg X26 0")
    pr__broadcast_ud_11.writeAction("yield")

    ## pr__broadcast_ud_fin with ID 12
    pr__broadcast_ud_fin_12 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 12)
    pr__broadcast_ud_fin_12.writeAction("addi X26 X26 1")
    pr__broadcast_ud_fin_12.writeAction("blt X26 X25 GenMSRPagerankEFA_xvlsl_continue")
    pr__broadcast_ud_fin_12.writeAction("movir X30 -1")
    pr__broadcast_ud_fin_12.writeAction("sri X30 X30 1")
    pr__broadcast_ud_fin_12.writeAction("sendr_wcont X29 X30 X0 X2 ")
    pr__broadcast_ud_fin_12.writeAction("yield_terminate")
    pr__broadcast_ud_fin_12.writeAction("GenMSRPagerankEFA_xvlsl_continue: yield")

    ## pr__broadcast_node_fin with ID 13
    pr__broadcast_node_fin_13 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 13)
    pr__broadcast_node_fin_13.writeAction("addi X26 X26 1")
    pr__broadcast_node_fin_13.writeAction("blt X26 X25 GenMSRPagerankEFA_xvlsl_continue")
    pr__broadcast_node_fin_13.writeAction("sendr_reply X0 X2 X16")
    pr__broadcast_node_fin_13.writeAction("yield_terminate")
    pr__broadcast_node_fin_13.writeAction("GenMSRPagerankEFA_xvlsl_continue: yield")

    ## pr__broadcast_global_fin with ID 14
    pr__broadcast_global_fin_14 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 14)
    pr__broadcast_global_fin_14.writeAction("addi X26 X26 1")
    pr__broadcast_global_fin_14.writeAction("beq X26 X25 GenMSRPagerankEFA_xvlsl_global_bcst_finish")
    pr__broadcast_global_fin_14.writeAction("yield")
    pr__broadcast_global_fin_14.writeAction("GenMSRPagerankEFA_xvlsl_global_bcst_finish: sendr_reply X0 X2 X16")
    pr__broadcast_global_fin_14.writeAction("yieldt")

    ## pr__broadcast_value_to_scratchpad with ID 15
    pr__broadcast_value_to_scratchpad_15 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 15)
    pr__broadcast_value_to_scratchpad_15.writeAction("sri X8 X16 32")
    pr__broadcast_value_to_scratchpad_15.writeAction("add X7 X16 X16")
    pr__broadcast_value_to_scratchpad_15.writeAction("andi X8 X17 15")
    pr__broadcast_value_to_scratchpad_15.writeAction("bcpyol X9 X16 X17")
    pr__broadcast_value_to_scratchpad_15.writeAction("sendr_reply X1 X2 X16")
    pr__broadcast_value_to_scratchpad_15.writeAction("yieldt")

    ## pr__init_input_kvset_on_lane with ID 16
    pr__init_input_kvset_on_lane_16 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 16)
    pr__init_input_kvset_on_lane_16.writeAction("movir X16 192")
    pr__init_input_kvset_on_lane_16.writeAction("add X7 X16 X16")
    pr__init_input_kvset_on_lane_16.writeAction("bcpyoli X8 X16 2")
    pr__init_input_kvset_on_lane_16.writeAction("sendr_reply X0 X16 X28")
    pr__init_input_kvset_on_lane_16.writeAction("yield_terminate")

    ## pr__init_output_kvset_on_lane with ID 17
    pr__init_output_kvset_on_lane_17 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 17)
    pr__init_output_kvset_on_lane_17.writeAction("movir X16 256")
    pr__init_output_kvset_on_lane_17.writeAction("add X7 X16 X16")
    pr__init_output_kvset_on_lane_17.writeAction("bcpyoli X8 X16  2")
    pr__init_output_kvset_on_lane_17.writeAction("sendr_reply X0 X16 X28")
    pr__init_output_kvset_on_lane_17.writeAction("yield_terminate")

    ## pr__init_sp_lane with ID 18
    pr__init_sp_lane_18 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 18)
    pr__init_sp_lane_18.writeAction("mov_imm2reg UDPR_0 0")
    pr__init_sp_lane_18.writeAction("addi X7 X20 64")
    pr__init_sp_lane_18.writeAction("move UDPR_0 0(X20) 0 8")
    pr__init_sp_lane_18.writeAction("move UDPR_0 8(X20) 0 8")
    pr__init_sp_lane_18.writeAction("move UDPR_0 24(X20) 0 8")
    pr__init_sp_lane_18.writeAction("movir X28 220")
    pr__init_sp_lane_18.writeAction("move X28 32(X20) 0 8")
    pr__init_sp_lane_18.writeAction("subi X8 X28 1")
    pr__init_sp_lane_18.writeAction("move X28 40(X20) 0 8")
    pr__init_sp_lane_18.writeAction("move X9 56(X20) 0 8")
    pr__init_sp_lane_18.writeAction("movir X16 -1")
    pr__init_sp_lane_18.writeAction("movir X19 4000")
    pr__init_sp_lane_18.writeAction("movir X17 328")
    pr__init_sp_lane_18.writeAction("add X7 X17 X17")
    pr__init_sp_lane_18.writeAction("mov_imm2reg X18 0")
    pr__init_sp_lane_18.writeAction("GenMSRPagerankEFA_xvlsl_init_cache_loop: movwrl X16 X17(X18,1,1)")
    pr__init_sp_lane_18.writeAction("blt X18 X19 GenMSRPagerankEFA_xvlsl_init_cache_loop")
    pr__init_sp_lane_18.writeAction("sendr_reply X0 X16 X28")
    pr__init_sp_lane_18.writeAction("yield_terminate")

    ## pr__init_global_master with ID 19
    pr__init_global_master_19 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 19)
    pr__init_global_master_19.writeAction("mul X27 X9 X24")
    pr__init_global_master_19.writeAction("sri X27 X25 11")
    pr__init_global_master_19.writeAction("movir X28 16384")
    pr__init_global_master_19.writeAction("bgt X25 X28 GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero")
    pr__init_global_master_19.writeAction("andi X27 X28 2047")
    pr__init_global_master_19.writeAction("beqi X28 0 GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__init_global_master_19.writeAction("addi X25 X25 1")
    pr__init_global_master_19.writeAction("jmp GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero: mov_imm2reg X25 16384")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_xvlsl_modular_eq_zero: mov_imm2reg X22 2048")
    pr__init_global_master_19.writeAction("bge X27 X22 GenMSRPagerankEFA_xvlsl_global_master_full_child")
    pr__init_global_master_19.writeAction("addi X27 X22 0")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_xvlsl_global_master_full_child: mul X22 X9 X20")
    pr__init_global_master_19.writeAction("lshift X20 X18 4")
    pr__init_global_master_19.writeAction("mov_reg2reg X0 X23")
    pr__init_global_master_19.writeAction("movir X21 0")
    pr__init_global_master_19.writeAction("evi X2 X30 255 4")
    pr__init_global_master_19.writeAction("evlb X30 23")
    pr__init_global_master_19.writeAction("GenMSRPagerankEFA_xvlsl_glb_master_loop: ev_update_reg_2             X30 X30 X23 X23 8")
    pr__init_global_master_19.writeAction("sendr3_wret X30 20             X16 X18 X27 X28")
    pr__init_global_master_19.writeAction("add X22 X23 X23")
    pr__init_global_master_19.writeAction("add X18 X16 X16 ")
    pr__init_global_master_19.writeAction("addi X21 X21 1")
    pr__init_global_master_19.writeAction("blt X21 X25 GenMSRPagerankEFA_xvlsl_glb_master_loop")
    pr__init_global_master_19.writeAction("mul X21 X20 X17")
    pr__init_global_master_19.writeAction("mov_imm2reg X19 0")
    pr__init_global_master_19.writeAction("yield")

    ## pr__global_master with ID 20
    pr__global_master_20 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 20)
    pr__global_master_20.writeAction("add X8 X19 X19")
    pr__global_master_20.writeAction("bge X17 X24 GenMSRPagerankEFA_xvlsl_global_master_fin_fetch")
    pr__global_master_20.writeAction("sendr3_wret X1 20             X16 X18 X27 X28")
    pr__global_master_20.writeAction("add X20 X17 X17")
    pr__global_master_20.writeAction("add X18 X16 X16 ")
    pr__global_master_20.writeAction("yield")
    pr__global_master_20.writeAction("GenMSRPagerankEFA_xvlsl_global_master_fin_fetch: subi X21 X21 1")
    pr__global_master_20.writeAction("addi X1 X30 0")
    pr__global_master_20.writeAction("evlb X30 25")
    pr__global_master_20.writeAction("sendr_wcont X30 X2 X16 X16")
    pr__global_master_20.writeAction("beqi X21 0 GenMSRPagerankEFA_xvlsl_global_master_fin_map")
    pr__global_master_20.writeAction("yield")
    pr__global_master_20.writeAction("GenMSRPagerankEFA_xvlsl_global_master_fin_map: bnei X19 0 GenMSRPagerankEFA_xvlsl_global_master_init_sync")
    pr__global_master_20.writeAction("movir X28 -1")
    pr__global_master_20.writeAction("sri X28 X28 1")
    pr__global_master_20.writeAction("sendr_wcont X31 X28 X27 X19")
    pr__global_master_20.writeAction("yieldt")
    pr__global_master_20.writeAction("GenMSRPagerankEFA_xvlsl_global_master_init_sync: evi X2 X30 255 4")
    pr__global_master_20.writeAction("evlb X30 34")
    pr__global_master_20.writeAction("addi X2 X28 0")
    pr__global_master_20.writeAction("evlb X28 21")
    pr__global_master_20.writeAction("sendr_wcont X30 X28 X27 X19")
    pr__global_master_20.writeAction("yield")

    ## pr__cache_flush with ID 21
    pr__cache_flush_21 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 21)
    pr__cache_flush_21.writeAction("movir X20 128")
    pr__cache_flush_21.writeAction("add X20 X7 X20")
    pr__cache_flush_21.writeAction("movrl X27 0(X20) 0 8")
    pr__cache_flush_21.writeAction("movir X28 0")
    pr__cache_flush_21.writeAction("evlb X28 48")
    pr__cache_flush_21.writeAction("movrl X28 8(X20) 0 8")
    pr__cache_flush_21.writeAction("evi X2 X30 255 4")
    pr__cache_flush_21.writeAction("evlb X30 9")
    pr__cache_flush_21.writeAction("send_wret X30 22 X20 8 X28")
    pr__cache_flush_21.writeAction("yield")

    ## pr__cache_flush_return with ID 22
    pr__cache_flush_return_22 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 22)
    pr__cache_flush_return_22.writeAction("print ' '")
    pr__cache_flush_return_22.writeAction("print '[DEBUG][NWID %ld][pr::cache_flush_return] Finish flushing the cache. UDKVMSR program pr terminates, number of reduce task process = %ld. Return to user continuation %lu' X0 X19 X31")
    pr__cache_flush_return_22.writeAction("movir X28 -1")
    pr__cache_flush_return_22.writeAction("sri X28 X28 1")
    pr__cache_flush_return_22.writeAction("sendr_wcont X31 X28 X19 X19")
    pr__cache_flush_return_22.writeAction("yieldt")

    ## pr__init_node_master with ID 23
    pr__init_node_master_23 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 23)
    pr__init_node_master_23.writeAction("mov_reg2reg X1 X31")
    pr__init_node_master_23.writeAction("mov_reg2reg X8 X16")
    pr__init_node_master_23.writeAction("mov_reg2reg X10 X27")
    pr__init_node_master_23.writeAction("sri X27 X25 6")
    pr__init_node_master_23.writeAction("movir X28 32")
    pr__init_node_master_23.writeAction("bgt X25 X28 GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero")
    pr__init_node_master_23.writeAction("andi X27 X28 63")
    pr__init_node_master_23.writeAction("beqi X28 0 GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__init_node_master_23.writeAction("addi X25 X25 1")
    pr__init_node_master_23.writeAction("jmp GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_xvlsl_max_child_modular_eq_zero: mov_imm2reg X25 32")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_xvlsl_modular_eq_zero: add X9 X16 X24")
    pr__init_node_master_23.writeAction("mov_imm2reg X21 0")
    pr__init_node_master_23.writeAction("mov_imm2reg X22 64")
    pr__init_node_master_23.writeAction("bge X27 X22 GenMSRPagerankEFA_xvlsl_node_master_full_child")
    pr__init_node_master_23.writeAction("addi X27 X22 0")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_xvlsl_node_master_full_child: div X9 X25 X18")
    pr__init_node_master_23.writeAction("addi X0 X23 0")
    pr__init_node_master_23.writeAction("evi X2 X30 255 4")
    pr__init_node_master_23.writeAction("evlb X30 26")
    pr__init_node_master_23.writeAction("GenMSRPagerankEFA_xvlsl_node_master_loop: ev X30 X30 X23 X23 8")
    pr__init_node_master_23.writeAction("sendr3_wret X30 24             X16 X18 X27 X28")
    pr__init_node_master_23.writeAction("add X22 X23 X23")
    pr__init_node_master_23.writeAction("add X18 X16 X16 ")
    pr__init_node_master_23.writeAction("addi X21 X21 1")
    pr__init_node_master_23.writeAction("blt X21 X25 GenMSRPagerankEFA_xvlsl_node_master_loop")
    pr__init_node_master_23.writeAction("mov_imm2reg X19 0")
    pr__init_node_master_23.writeAction("yield")

    ## pr__node_master with ID 24
    pr__node_master_24 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 24)
    pr__node_master_24.writeAction("add X8 X19 X19")
    pr__node_master_24.writeAction("bge X16 X24 GenMSRPagerankEFA_xvlsl_node_master_fin_fetch")
    pr__node_master_24.writeAction("sendr3_wret X1 24             X16 X18 X27 X28")
    pr__node_master_24.writeAction("add X18 X16 X16 ")
    pr__node_master_24.writeAction("yield")
    pr__node_master_24.writeAction("GenMSRPagerankEFA_xvlsl_node_master_fin_fetch: subi X21 X21 1")
    pr__node_master_24.writeAction("addi X1 X30 0")
    pr__node_master_24.writeAction("evlb X30 28")
    pr__node_master_24.writeAction("sendr_wcont X30 X2 X16 X22")
    pr__node_master_24.writeAction("beqi X21 0 GenMSRPagerankEFA_xvlsl_node_master_fin_partition")
    pr__node_master_24.writeAction("yield")
    pr__node_master_24.writeAction("GenMSRPagerankEFA_xvlsl_node_master_fin_partition: sendr_wret X31 23             X19 X19 X28")
    pr__node_master_24.writeAction("mov_imm2reg X19 0")
    pr__node_master_24.writeAction("yield")

    ## pr__termiante_node_master with ID 25
    pr__termiante_node_master_25 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 25)
    pr__termiante_node_master_25.writeAction("yield_terminate")

    ## pr__init_updown_master with ID 26
    pr__init_updown_master_26 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 26)
    pr__init_updown_master_26.writeAction("mov_reg2reg X1 X31")
    pr__init_updown_master_26.writeAction("mov_reg2reg X8 X16")
    pr__init_updown_master_26.writeAction("mov_reg2reg X10 X27")
    pr__init_updown_master_26.writeAction("movir X25 64")
    pr__init_updown_master_26.writeAction("bgt X27 X25 GenMSRPagerankEFA_xvlsl_modular_eq_zero")
    pr__init_updown_master_26.writeAction("addi X27 X25 0")
    pr__init_updown_master_26.writeAction("GenMSRPagerankEFA_xvlsl_modular_eq_zero: add X9 X16 X24")
    pr__init_updown_master_26.writeAction("mov_imm2reg X21 0")
    pr__init_updown_master_26.writeAction("mov_imm2reg X18 16")
    pr__init_updown_master_26.writeAction("mov_reg2reg X0 X23")
    pr__init_updown_master_26.writeAction("evi X2 X30 255 4")
    pr__init_updown_master_26.writeAction("evlb X30 29")
    pr__init_updown_master_26.writeAction("GenMSRPagerankEFA_xvlsl_updown_master_loop: ev X30 X30 X23 X23 8")
    pr__init_updown_master_26.writeAction("sendr3_wret X30 27             X16 X18 X21 X28")
    pr__init_updown_master_26.writeAction("addi X23 X23 1")
    pr__init_updown_master_26.writeAction("add X18 X16 X16 ")
    pr__init_updown_master_26.writeAction("addi X21 X21 1")
    pr__init_updown_master_26.writeAction("blt X21 X25 GenMSRPagerankEFA_xvlsl_updown_master_loop")
    pr__init_updown_master_26.writeAction("mov_imm2reg X19 0")
    pr__init_updown_master_26.writeAction("addi X21 X22 0")
    pr__init_updown_master_26.writeAction("yield")

    ## pr__updown_master with ID 27
    pr__updown_master_27 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 27)
    pr__updown_master_27.writeAction("add X8 X19 X19")
    pr__updown_master_27.writeAction("bge X16 X24 GenMSRPagerankEFA_xvlsl_updown_master_fin_fetch")
    pr__updown_master_27.writeAction("sendr3_wret X1 27                 X16 X18 X22 X28")
    pr__updown_master_27.writeAction("addi X22 X22 1")
    pr__updown_master_27.writeAction("add X18 X16 X16 ")
    pr__updown_master_27.writeAction("yield")
    pr__updown_master_27.writeAction("GenMSRPagerankEFA_xvlsl_updown_master_fin_fetch: subi X21 X21 1")
    pr__updown_master_27.writeAction("addi X1 X30 0")
    pr__updown_master_27.writeAction("evlb X30 33")
    pr__updown_master_27.writeAction("sendr_wcont X30 X2 X16 X22")
    pr__updown_master_27.writeAction("blei X21 0 GenMSRPagerankEFA_xvlsl_updown_master_fin_partition")
    pr__updown_master_27.writeAction("yield")
    pr__updown_master_27.writeAction("GenMSRPagerankEFA_xvlsl_updown_master_fin_partition: sendr_wret X31             26 X19 X19 X28")
    pr__updown_master_27.writeAction("mov_imm2reg X19 0")
    pr__updown_master_27.writeAction("yield")

    ## pr__terminate_updown_master with ID 28
    pr__terminate_updown_master_28 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 28)
    pr__terminate_updown_master_28.writeAction("yield_terminate")

    ## pr__lane_master_init with ID 29
    pr__lane_master_init_29 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 29)
    pr__lane_master_init_29.writeAction("addi X1 X31 0")
    pr__lane_master_init_29.writeAction("send_dmlm_ld_wret X8 31 2 X28")
    pr__lane_master_init_29.writeAction("movir X16 0")
    pr__lane_master_init_29.writeAction("movir X17 24")
    pr__lane_master_init_29.writeAction("mov_imm2reg X19 0")
    pr__lane_master_init_29.writeAction("addi X7 X22 64")
    pr__lane_master_init_29.writeAction("move X19 0(X22) 0 8")
    pr__lane_master_init_29.writeAction("addi X2 X28 0")
    pr__lane_master_init_29.writeAction("evlb X28 30")
    pr__lane_master_init_29.writeAction("addi X7 X29 80")
    pr__lane_master_init_29.writeAction("move X28 0(X29) 0 8")
    pr__lane_master_init_29.writeAction("addi X2 X20 0")
    pr__lane_master_init_29.writeAction("evlb X20 32")
    pr__lane_master_init_29.writeAction("evi X2 X21 255 4")
    pr__lane_master_init_29.writeAction("evlb X21 52")
    pr__lane_master_init_29.writeAction("yield")

    ## pr__lane_master_loop with ID 30
    pr__lane_master_loop_30 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 30)
    pr__lane_master_loop_30.writeAction("subi X16 X16 1")
    pr__lane_master_loop_30.writeAction("beqi X23 1 GenMSRPagerankEFA_xvlsl_lane_master_loop_continue")
    pr__lane_master_loop_30.writeAction("bge X23 X24 GenMSRPagerankEFA_xvlsl_lane_master_reach_end")
    pr__lane_master_loop_30.writeAction("addi X23 X28 32")
    pr__lane_master_loop_30.writeAction("sendr_wcont X20 X20 X28 X24")
    pr__lane_master_loop_30.writeAction("send_dmlm_ld X23 X21 4")
    pr__lane_master_loop_30.writeAction("addi X16 X16 1")
    pr__lane_master_loop_30.writeAction("movir X23 1")
    pr__lane_master_loop_30.writeAction("yield")
    pr__lane_master_loop_30.writeAction("GenMSRPagerankEFA_xvlsl_lane_master_reach_end: bgti X16 0 GenMSRPagerankEFA_xvlsl_lane_master_loop_continue")
    pr__lane_master_loop_30.writeAction("movlr 0(X22) X19 0 8")
    pr__lane_master_loop_30.writeAction("sendr_wret X31 29 X19 X19 X28")
    pr__lane_master_loop_30.writeAction("mov_imm2reg X19 0")
    pr__lane_master_loop_30.writeAction("movrl X19 0(X22) 0 8")
    pr__lane_master_loop_30.writeAction("GenMSRPagerankEFA_xvlsl_lane_master_loop_continue: yield")

    ## pr__lane_master_read_partition with ID 31
    pr__lane_master_read_partition_31 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 31)
    pr__lane_master_read_partition_31.writeAction("bge X8 X9 GenMSRPagerankEFA_xvlsl_lane_master_empty_partition")
    pr__lane_master_read_partition_31.writeAction("addi X8 X28 32")
    pr__lane_master_read_partition_31.writeAction("sendr_wcont X20 X20 X28 X9")
    pr__lane_master_read_partition_31.writeAction("send_dmlm_ld X8 X21 4")
    pr__lane_master_read_partition_31.writeAction("addi X16 X16 1")
    pr__lane_master_read_partition_31.writeAction("movir X23 1")
    pr__lane_master_read_partition_31.writeAction("yield")
    pr__lane_master_read_partition_31.writeAction("GenMSRPagerankEFA_xvlsl_lane_master_empty_partition: sendr_wret X31 29 X19 X19 X28")
    pr__lane_master_read_partition_31.writeAction("yield")

    ## pr__lane_master_get_next_return with ID 32
    pr__lane_master_get_next_return_32 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 32)
    pr__lane_master_get_next_return_32.writeAction("bge X16 X17 GenMSRPagerankEFA_xvlsl_lane_master_break_iterate_loop")
    pr__lane_master_get_next_return_32.writeAction("bge X8 X9 GenMSRPagerankEFA_xvlsl_lane_master_break_iterate_loop")
    pr__lane_master_get_next_return_32.writeAction("addi X8 X28 32")
    pr__lane_master_get_next_return_32.writeAction("sendr_wcont X20 X20 X28 X9")
    pr__lane_master_get_next_return_32.writeAction("send_dmlm_ld X8 X21 4")
    pr__lane_master_get_next_return_32.writeAction("addi X16 X16 1")
    pr__lane_master_get_next_return_32.writeAction("yield")
    pr__lane_master_get_next_return_32.writeAction("GenMSRPagerankEFA_xvlsl_lane_master_break_iterate_loop: movir X23 0")
    pr__lane_master_get_next_return_32.writeAction("addi X8 X23 0")
    pr__lane_master_get_next_return_32.writeAction("addi X9 X24 0")
    pr__lane_master_get_next_return_32.writeAction("yield")
    pr__lane_master_get_next_return_32.writeAction("GenMSRPagerankEFA_xvlsl_lane_master_iterator_pass_end: subi X16 X16 1")
    pr__lane_master_get_next_return_32.writeAction("addi X8 X23 0")
    pr__lane_master_get_next_return_32.writeAction("addi X9 X24 0")
    pr__lane_master_get_next_return_32.writeAction("bgti X16 0 GenMSRPagerankEFA_xvlsl_lane_master_loop_continue")
    pr__lane_master_get_next_return_32.writeAction("movlr 0(X22) X19 0 8")
    pr__lane_master_get_next_return_32.writeAction("sendr_wret X31 29 X19 X19 X28")
    pr__lane_master_get_next_return_32.writeAction("GenMSRPagerankEFA_xvlsl_lane_master_loop_continue: yield")

    ## pr__lane_master_terminate with ID 33
    pr__lane_master_terminate_33 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 33)
    pr__lane_master_terminate_33.writeAction("yield_terminate")

    ## pr__init_global_snyc with ID 34
    pr__init_global_snyc_34 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 34)
    pr__init_global_snyc_34.writeAction("sri X8 X16 11")
    pr__init_global_snyc_34.writeAction("movir X28 16384")
    pr__init_global_snyc_34.writeAction("bgt X16 X28 GenMSRPagerankEFA_xvlsl_max_child_max_node")
    pr__init_global_snyc_34.writeAction("andi X8 X28 2047")
    pr__init_global_snyc_34.writeAction("beqi X28 0 GenMSRPagerankEFA_xvlsl_max_node")
    pr__init_global_snyc_34.writeAction("addi X16 X16 1")
    pr__init_global_snyc_34.writeAction("jmp GenMSRPagerankEFA_xvlsl_max_node")
    pr__init_global_snyc_34.writeAction("GenMSRPagerankEFA_xvlsl_max_child_max_node: mov_imm2reg X16 16384")
    pr__init_global_snyc_34.writeAction("GenMSRPagerankEFA_xvlsl_max_node: addi X16 X16 0")
    pr__init_global_snyc_34.writeAction("sri X8 X17 6")
    pr__init_global_snyc_34.writeAction("movir X28 32")
    pr__init_global_snyc_34.writeAction("bgt X17 X28 GenMSRPagerankEFA_xvlsl_max_child_max_ud_per_nd")
    pr__init_global_snyc_34.writeAction("andi X8 X28 63")
    pr__init_global_snyc_34.writeAction("beqi X28 0 GenMSRPagerankEFA_xvlsl_max_ud_per_nd")
    pr__init_global_snyc_34.writeAction("addi X17 X17 1")
    pr__init_global_snyc_34.writeAction("jmp GenMSRPagerankEFA_xvlsl_max_ud_per_nd")
    pr__init_global_snyc_34.writeAction("GenMSRPagerankEFA_xvlsl_max_child_max_ud_per_nd: mov_imm2reg X17 32")
    pr__init_global_snyc_34.writeAction("GenMSRPagerankEFA_xvlsl_max_ud_per_nd: addi X17 X17 0")
    pr__init_global_snyc_34.writeAction("movir X18 64")
    pr__init_global_snyc_34.writeAction("bgt X8 X18 GenMSRPagerankEFA_xvlsl_max_ln_per_ud")
    pr__init_global_snyc_34.writeAction("addi X8 X18 0")
    pr__init_global_snyc_34.writeAction("GenMSRPagerankEFA_xvlsl_max_ln_per_ud: addi X18 X18 0")
    pr__init_global_snyc_34.writeAction("mov_reg2reg X1 X19")
    pr__init_global_snyc_34.writeAction("mov_reg2reg X9 X21")
    pr__init_global_snyc_34.writeAction("evi X2 X30 255 4")
    pr__init_global_snyc_34.writeAction("evlb X30 35")
    pr__init_global_snyc_34.writeAction("mov_imm2reg X29 0")
    pr__init_global_snyc_34.writeAction("GenMSRPagerankEFA_xvlsl_broadcast_loop: lshift X29 X28 11")
    pr__init_global_snyc_34.writeAction("add X0 X28 X28")
    pr__init_global_snyc_34.writeAction("ev X30 X30 X28 X28 8")
    pr__init_global_snyc_34.writeAction("sendr_wret X30 37 X17 X18  X28")
    pr__init_global_snyc_34.writeAction("addi X29 X29 1")
    pr__init_global_snyc_34.writeAction("blt X29 X16 GenMSRPagerankEFA_xvlsl_broadcast_loop")
    pr__init_global_snyc_34.writeAction("mov_imm2reg X20 0")
    pr__init_global_snyc_34.writeAction("mov_imm2reg X22 0")
    pr__init_global_snyc_34.writeAction("yield")

    ## pr__init_node_sync with ID 35
    pr__init_node_sync_35 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 35)
    pr__init_node_sync_35.writeAction("mov_reg2reg X8 X17")
    pr__init_node_sync_35.writeAction("evi X2 X30 255 4")
    pr__init_node_sync_35.writeAction("evlb X30 39")
    pr__init_node_sync_35.writeAction("mov_imm2reg X29 0")
    pr__init_node_sync_35.writeAction("GenMSRPagerankEFA_xvlsl_broadcast_loop: lshift X29 X28 6")
    pr__init_node_sync_35.writeAction("add X0 X28 X28")
    pr__init_node_sync_35.writeAction("ev X30 X30 X28 X28 8")
    pr__init_node_sync_35.writeAction("sendr_wret X30 38 X9 EQT  X28")
    pr__init_node_sync_35.writeAction("addi X29 X29 1")
    pr__init_node_sync_35.writeAction("blt X29 X17 GenMSRPagerankEFA_xvlsl_broadcast_loop")
    pr__init_node_sync_35.writeAction("mov_imm2reg X20 0")
    pr__init_node_sync_35.writeAction("mov_imm2reg X22 0")
    pr__init_node_sync_35.writeAction("mov_reg2reg X1 X19")
    pr__init_node_sync_35.writeAction("yield")

    ## pr__ud_accumulate with ID 36
    pr__ud_accumulate_36 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 36)
    pr__ud_accumulate_36.writeAction("movir UDPR_0 64")
    pr__ud_accumulate_36.writeAction("mov_imm2reg UDPR_2 0")
    pr__ud_accumulate_36.writeAction("mov_imm2reg X22 0")
    pr__ud_accumulate_36.writeAction("GenMSRPagerankEFA_xvlsl_accumulate_loop: lshift UDPR_2 UDPR_1 16")
    pr__ud_accumulate_36.writeAction("add X10 UDPR_1 UDPR_1")
    pr__ud_accumulate_36.writeAction("addi UDPR_1 UDPR_1 72")
    pr__ud_accumulate_36.writeAction("move 0(UDPR_1) X28 0 8")
    pr__ud_accumulate_36.writeAction("add X28 X22 X22")
    pr__ud_accumulate_36.writeAction("addi UDPR_2 UDPR_2 1")
    pr__ud_accumulate_36.writeAction("blt UDPR_2 UDPR_0 GenMSRPagerankEFA_xvlsl_accumulate_loop")
    pr__ud_accumulate_36.writeAction("sendr_reply X22 X22 X28")
    pr__ud_accumulate_36.writeAction("yield_terminate")

    ## pr__global_sync_return with ID 37
    pr__global_sync_return_37 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 37)
    pr__global_sync_return_37.writeAction("addi X20 X20 1")
    pr__global_sync_return_37.writeAction("add X8 X22 X22")
    pr__global_sync_return_37.writeAction("blt X20 X16 GenMSRPagerankEFA_xvlsl_continue")
    pr__global_sync_return_37.writeAction("bge X22 X21 GenMSRPagerankEFA_xvlsl_sync_finish")
    pr__global_sync_return_37.writeAction("mov_imm2reg X29 0")
    pr__global_sync_return_37.writeAction("GenMSRPagerankEFA_xvlsl_broadcast_loop: lshift X29 X28 11")
    pr__global_sync_return_37.writeAction("add X0 X28 X28")
    pr__global_sync_return_37.writeAction("ev X30 X30 X28 X28 8")
    pr__global_sync_return_37.writeAction("sendr_wret X30 37 X17 X18  X28")
    pr__global_sync_return_37.writeAction("addi X29 X29 1")
    pr__global_sync_return_37.writeAction("blt X29 X16 GenMSRPagerankEFA_xvlsl_broadcast_loop")
    pr__global_sync_return_37.writeAction("mov_imm2reg X20 0")
    pr__global_sync_return_37.writeAction("mov_imm2reg X22 0")
    pr__global_sync_return_37.writeAction("GenMSRPagerankEFA_xvlsl_continue: yield")
    pr__global_sync_return_37.writeAction("GenMSRPagerankEFA_xvlsl_sync_finish: movir X30 -1")
    pr__global_sync_return_37.writeAction("sri X30 X30 1")
    pr__global_sync_return_37.writeAction("sendr_wcont X19 X30 X22 X22")
    pr__global_sync_return_37.writeAction("yield_terminate")

    ## pr__node_sync_return with ID 38
    pr__node_sync_return_38 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 38)
    pr__node_sync_return_38.writeAction("addi X20 X20 1")
    pr__node_sync_return_38.writeAction("add X8 X22 X22")
    pr__node_sync_return_38.writeAction("blt X20 X17 GenMSRPagerankEFA_xvlsl_continue")
    pr__node_sync_return_38.writeAction("sendr_wcont X19 EQT X22 X22")
    pr__node_sync_return_38.writeAction("yield_terminate")
    pr__node_sync_return_38.writeAction("GenMSRPagerankEFA_xvlsl_continue: yield")

    ## pr__ud_entry with ID 39
    pr__ud_entry_39 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 39)
    pr__ud_entry_39.writeAction("mov_imm2reg UDPR_5 10")
    pr__ud_entry_39.writeAction("evi X2 UDPR_8 255 4")
    pr__ud_entry_39.writeAction("evlb UDPR_8 40")
    pr__ud_entry_39.writeAction("movir UDPR_2 6")
    pr__ud_entry_39.writeAction("sli UDPR_2 UDPR_2 27")
    pr__ud_entry_39.writeAction("or X0 UDPR_2 UDPR_2")
    pr__ud_entry_39.writeAction("ev UDPR_8 UDPR_8 UDPR_2 UDPR_2 8")
    pr__ud_entry_39.writeAction("sendr3_wcont UDPR_8 X1 UDPR_5 UDPR_8 X7")
    pr__ud_entry_39.writeAction("yieldt")

    ## pr__ud_delay with ID 40
    pr__ud_delay_40 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 40)
    pr__ud_delay_40.writeAction("beqi X8 0 GenMSRPagerankEFA_xvlsl_ud_loop_term")
    pr__ud_delay_40.writeAction("subi X8 UDPR_5 1")
    pr__ud_delay_40.writeAction("sendr3_wcont X9 X1 UDPR_5 X9 X10")
    pr__ud_delay_40.writeAction("yieldt")
    pr__ud_delay_40.writeAction("GenMSRPagerankEFA_xvlsl_ud_loop_term: movir UDPR_2 1")
    pr__ud_delay_40.writeAction("sli UDPR_2 UDPR_2 27")
    pr__ud_delay_40.writeAction("or X0 UDPR_2 UDPR_2")
    pr__ud_delay_40.writeAction("evi X2 UDPR_8 255 4")
    pr__ud_delay_40.writeAction("evlb UDPR_8 36")
    pr__ud_delay_40.writeAction("ev UDPR_8 UDPR_8 UDPR_2 UDPR_2 8")
    pr__ud_delay_40.writeAction("sendr3_wcont UDPR_8 X1 X8 X9 X10")
    pr__ud_delay_40.writeAction("yieldt")

    ## pr__kv_map_emit with ID 41
    pr__kv_map_emit_41 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 41)
    pr__kv_map_emit_41.writeAction("addi X7 X25 64")
    pr__kv_map_emit_41.writeAction("movlr 40(X25) X23 0 8")
    pr__kv_map_emit_41.writeAction("movlr 56(X25) X26 0 8")
    pr__kv_map_emit_41.writeAction("movir X24 0")
    pr__kv_map_emit_41.writeAction("hash X8 X24")
    pr__kv_map_emit_41.writeAction("and X24 X23 X24")
    pr__kv_map_emit_41.writeAction("add X24 X26 X24")
    pr__kv_map_emit_41.writeAction("evi X2 X30 255 4")
    pr__kv_map_emit_41.writeAction("evlb X30 44")
    pr__kv_map_emit_41.writeAction("evi X2 X27 255 4")
    pr__kv_map_emit_41.writeAction("evlb X27 47")
    pr__kv_map_emit_41.writeAction("ev X30  X30  X24 X24 8")
    pr__kv_map_emit_41.writeAction("sendops_wcont X30 X27 X8 2")
    pr__kv_map_emit_41.writeAction("move 0(X25) X29  0 8")
    pr__kv_map_emit_41.writeAction("addi X29 X29 1")
    pr__kv_map_emit_41.writeAction("move X29 0(X25) 0 8")
    pr__kv_map_emit_41.writeAction("yield_terminate")

    ## pr__kv_reduce_emit with ID 42
    pr__kv_reduce_emit_42 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 42)
    pr__kv_reduce_emit_42.writeAction("movir X16 128")
    pr__kv_reduce_emit_42.writeAction("add X16 X7 X16")
    pr__kv_reduce_emit_42.writeAction("movlr 256(X7) X28 0 8")
    pr__kv_reduce_emit_42.writeAction("lshift X8 X29 3")
    pr__kv_reduce_emit_42.writeAction("add X29 X28 X28")
    pr__kv_reduce_emit_42.writeAction("subi X16 X16 8")
    pr__kv_reduce_emit_42.writeAction("send_dmlm X28 X1 X16 1")
    pr__kv_reduce_emit_42.writeAction("yieldt")

    ## pr__kv_map_return with ID 43
    pr__kv_map_return_43 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 43)
    pr__kv_map_return_43.writeAction("addi X7 X16 80")
    pr__kv_map_return_43.writeAction("move 0(X16) X29 0 8")
    pr__kv_map_return_43.writeAction("sendops_wcont X29 X2 X8 2")
    pr__kv_map_return_43.writeAction("yieldt")

    ## pr__init_reduce_thread with ID 44
    pr__init_reduce_thread_44 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 44)
    pr__init_reduce_thread_44.writeAction("movir X21 4000")
    pr__init_reduce_thread_44.writeAction("mod X8 X21 X21")
    pr__init_reduce_thread_44.writeAction("sli X21 X16 4")
    pr__init_reduce_thread_44.writeAction("add X7 X16 X16")
    pr__init_reduce_thread_44.writeAction("addi X16 X16 328")
    pr__init_reduce_thread_44.writeAction("movlr 0(X16) X17 0 8")
    pr__init_reduce_thread_44.writeAction("beq X17 X8 GenMSRPagerankEFA_xvlsl_cache_hit")
    pr__init_reduce_thread_44.writeAction("movir X21 1")
    pr__init_reduce_thread_44.writeAction("sli X21 X21 63")
    pr__init_reduce_thread_44.writeAction("or X21 X8 X25")
    pr__init_reduce_thread_44.writeAction("beq X25 X17 GenMSRPagerankEFA_xvlsl_cache_hit")
    pr__init_reduce_thread_44.writeAction("rshift X17 X24 63")
    pr__init_reduce_thread_44.writeAction("beqi X24 1 GenMSRPagerankEFA_xvlsl_cache_evict")
    pr__init_reduce_thread_44.writeAction("beqi X17 -1 GenMSRPagerankEFA_xvlsl_cache_evict")
    pr__init_reduce_thread_44.writeAction("evi X2 X24 255 4")
    pr__init_reduce_thread_44.writeAction("sendops_wcont X24 X1 X8 2")
    pr__init_reduce_thread_44.writeAction("yieldt")
    pr__init_reduce_thread_44.writeAction("GenMSRPagerankEFA_xvlsl_cache_hit: move 8(X16) X22 0 8")
    pr__init_reduce_thread_44.writeAction("fadd.64 X9 X22 X22")
    pr__init_reduce_thread_44.writeAction("movrl X22 8(X16) 0 8")
    pr__init_reduce_thread_44.writeAction("sendr_wcont X1 X2 X8 X17 ")
    pr__init_reduce_thread_44.writeAction("addi X7 X18 64")
    pr__init_reduce_thread_44.writeAction("move 8(X18) X24 0 8")
    pr__init_reduce_thread_44.writeAction("addi X24 X24 1")
    pr__init_reduce_thread_44.writeAction("move X24 8(X18) 0 8")
    pr__init_reduce_thread_44.writeAction("yieldt")
    pr__init_reduce_thread_44.writeAction("GenMSRPagerankEFA_xvlsl_cache_evict: addi X7 X18 64")
    pr__init_reduce_thread_44.writeAction("move 24(X18) X24 0 8")
    pr__init_reduce_thread_44.writeAction("move 32(X18) X25 0 8")
    pr__init_reduce_thread_44.writeAction("bgt X25 X24 GenMSRPagerankEFA_xvlsl_thread_available")
    pr__init_reduce_thread_44.writeAction("evi X2 X24 255 4")
    pr__init_reduce_thread_44.writeAction("sendops_wcont X24 X1 X8 2")
    pr__init_reduce_thread_44.writeAction("yieldt")
    pr__init_reduce_thread_44.writeAction("GenMSRPagerankEFA_xvlsl_thread_available: addi X24 X24 1")
    pr__init_reduce_thread_44.writeAction("move X24  24(X18) 0 8")
    pr__init_reduce_thread_44.writeAction("movrl X8 0(X16) 1 8")
    pr__init_reduce_thread_44.writeAction("movir X19 0")
    pr__init_reduce_thread_44.writeAction("beqi X17 -1 GenMSRPagerankEFA_xvlsl_skip_flush")
    pr__init_reduce_thread_44.writeAction("sub X17 X21 X17")
    pr__init_reduce_thread_44.writeAction("addi X16 X22 0")
    pr__init_reduce_thread_44.writeAction("addi X7 X18 128")
    pr__init_reduce_thread_44.writeAction("addi X2 X21 0")
    pr__init_reduce_thread_44.writeAction("evlb X21 46")
    pr__init_reduce_thread_44.writeAction("movlr 256(X7) X24 0 8")
    pr__init_reduce_thread_44.writeAction("lshift X17 X25 3")
    pr__init_reduce_thread_44.writeAction("add X25 X24 X24")
    pr__init_reduce_thread_44.writeAction("send_dmlm X24 X21 X22 1")
    pr__init_reduce_thread_44.writeAction("addi X22 X22 8")
    pr__init_reduce_thread_44.writeAction("addi X19 X19 1")
    pr__init_reduce_thread_44.writeAction("GenMSRPagerankEFA_xvlsl_skip_flush: addi X2 X21 0")
    pr__init_reduce_thread_44.writeAction("evlb X21 45")
    pr__init_reduce_thread_44.writeAction("move 256(X7) X24 0 8")
    pr__init_reduce_thread_44.writeAction("lshift X8 X25 3")
    pr__init_reduce_thread_44.writeAction("add X25 X24 X24")
    pr__init_reduce_thread_44.writeAction("send_dmlm_ld X24 X21 1")
    pr__init_reduce_thread_44.writeAction("move X9 0(X16) 0 8")
    pr__init_reduce_thread_44.writeAction("addi X8 X17 0")
    pr__init_reduce_thread_44.writeAction("addi X1 X20 0")
    pr__init_reduce_thread_44.writeAction("addi X19 X19 1")
    pr__init_reduce_thread_44.writeAction("yield")

    ## pr__combine_get_pair with ID 45
    pr__combine_get_pair_45 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 45)
    pr__combine_get_pair_45.writeAction("move 0(X16) X22 0 8")
    pr__combine_get_pair_45.writeAction("fadd.64 X22 X8 X22")
    pr__combine_get_pair_45.writeAction("move X22 0(X16) 0 8")
    pr__combine_get_pair_45.writeAction("GenMSRPagerankEFA_xvlsl_get_fail: subi X19 X19 1")
    pr__combine_get_pair_45.writeAction("bnei X19 0 GenMSRPagerankEFA_xvlsl_contiue")
    pr__combine_get_pair_45.writeAction("movir X21 1")
    pr__combine_get_pair_45.writeAction("sli X21 X21 63")
    pr__combine_get_pair_45.writeAction("or X21 X17 X17")
    pr__combine_get_pair_45.writeAction("movrl X17 -8(X16) 0 8")
    pr__combine_get_pair_45.writeAction("sendr_wcont X20 X2 X2 X17 ")
    pr__combine_get_pair_45.writeAction("addi X7 X18 64")
    pr__combine_get_pair_45.writeAction("move 24(X18) X24  0 8")
    pr__combine_get_pair_45.writeAction("subi X24 X24 1")
    pr__combine_get_pair_45.writeAction("move X24  24(X18) 0 8")
    pr__combine_get_pair_45.writeAction("move 8(X18) X24 0 8")
    pr__combine_get_pair_45.writeAction("addi X24 X24 1")
    pr__combine_get_pair_45.writeAction("move X24 8(X18) 0 8")
    pr__combine_get_pair_45.writeAction("yieldt")
    pr__combine_get_pair_45.writeAction("GenMSRPagerankEFA_xvlsl_contiue: yield")

    ## pr__combine_put_pair_ack with ID 46
    pr__combine_put_pair_ack_46 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 46)
    pr__combine_put_pair_ack_46.writeAction("subi X19 X19 1")
    pr__combine_put_pair_ack_46.writeAction("bnei X19 0 GenMSRPagerankEFA_xvlsl_contiue")
    pr__combine_put_pair_ack_46.writeAction("movir X21 1")
    pr__combine_put_pair_ack_46.writeAction("sli X21 X21 63")
    pr__combine_put_pair_ack_46.writeAction("or X21 X17 X17")
    pr__combine_put_pair_ack_46.writeAction("movrl X17 -8(X16) 0 8")
    pr__combine_put_pair_ack_46.writeAction("sendr_wcont X20 X2 X2 X17 ")
    pr__combine_put_pair_ack_46.writeAction("addi X7 X18 64")
    pr__combine_put_pair_ack_46.writeAction("move 24(X18) X24  0 8")
    pr__combine_put_pair_ack_46.writeAction("subi X24 X24 1")
    pr__combine_put_pair_ack_46.writeAction("move X24  24(X18) 0 8")
    pr__combine_put_pair_ack_46.writeAction("move 8(X18) X24 0 8")
    pr__combine_put_pair_ack_46.writeAction("addi X24 X24 1")
    pr__combine_put_pair_ack_46.writeAction("move X24 8(X18) 0 8")
    pr__combine_put_pair_ack_46.writeAction("yieldt")
    pr__combine_put_pair_ack_46.writeAction("GenMSRPagerankEFA_xvlsl_contiue: yield")

    ## pr__kv_reduce_return with ID 47
    pr__kv_reduce_return_47 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 47)
    pr__kv_reduce_return_47.writeAction("yieldt")

    ## pr__combine_flush_lane with ID 48
    pr__combine_flush_lane_48 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 48)
    pr__combine_flush_lane_48.writeAction("addi X1 X17 0")
    pr__combine_flush_lane_48.writeAction("addi X7 X20 328")
    pr__combine_flush_lane_48.writeAction("movir X16 4000")
    pr__combine_flush_lane_48.writeAction("sli X16 X16 4")
    pr__combine_flush_lane_48.writeAction("add X16 X20 X16")
    pr__combine_flush_lane_48.writeAction("movir X19 0")
    pr__combine_flush_lane_48.writeAction("movir X22 -1")
    pr__combine_flush_lane_48.writeAction("addi X2 X23 0")
    pr__combine_flush_lane_48.writeAction("evlb X23 49")
    pr__combine_flush_lane_48.writeAction("addi X7 X18 128")
    pr__combine_flush_lane_48.writeAction("GenMSRPagerankEFA_xvlsl_flush_loop: bge X20 X16 GenMSRPagerankEFA_xvlsl_break_flush_loop")
    pr__combine_flush_lane_48.writeAction("movlr 0(X20) X21 0 8")
    pr__combine_flush_lane_48.writeAction("beq X21 X22 GenMSRPagerankEFA_xvlsl_continue_flush_loop")
    pr__combine_flush_lane_48.writeAction("sli X21 X21 1")
    pr__combine_flush_lane_48.writeAction("sri X21 X21 1")
    pr__combine_flush_lane_48.writeAction("addi X20 X20 8")
    pr__combine_flush_lane_48.writeAction("movlr 256(X7) X24 0 8")
    pr__combine_flush_lane_48.writeAction("lshift X21 X25 3")
    pr__combine_flush_lane_48.writeAction("add X25 X24 X24")
    pr__combine_flush_lane_48.writeAction("send_dmlm X24 X23 X20 1")
    pr__combine_flush_lane_48.writeAction("addi X20 X20 8")
    pr__combine_flush_lane_48.writeAction("addi X19 X19 1")
    pr__combine_flush_lane_48.writeAction("jmp GenMSRPagerankEFA_xvlsl_flush_loop")
    pr__combine_flush_lane_48.writeAction("GenMSRPagerankEFA_xvlsl_continue_flush_loop: addi X20 X20 16")
    pr__combine_flush_lane_48.writeAction("jmp GenMSRPagerankEFA_xvlsl_flush_loop")
    pr__combine_flush_lane_48.writeAction("GenMSRPagerankEFA_xvlsl_break_flush_loop: beqi X19 0 GenMSRPagerankEFA_xvlsl_empty_cache")
    pr__combine_flush_lane_48.writeAction("yield")
    pr__combine_flush_lane_48.writeAction("GenMSRPagerankEFA_xvlsl_empty_cache: movir X21 -1")
    pr__combine_flush_lane_48.writeAction("sri X21 X21 1")
    pr__combine_flush_lane_48.writeAction("sendr_wcont X17 X21 X2 X16 ")
    pr__combine_flush_lane_48.writeAction("yieldt")

    ## pr__combine_flush_ack with ID 49
    pr__combine_flush_ack_49 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 49)
    pr__combine_flush_ack_49.writeAction("subi X19 X19 1")
    pr__combine_flush_ack_49.writeAction("bnei X19 0 GenMSRPagerankEFA_xvlsl_continue_flush_loop")
    pr__combine_flush_ack_49.writeAction("movir X21 -1")
    pr__combine_flush_ack_49.writeAction("sri X21 X21 1")
    pr__combine_flush_ack_49.writeAction("sendr_wcont X17 X21 X2 X16 ")
    pr__combine_flush_ack_49.writeAction("yieldt")
    pr__combine_flush_ack_49.writeAction("GenMSRPagerankEFA_xvlsl_continue_flush_loop: yield")

    ## updown_init with ID 50
    updown_init_50 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 50)
    updown_init_50.writeAction("print '[DEBUG][NWID %d] Event <updown_init> ' X0 ")
    updown_init_50.writeAction("movir UDPR_2 128")
    updown_init_50.writeAction("add X7 UDPR_2 UDPR_2")
    updown_init_50.writeAction("movrl X8 0(UDPR_2) 0 8")
    updown_init_50.writeAction("movrl X9 8(UDPR_2) 0 8")
    updown_init_50.writeAction("movrl X10 16(UDPR_2) 0 8")
    updown_init_50.writeAction("addi X7 UDPR_1 192")
    updown_init_50.writeAction("movrl UDPR_1 24(UDPR_2) 0 8")
    updown_init_50.writeAction("movrl X11 0(UDPR_1) 1 8")
    updown_init_50.writeAction("movrl X12 0(UDPR_1) 1 8")
    updown_init_50.writeAction("movrl UDPR_1 32(UDPR_2) 0 8")
    updown_init_50.writeAction("movrl X13 0(UDPR_1) 1 8")
    updown_init_50.writeAction("movrl X14 0(UDPR_1) 1 8")
    updown_init_50.writeAction("evii UDPR_9 7 255 5")
    updown_init_50.writeAction("send_wret UDPR_9 51 UDPR_2 5 UDPR_0")
    updown_init_50.writeAction("movir UDPR_0 0")
    updown_init_50.writeAction("addi X7 UDPR_1 0")
    updown_init_50.writeAction("move UDPR_0 0(UDPR_1) 0 8")
    updown_init_50.writeAction("yield")

    ## updown_terminate with ID 51
    updown_terminate_51 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 51)
    updown_terminate_51.writeAction("movir UDPR_0 1")
    updown_terminate_51.writeAction("move UDPR_0 0(UDPR_1) 0 8")
    updown_terminate_51.writeAction("yield_terminate")

    ## pr__kv_map with ID 52
    pr__kv_map_52 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 52)
    pr__kv_map_52.writeAction("beqi X9 0 GenMSRPagerankEFA_xvlsl_empty")
    pr__kv_map_52.writeAction("addi X10 UDPR_0 0")
    pr__kv_map_52.writeAction("lshift X9 UDPR_1 3")
    pr__kv_map_52.writeAction("add UDPR_0 UDPR_1 UDPR_1")
    pr__kv_map_52.writeAction("movir UDPR_7 0")
    pr__kv_map_52.writeAction("movir UDPR_9 64")
    pr__kv_map_52.writeAction("GenMSRPagerankEFA_xvlsl_array_load: bge UDPR_0 UDPR_1 GenMSRPagerankEFA_xvlsl_array_load_fin")
    pr__kv_map_52.writeAction("send_dmlm_ld_wret UDPR_0 53 8 UDPR_14")
    pr__kv_map_52.writeAction("addi UDPR_0 UDPR_0 64")
    pr__kv_map_52.writeAction("addi UDPR_7 UDPR_7 8")
    pr__kv_map_52.writeAction("bge UDPR_7 UDPR_9 GenMSRPagerankEFA_xvlsl_array_load_fin")
    pr__kv_map_52.writeAction("jmp GenMSRPagerankEFA_xvlsl_array_load")
    pr__kv_map_52.writeAction("GenMSRPagerankEFA_xvlsl_array_load_fin: fcnvt.i64.64 X9 UDPR_4")
    pr__kv_map_52.writeAction("fdiv.64 X11 UDPR_4 UDPR_3")
    pr__kv_map_52.writeAction("addi X9 UDPR_4 0")
    pr__kv_map_52.writeAction("addi X7 UDPR_10 0")
    pr__kv_map_52.writeAction("movlr 104(UDPR_10) UDPR_8 0 8")
    pr__kv_map_52.writeAction("evi X2 UDPR_11 255 4")
    pr__kv_map_52.writeAction("evlb UDPR_11 44")
    pr__kv_map_52.writeAction("evi X2 UDPR_12 255 4")
    pr__kv_map_52.writeAction("evlb UDPR_12 47")
    pr__kv_map_52.writeAction("move 64(UDPR_10) UDPR_14  0 8")
    pr__kv_map_52.writeAction("add X9 UDPR_14 UDPR_14")
    pr__kv_map_52.writeAction("move UDPR_14 64(UDPR_10) 0 8")
    pr__kv_map_52.writeAction("movir UDPR_7 0")
    pr__kv_map_52.writeAction("yield")
    pr__kv_map_52.writeAction("GenMSRPagerankEFA_xvlsl_empty: addi X2 X30 0")
    pr__kv_map_52.writeAction("evlb X30 43")
    pr__kv_map_52.writeAction("sendr_wcont X30 X2 EQT EQT")
    pr__kv_map_52.writeAction("yield")

    ## pr__map_load_return with ID 53
    pr__map_load_return_53 = init_null_state_0.writeTransition("eventCarry", init_null_state_0, init_null_state_0, 53)
    pr__map_load_return_53.writeAction("bge UDPR_0 UDPR_1 GenMSRPagerankEFA_xvlsl_finish_fetch")
    pr__map_load_return_53.writeAction("send_dmlm_ld_wret UDPR_0 53 8 UDPR_14")
    pr__map_load_return_53.writeAction("addi UDPR_0 UDPR_0 64")
    pr__map_load_return_53.writeAction("GenMSRPagerankEFA_xvlsl_finish_fetch: addi X3 UDPR_9 0")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X8 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X8 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X9 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X9 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X10 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X10 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X11 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X11 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X12 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X12 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X13 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X13 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X14 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X14 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("bge UDPR_9 UDPR_1 GenMSRPagerankEFA_xvlsl_broadcast_continue")
    pr__map_load_return_53.writeAction("movir UDPR_5 8")
    pr__map_load_return_53.writeAction("hash X15 UDPR_5")
    pr__map_load_return_53.writeAction("and UDPR_5 UDPR_8 UDPR_5")
    pr__map_load_return_53.writeAction("ev UDPR_11  UDPR_11  UDPR_5 UDPR_5 8")
    pr__map_load_return_53.writeAction("sendr_wcont UDPR_11 UDPR_12 X15 UDPR_3")
    pr__map_load_return_53.writeAction("addi UDPR_9 UDPR_9 8")
    pr__map_load_return_53.writeAction("addi UDPR_7 UDPR_7 1")
    pr__map_load_return_53.writeAction("bge UDPR_7 UDPR_4 GenMSRPagerankEFA_xvlsl_finish_broadcast")
    pr__map_load_return_53.writeAction("GenMSRPagerankEFA_xvlsl_broadcast_continue: yield")
    pr__map_load_return_53.writeAction("GenMSRPagerankEFA_xvlsl_finish_broadcast: addi X2 X30 0")
    pr__map_load_return_53.writeAction("evlb X30 43")
    pr__map_load_return_53.writeAction("sendr_wcont X30 X2 UDPR_2 UDPR_6")
    pr__map_load_return_53.writeAction("yield")



def main():
    efa = EFA([])
    efa.code_level = 'machine'
    efaProgram_PagerankMsrEFA(efa)
    return efa