from linker.EFAProgram import efaProgram

## Global constants

@efaProgram
def EFA_pagerankPullDD(efa):
  efa.code_level = 'machine'
  state0 = efa.State("udweave_init") #Only one state code 
  efa.add_initId(state0.state_id)
  ## Static declarations
  ## Scoped Variable "nlist_ptr" uses Register X16, scope (0)
  ## Scoped Variable "vid" uses Register X17, scope (0)
  ## Scoped Variable "new_value" uses Register X18, scope (0)
  ## Scoped Variable "old_value" uses Register X19, scope (0)
  ## Scoped Variable "nlist_bound" uses Register X20, scope (0)
  ## Scoped Variable "num_pending" uses Register X21, scope (0)
  ## Scoped Variable "write_ack_evw" uses Register X22, scope (0)
  ## Param "vid_op" uses Register X8, scope (0->4)
  ## Param "deg_op" uses Register X9, scope (0->4)
  ## Param "neighbors_op" uses Register X10, scope (0->4)
  ## Param "value_op" uses Register X11, scope (0->4)
  ## Param "active_flag" uses Register X12, scope (0->4)
  ## Param "pad1" uses Register X13, scope (0->4)
  ## Param "pad2" uses Register X14, scope (0->4)
  ## Param "pad3" uses Register X15, scope (0->4)
  ## Param "vertex_addr" uses Register X3, scope (0->4)
  ## Scoped Variable "evw" uses Register X23, scope (0->4)
  ## Scoped Variable "max_fetch_size" uses Register X24, scope (0->4)
  ## Scoped Variable "tmp_lm_ptr" uses Register X25, scope (0->4)
  ## Scoped Variable "temp_value" uses Register X26, scope (0->4)
  ## Scoped Variable "evw" uses Register X23, scope (0->4->6)
  ## Scoped Variable "active" uses Register X24, scope (0->4->6)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->4->9)
  ## Scoped Variable "value_addr" uses Register X24, scope (0->4->9)
  ## Scoped Variable "active_flag_addr" uses Register X25, scope (0->4->9)
  ## Scoped Variable "temp_value" uses Register X26, scope (0->4->9)
  ## Param "e0" uses Register X8, scope (0->17)
  ## Param "e1" uses Register X9, scope (0->17)
  ## Param "e2" uses Register X10, scope (0->17)
  ## Param "e3" uses Register X11, scope (0->17)
  ## Param "e4" uses Register X12, scope (0->17)
  ## Param "e5" uses Register X13, scope (0->17)
  ## Param "e6" uses Register X14, scope (0->17)
  ## Param "e7" uses Register X15, scope (0->17)
  ## Param "curr_nlist_addr" uses Register X3, scope (0->17)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->17)
  ## Scoped Variable "input_graph" uses Register X24, scope (0->17)
  ## Scoped Variable "tmp_nlist_ptr" uses Register X25, scope (0->17)
  ## Scoped Variable "read_nbor_vertex_evw" uses Register X26, scope (0->17)
  ## Scoped Variable "tmp_vertex_addr" uses Register X27, scope (0->17)
  ## Param "vid_op" uses Register X8, scope (0->36)
  ## Param "deg_op" uses Register X9, scope (0->36)
  ## Param "neighbors_op" uses Register X10, scope (0->36)
  ## Param "value_op" uses Register X11, scope (0->36)
  ## Param "active_flag" uses Register X12, scope (0->36)
  ## Param "pad1" uses Register X13, scope (0->36)
  ## Param "pad2" uses Register X14, scope (0->36)
  ## Param "pad3" uses Register X15, scope (0->36)
  ## Param "vertex_addr" uses Register X3, scope (0->36)
  ## Scoped Variable "evw" uses Register X23, scope (0->36->40)
  ## Scoped Variable "tmp_lm_ptr" uses Register X24, scope (0->36->40)
  ## Scoped Variable "output_v_addr" uses Register X25, scope (0->36->40)
  ## Param "vid_op" uses Register X8, scope (0->42)
  ## Param "deg_op" uses Register X9, scope (0->42)
  ## Param "neighbors_op" uses Register X10, scope (0->42)
  ## Param "value_op" uses Register X11, scope (0->42)
  ## Param "active_flag" uses Register X12, scope (0->42)
  ## Param "pad1" uses Register X13, scope (0->42)
  ## Param "pad2" uses Register X14, scope (0->42)
  ## Param "pad3" uses Register X15, scope (0->42)
  ## Param "vertex_addr" uses Register X3, scope (0->42)
  ## Scoped Variable "active" uses Register X23, scope (0->42)
  ## Scoped Variable "max_fetch_size" uses Register X24, scope (0->42)
  ## Scoped Variable "evw" uses Register X25, scope (0->42)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->42->45)
  ## Scoped Variable "N" uses Register X24, scope (0->42->45)
  ## Scoped Variable "tmp_val" uses Register X25, scope (0->42->45)
  ## Scoped Variable "tmp_eps_ptr" uses Register X24, scope (0->42->50)
  ## Scoped Variable "eps" uses Register X25, scope (0->42->50)
  ## Scoped Variable "diff" uses Register X26, scope (0->42->50)
  ## Scoped Variable "value_addr" uses Register X27, scope (0->42->50)
  ## Scoped Variable "tmp_lm_ptr" uses Register X24, scope (0->42->62)
  ## Scoped Variable "flag_addr" uses Register X25, scope (0->42->62)
  ## Scoped Variable "val" uses Register X26, scope (0->42->62)
  ## Param "e0" uses Register X8, scope (0->74)
  ## Param "e1" uses Register X9, scope (0->74)
  ## Param "e2" uses Register X10, scope (0->74)
  ## Param "e3" uses Register X11, scope (0->74)
  ## Param "e4" uses Register X12, scope (0->74)
  ## Param "e5" uses Register X13, scope (0->74)
  ## Param "e6" uses Register X14, scope (0->74)
  ## Param "e7" uses Register X15, scope (0->74)
  ## Param "curr_nlist_addr" uses Register X3, scope (0->74)
  ## Scoped Variable "tmp_nlist_ptr" uses Register X23, scope (0->74)
  ## Scoped Variable "is_active" uses Register X24, scope (0->74)
  ## Scoped Variable "tmp_lm_ptr" uses Register X25, scope (0->74)
  ## Scoped Variable "output_graph" uses Register X26, scope (0->74)
  ## Scoped Variable "tmp_vertex_addr" uses Register X27, scope (0->74)
  ## Param "return_addr" uses Register X8, scope (0->100)
  ## Scoped Variable "evw" uses Register X23, scope (0->100)
  ## Scoped Variable "tmp_lm_ptr" uses Register X16, scope (0)
  ## Param "partition_array" uses Register X8, scope (0->105)
  ## Param "NUM_PARTITION_PER_LANE" uses Register X9, scope (0->105)
  ## Param "num_lanes" uses Register X10, scope (0->105)
  ## Param "input_vertices" uses Register X11, scope (0->105)
  ## Param "num_vertices" uses Register X12, scope (0->105)
  ## Param "output_vertices" uses Register X13, scope (0->105)
  ## Param "epsilon" uses Register X14, scope (0->105)
  ## Scoped Variable "send_buffer" uses Register X17, scope (0->105)
  ## Scoped Variable "tmp_eps_ptr" uses Register X18, scope (0->105)
  ## Scoped Variable "evw" uses Register X19, scope (0->105)
  ## Param "num_lanes" uses Register X8, scope (0->107)
  ## Param "value" uses Register X9, scope (0->107)
  ## #define EPSILON (0.000001)
  
  ####################################################
  ###### Writing code for thread PageRankPullDD ######
  ####################################################
  # Writing code for event PageRankPullDD::kv_map
  tranPageRankPullDD__kv_map = efa.writeEvent('PageRankPullDD::kv_map')
  ## The vertex has degree 0, skip it
  tranPageRankPullDD__kv_map.writeAction(f"entry: bnei X9 0 __if_kv_map_2_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_0_true: evi X2 X23 PageRankPullDD::kv_map_return 1") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X24 0") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_wcont X23 X2 X8 X24") 
  tranPageRankPullDD__kv_map.writeAction(f"yield") 
  ## The vertex is inactive, skip it
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_2_post: bnei X12 0 __if_kv_map_8_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_6_true: addi X7 X23 792") 
  tranPageRankPullDD__kv_map.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__kv_map.writeAction(f"sli X8 X25 6") 
  tranPageRankPullDD__kv_map.writeAction(f"add X24 X25 X26") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X26 X24 24") 
  tranPageRankPullDD__kv_map.writeAction(f"evi X2 X22 PageRankPullDD::write_value_ack 1") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_dmlm X24 X22 X11") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X3 X25 32") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X26 0") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_dmlm X25 X22 X26") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X21 2") 
  tranPageRankPullDD__kv_map.writeAction(f"yield") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_8_post: sli X9 X23 3") 
  tranPageRankPullDD__kv_map.writeAction(f"add X10 X23 X20") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X10 X16 0") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X8 X17 0") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X21 0") 
  tranPageRankPullDD__kv_map.writeAction(f"evi X2 X23 PageRankPullDD::rd_nlist_return 1") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X24 256") 
  tranPageRankPullDD__kv_map.writeAction(f"__while_kv_map_18_condition: ble X9 X21 __while_kv_map_20_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__while_kv_map_19_body: send_dmlm_ld X16 X23 8") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X21 X21 8") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__kv_map.writeAction(f"bgt X24 X21 __if_kv_map_23_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_21_true: jmp __while_kv_map_20_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_23_post: jmp __while_kv_map_18_condition") 
  tranPageRankPullDD__kv_map.writeAction(f"__while_kv_map_20_post: movir X18 0") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X11 X19 0") 
  ## Count active set volumn
  tranPageRankPullDD__kv_map.writeAction(f"addi X7 X25 640") 
  tranPageRankPullDD__kv_map.writeAction(f"movlr 0(X25) X26 0 8") 
  tranPageRankPullDD__kv_map.writeAction(f"add X26 X9 X26") 
  tranPageRankPullDD__kv_map.writeAction(f"movrl X26 0(X25) 0 8") 
  tranPageRankPullDD__kv_map.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::rd_nlist_return
  tranPageRankPullDD__rd_nlist_return = efa.writeEvent('PageRankPullDD::rd_nlist_return')
  tranPageRankPullDD__rd_nlist_return.writeAction(f"entry: ble X20 X16 __if_rd_nlist_return_2_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_0_true: send_dmlm_ld X16 X2 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X21 X21 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_2_post: addi X7 X23 784") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X3 X25 0") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"evi X2 X26 PageRankPullDD::read_nbor_vertex 1") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_5_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_3_true: subi X21 X21 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_5_post: sli X8 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_8_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_6_true: subi X21 X21 7") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_8_post: sli X9 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_11_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_9_true: subi X21 X21 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_11_post: sli X10 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_14_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_12_true: subi X21 X21 5") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_14_post: sli X11 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_17_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_15_true: subi X21 X21 4") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_17_post: sli X12 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_20_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_18_true: subi X21 X21 3") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_20_post: sli X13 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_23_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_21_true: subi X21 X21 2") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_23_post: sli X14 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_26_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_24_true: subi X21 X21 1") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_26_post: sli X15 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::read_nbor_vertex
  tranPageRankPullDD__read_nbor_vertex = efa.writeEvent('PageRankPullDD::read_nbor_vertex')
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"entry: fcnvt.i64.64 X9 X23")  # This is for casting. May be used later on
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"fdiv.64 X11 X23 X24") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"fadd.64 X18 X24 X18") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"subi X21 X21 1") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"bnei X21 0 __if_read_nbor_vertex_8_post") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"__if_read_nbor_vertex_6_true: evi X2 X23 PageRankPullDD::update_value 1") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"addi X7 X24 792") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"movlr 0(X24) X25 0 8") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"sli X17 X26 6") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"add X25 X26 X25") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"send_dmlm_ld X25 X23 8") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"__if_read_nbor_vertex_8_post: yield") 
  
  # Writing code for event PageRankPullDD::update_value
  tranPageRankPullDD__update_value = efa.writeEvent('PageRankPullDD::update_value')
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_3_true: addi X7 X23 776") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 0(X23) X25 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"fcnvt.i64.64 X25 X24")  # This is for casting. May be used later on
  tranPageRankPullDD__update_value.writeAction(f"movir X26 16323") 
  tranPageRankPullDD__update_value.writeAction(f"sli X26 X26 16") 
  tranPageRankPullDD__update_value.writeAction(f"ori X26 X26 13107") 
  tranPageRankPullDD__update_value.writeAction(f"sli X26 X26 16") 
  tranPageRankPullDD__update_value.writeAction(f"ori X26 X26 13107") 
  tranPageRankPullDD__update_value.writeAction(f"sli X26 X26 16") 
  tranPageRankPullDD__update_value.writeAction(f"ori X26 X26 13107") 
  tranPageRankPullDD__update_value.writeAction(f"fdiv.64 X26 X24 X25") 
  tranPageRankPullDD__update_value.writeAction(f"movir X26 16363") 
  tranPageRankPullDD__update_value.writeAction(f"sli X26 X26 16") 
  tranPageRankPullDD__update_value.writeAction(f"ori X26 X26 13107") 
  tranPageRankPullDD__update_value.writeAction(f"sli X26 X26 16") 
  tranPageRankPullDD__update_value.writeAction(f"ori X26 X26 13107") 
  tranPageRankPullDD__update_value.writeAction(f"sli X26 X26 16") 
  tranPageRankPullDD__update_value.writeAction(f"ori X26 X26 13107") 
  tranPageRankPullDD__update_value.writeAction(f"fmul.64 X26 X18 X26") 
  tranPageRankPullDD__update_value.writeAction(f"fadd.64 X26 X25 X18") 
  tranPageRankPullDD__update_value.writeAction(f"movir X23 0") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_15_true: addi X7 X24 800") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 0(X24) X25 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"fsub.64 X18 X19 X26") 
  tranPageRankPullDD__update_value.writeAction(f"bgei X26 0 __if_update_value_23_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_21_true: movir X27 -16400") 
  tranPageRankPullDD__update_value.writeAction(f"sli X27 X27 48") 
  tranPageRankPullDD__update_value.writeAction(f"fmul.64 X26 X27 X26") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_23_post: ble X25 X26 __if_update_value_28_false") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_27_true: movir X23 0") 
  tranPageRankPullDD__update_value.writeAction(f"jmp __if_update_value_29_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_28_false: movir X23 1") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_29_post: evi X2 X22 PageRankPullDD::write_value_ack 1") 
  tranPageRankPullDD__update_value.writeAction(f"addi X3 X27 24") 
  tranPageRankPullDD__update_value.writeAction(f"sendr_dmlm X27 X22 X18") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_39_true: addi X7 X24 784") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 0(X24) X25 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"sli X17 X26 6") 
  tranPageRankPullDD__update_value.writeAction(f"add X25 X26 X27") 
  tranPageRankPullDD__update_value.writeAction(f"addi X27 X25 32") 
  tranPageRankPullDD__update_value.writeAction(f"movir X26 0") 
  tranPageRankPullDD__update_value.writeAction(f"sendr_dmlm X25 X22 X26") 
  tranPageRankPullDD__update_value.writeAction(f"bneiu X23 0 __if_update_value_47_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_45_true: movir X21 2") 
  tranPageRankPullDD__update_value.writeAction(f"yield") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_47_post: movir X21 0") 
  tranPageRankPullDD__update_value.writeAction(f"movir X24 256") 
  tranPageRankPullDD__update_value.writeAction(f"evi X2 X25 PageRankPullDD::rd_nlist_return_update 1") 
  tranPageRankPullDD__update_value.writeAction(f"addi X10 X16 0") 
  tranPageRankPullDD__update_value.writeAction(f"sli X9 X26 3") 
  tranPageRankPullDD__update_value.writeAction(f"add X10 X26 X20") 
  tranPageRankPullDD__update_value.writeAction(f"__while_update_value_54_condition: ble X9 X21 __while_update_value_56_post") 
  tranPageRankPullDD__update_value.writeAction(f"__while_update_value_55_body: send_dmlm_ld X16 X25 8") 
  tranPageRankPullDD__update_value.writeAction(f"addi X21 X21 8") 
  tranPageRankPullDD__update_value.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__update_value.writeAction(f"bgt X24 X21 __if_update_value_59_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_57_true: jmp __while_update_value_56_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_59_post: jmp __while_update_value_54_condition") 
  tranPageRankPullDD__update_value.writeAction(f"__while_update_value_56_post: addi X9 X21 2") 
  tranPageRankPullDD__update_value.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::rd_nlist_return_update
  tranPageRankPullDD__rd_nlist_return_update = efa.writeEvent('PageRankPullDD::rd_nlist_return_update')
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"entry: ble X20 X16 __if_rd_nlist_return_update_5_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_3_true: send_dmlm_ld X16 X2 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_5_post: addi X3 X23 0") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"movir X24 1") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X7 X25 792") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"movlr 0(X25) X26 0 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sli X8 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_11_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_9_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_11_post: sli X9 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_17_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_15_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_17_post: sli X10 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_23_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_21_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_23_post: sli X11 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_29_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_27_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_29_post: sli X12 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_35_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_33_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_35_post: sli X13 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_41_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_39_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_41_post: sli X14 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_47_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_45_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_47_post: sli X15 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 32") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::write_value_ack
  tranPageRankPullDD__write_value_ack = efa.writeEvent('PageRankPullDD::write_value_ack')
  tranPageRankPullDD__write_value_ack.writeAction(f"entry: subi X21 X21 1") 
  tranPageRankPullDD__write_value_ack.writeAction(f"blei X21 0 __if_write_value_ack_5_post") 
  tranPageRankPullDD__write_value_ack.writeAction(f"__if_write_value_ack_3_true: yield") 
  tranPageRankPullDD__write_value_ack.writeAction(f"__if_write_value_ack_5_post: evi X2 X23 PageRankPullDD::kv_map_return 1") 
  tranPageRankPullDD__write_value_ack.writeAction(f"sendr_wcont X23 X2 X17 X21") 
  tranPageRankPullDD__write_value_ack.writeAction(f"yield") 
  
  
  ################################################
  ###### Writing code for thread InitUpDown ######
  ################################################
  # Writing code for event InitUpDown::init
  tranInitUpDown__init = efa.writeEvent('InitUpDown::init')
  tranInitUpDown__init.writeAction(f"entry: addi X7 X17 8") 
  tranInitUpDown__init.writeAction(f"movrl X8 0(X17) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X9 8(X17) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X10 16(X17) 0 8") 
  tranInitUpDown__init.writeAction(f"addi X7 X16 768") 
  tranInitUpDown__init.writeAction(f"movrl X11 0(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X12 8(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X11 16(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X13 24(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X16 24(X17) 0 8") 
  tranInitUpDown__init.writeAction(f"addi X7 X18 800") 
  tranInitUpDown__init.writeAction(f"movrl X14 0(X18) 0 8") 
  tranInitUpDown__init.writeAction(f"movir X19 0") 
  tranInitUpDown__init.writeAction(f"evlb X19 PageRankPullDD::map_shuffle_reduce") 
  tranInitUpDown__init.writeAction(f"evi X19 X19 255 4") 
  tranInitUpDown__init.writeAction(f"ev X19 X19 X0 X0 8") 
  tranInitUpDown__init.writeAction(f"send_wret X19 InitUpDown::terminate X17 4 X20") 
  tranInitUpDown__init.writeAction(f"addi X7 X16 0") 
  tranInitUpDown__init.writeAction(f"movir X21 0") 
  tranInitUpDown__init.writeAction(f"movrl X21 0(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"yield") 
  
  # Writing code for event InitUpDown::terminate
  tranInitUpDown__terminate = efa.writeEvent('InitUpDown::terminate')
  tranInitUpDown__terminate.writeAction(f"entry: print 'PageRank MSR returns current active set volumn = %lu.' X9") 
  tranInitUpDown__terminate.writeAction(f"movir X18 1") 
  tranInitUpDown__terminate.writeAction(f"movrl X18 0(X16) 0 8") 
  tranInitUpDown__terminate.writeAction(f"yield_terminate") 
  
