from linker.EFAProgram import efaProgram

## Global constants

@efaProgram
def EFA_three_clique_intersection_test(efa):
  efa.code_level = 'machine'
  state0 = efa.State("udweave_init") #Only one state code 
  efa.add_initId(state0.state_id)
  ## Static declarations
  ## Scoped Variable "abreturn_count" uses Register X16, scope (0)
  ## Scoped Variable "offs_a" uses Register X17, scope (0)
  ## Scoped Variable "offs_b" uses Register X18, scope (0)
  ## Scoped Variable "lmbuff" uses Register X19, scope (0)
  ## Param "lm_offset" uses Register X8, scope (0->1)
  ## Param "gv" uses Register X9, scope (0->1)
  ## Param "v1" uses Register X10, scope (0->1)
  ## Param "v2" uses Register X11, scope (0->1)
  ## Param "threshold" uses Register X12, scope (0->1)
  ## Scoped Variable "v_addr" uses Register X20, scope (0->1)
  ## Param "op0" uses Register X8, scope (0->2)
  ## Param "op1" uses Register X9, scope (0->2)
  ## Param "op2" uses Register X10, scope (0->2)
  ## Param "op3" uses Register X11, scope (0->2)
  ## Param "op4" uses Register X12, scope (0->2)
  ## Param "op5" uses Register X13, scope (0->2)
  ## Param "op6" uses Register X14, scope (0->2)
  ## Param "op7" uses Register X15, scope (0->2)
  ## Scoped Variable "int_addr" uses Register X20, scope (0->2->4)
  ## Scoped Variable "evword" uses Register X21, scope (0->2->4)
  ## Param "ptr_a" uses Register X8, scope (0->6)
  ## Param "ptr_b" uses Register X9, scope (0->6)
  ## Param "size_a" uses Register X10, scope (0->6)
  ## Param "size_b" uses Register X11, scope (0->6)
  ## Scoped Variable "fla" uses Register X20, scope (0->6)
  ## Scoped Variable "flb" uses Register X21, scope (0->6)
  ## Scoped Variable "local_ptra" uses Register X22, scope (0->6)
  ## Scoped Variable "local_ptrb" uses Register X23, scope (0->6)
  ## Scoped Variable "temp" uses Register X20, scope (0->6->8)
  ## Scoped Variable "cont" uses Register X21, scope (0->6->8)
  ## Scoped Variable "v1" uses Register X22, scope (0->6->8)
  ## Scoped Variable "v2" uses Register X23, scope (0->6->8)
  ## Scoped Variable "size_a_bytes" uses Register X24, scope (0->6->20)
  ## Scoped Variable "size_a_bytes_al" uses Register X25, scope (0->6->20)
  ## Scoped Variable "rem_a" uses Register X26, scope (0->6->20)
  ## Scoped Variable "size_b_bytes" uses Register X24, scope (0->6->55)
  ## Scoped Variable "size_b_bytes_al" uses Register X25, scope (0->6->55)
  ## Scoped Variable "rem_b" uses Register X26, scope (0->6->55)
  ## Param "op0" uses Register X8, scope (0->89)
  ## Param "op1" uses Register X9, scope (0->89)
  ## Param "op2" uses Register X10, scope (0->89)
  ## Param "op3" uses Register X11, scope (0->89)
  ## Param "op4" uses Register X12, scope (0->89)
  ## Param "op5" uses Register X13, scope (0->89)
  ## Param "op6" uses Register X14, scope (0->89)
  ## Param "op7" uses Register X15, scope (0->89)
  ## Scoped Variable "num_ops" uses Register X20, scope (0->89)
  ## Scoped Variable "a_addr" uses Register X21, scope (0->89)
  ## Scoped Variable "phase" uses Register X22, scope (0->89->91)
  ## Scoped Variable "evword" uses Register X23, scope (0->89->91->93)
  ## Scoped Variable "evword" uses Register X23, scope (0->89->91->94)
  ## Param "op0" uses Register X8, scope (0->95)
  ## Param "op1" uses Register X9, scope (0->95)
  ## Param "op2" uses Register X10, scope (0->95)
  ## Param "op3" uses Register X11, scope (0->95)
  ## Param "op4" uses Register X12, scope (0->95)
  ## Param "op5" uses Register X13, scope (0->95)
  ## Param "op6" uses Register X14, scope (0->95)
  ## Param "op7" uses Register X15, scope (0->95)
  ## Scoped Variable "num_ops" uses Register X20, scope (0->95)
  ## Scoped Variable "a_addr" uses Register X21, scope (0->95)
  ## Scoped Variable "phase" uses Register X22, scope (0->95->97)
  ## Scoped Variable "evword" uses Register X23, scope (0->95->97->99)
  ## Scoped Variable "evword" uses Register X23, scope (0->95->97->100)
  ## Param "op0" uses Register X8, scope (0->101)
  ## Param "op1" uses Register X9, scope (0->101)
  ## Param "op2" uses Register X10, scope (0->101)
  ## Param "op3" uses Register X11, scope (0->101)
  ## Param "op4" uses Register X12, scope (0->101)
  ## Param "op5" uses Register X13, scope (0->101)
  ## Param "op6" uses Register X14, scope (0->101)
  ## Param "op7" uses Register X15, scope (0->101)
  ## Scoped Variable "num_ops" uses Register X20, scope (0->101)
  ## Scoped Variable "b_addr" uses Register X21, scope (0->101)
  ## Scoped Variable "phase" uses Register X22, scope (0->101->103)
  ## Scoped Variable "evword" uses Register X23, scope (0->101->103->105)
  ## Scoped Variable "evword" uses Register X23, scope (0->101->103->106)
  ## Param "op0" uses Register X8, scope (0->107)
  ## Param "op1" uses Register X9, scope (0->107)
  ## Param "op2" uses Register X10, scope (0->107)
  ## Param "op3" uses Register X11, scope (0->107)
  ## Param "op4" uses Register X12, scope (0->107)
  ## Param "op5" uses Register X13, scope (0->107)
  ## Param "op6" uses Register X14, scope (0->107)
  ## Param "op7" uses Register X15, scope (0->107)
  ## Scoped Variable "num_ops" uses Register X20, scope (0->107)
  ## Scoped Variable "b_addr" uses Register X21, scope (0->107)
  ## Scoped Variable "phase" uses Register X22, scope (0->107->109)
  ## Scoped Variable "evword" uses Register X23, scope (0->107->109->111)
  ## Scoped Variable "evword" uses Register X23, scope (0->107->109->112)
  ## Scoped Variable "first_a" uses Register X20, scope (0->113)
  ## Scoped Variable "first_b" uses Register X21, scope (0->113)
  ## Scoped Variable "last_a" uses Register X22, scope (0->113)
  ## Scoped Variable "last_b" uses Register X23, scope (0->113)
  ## Scoped Variable "size_a" uses Register X24, scope (0->113)
  ## Scoped Variable "fl_ab" uses Register X25, scope (0->113)
  ## Scoped Variable "size_b" uses Register X26, scope (0->113)
  ## Scoped Variable "evword" uses Register X27, scope (0->113)
  ## Scoped Variable "alist" uses Register X20, scope (0->128)
  ## Scoped Variable "blist" uses Register X21, scope (0->128)
  ## Scoped Variable "loc_size_a" uses Register X22, scope (0->128)
  ## Scoped Variable "loc_size_b" uses Register X23, scope (0->128)
  ## Scoped Variable "iter_a" uses Register X24, scope (0->128)
  ## Scoped Variable "iter_b" uses Register X25, scope (0->128)
  ## Scoped Variable "loc_tc" uses Register X26, scope (0->128)
  ## Scoped Variable "rem" uses Register X27, scope (0->128)
  ## Scoped Variable "elem_a" uses Register X28, scope (0->128->136)
  ## Scoped Variable "elem_b" uses Register X29, scope (0->128->136)
  ## Scoped Variable "loc_size" uses Register X28, scope (0->128->149)
  ## Scoped Variable "loc_size" uses Register X28, scope (0->128->153)
  ## Scoped Variable "evword" uses Register X29, scope (0->128->153->155)
  ## Scoped Variable "tc" uses Register X30, scope (0->128->153->155)
  ## Scoped Variable "loc_size" uses Register X28, scope (0->128->157)
  ## Scoped Variable "local_ptr" uses Register X29, scope (0->128->157)
  ## Scoped Variable "loc_size" uses Register X28, scope (0->128->174)
  ## Scoped Variable "local_ptr" uses Register X29, scope (0->128->174)
  ## This is all metadata information
  ## #define DEBUG
  ###define PERFLOG
  ## #define DETAIL_PERF
  ## thread offsets (total space = 41*8 = 336 bytes)
  
  ######################################################################
  ###### Writing code for thread three_clique_intersect_constrain ######
  ######################################################################
  ## repurporse these 2
  # Writing code for event three_clique_intersect_constrain::init
  tranthree_clique_intersect_constrain__init = efa.writeEvent('three_clique_intersect_constrain::init')
  ## fetch v1 and v2
  tranthree_clique_intersect_constrain__init.writeAction(f"entry: add X7 X8 X19") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movir X21 0") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movrl X21 0(X19) 0 8") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movrl X1 8(X19) 0 8") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movir X21 0") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movrl X21 16(X19) 0 8") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movrl X10 328(X19) 0 8") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movrl X11 336(X19) 0 8") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movrl X12 344(X19) 0 8") 
  tranthree_clique_intersect_constrain__init.writeAction(f"muli X10 X16 24") 
  tranthree_clique_intersect_constrain__init.writeAction(f"add X9 X16 X20") 
  ## long* v_addr = gv + (v1 << 6);
  tranthree_clique_intersect_constrain__init.writeAction(f"send_dmlm_ld_wret X20 three_clique_intersect_constrain::vert_return 8 X21") 
  tranthree_clique_intersect_constrain__init.writeAction(f"muli X11 X16 24") 
  tranthree_clique_intersect_constrain__init.writeAction(f"add X9 X16 X20") 
  ## v_addr = gv + (v2 << 6);
  tranthree_clique_intersect_constrain__init.writeAction(f"send_dmlm_ld_wret X20 three_clique_intersect_constrain::vert_return 8 X21") 
  tranthree_clique_intersect_constrain__init.writeAction(f"movir X16 0") 
  tranthree_clique_intersect_constrain__init.writeAction(f"yield") 
  
  # Writing code for event three_clique_intersect_constrain::vert_return
  tranthree_clique_intersect_constrain__vert_return = efa.writeEvent('three_clique_intersect_constrain::vert_return')
  ##0 - deg, 2 - neighlistptr
  ## save nlist
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"entry: addi X16 X20 5") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"movwrl X10 X19(X20,0,0)") 
  ## save degree
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"addi X16 X20 7") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"movwrl X8 X19(X20,0,0)") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"addi X16 X16 1") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"bnei X16 2 __if_vert_return_1_false") 
  ## launch intersection
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"__if_vert_return_0_true: addi X19 X20 40") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"evi X2 X21 three_clique_intersect_constrain::intersect_lists 1") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"send_wcont X21 X21 X20 4") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"jmp __if_vert_return_2_post") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"__if_vert_return_1_false: yield") 
  tranthree_clique_intersect_constrain__vert_return.writeAction(f"__if_vert_return_2_post: yield") 
  
  ## size_a, size_b, ptr_a, ptr_b, lm_offset
  ## return -1 if not enough size was available  -- master should relaunch
  ## size per intersection - 8 words, ptr_a, ptr_b
  # Writing code for event three_clique_intersect_constrain::intersect_lists
  tranthree_clique_intersect_constrain__intersect_lists = efa.writeEvent('three_clique_intersect_constrain::intersect_lists')
  ##lmbuff = LMBASE + lm_offset;
  ##lmbuff[TC] = 0;
  ## save the main continuation so we don't lose it
  ##lmbuff[MAINCONT] = CCONT;
  ##lmbuff[PHASE] = 0;
  ##tc = 0;
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"entry: ceqi X10 X20 0") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"ceqi X11 X21 0") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"or X20 X21 X22") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"beqi X22 0 __if_intersect_lists_2_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_0_true: movir X20 0") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"movlr 8(X19) X21 0 8") 
  ##     unsigned long temp2 = lmbuff - LMBASE;
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"movlr 328(X19) X22 0 8") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"movlr 336(X19) X23 0 8") 
  ##     send_event(cont, temp2, temp, IGNRCONT);
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X7 X19 0") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"movir X25 1") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"movrl X25 0(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"yield_terminate") 
  ## unsigned long temp = ptr_a;
  ## lmbuff[PTRA] = temp;
  ## temp = ptr_b;
  ## lmbuff[PTRB] = temp;
  ## lmbuff[SIZEA] = size_a;
  ## lmbuff[SIZEB] = size_b;
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_2_post: movir X16 0") 
  ## fla = 2, > 2 blocks, 1 > 1 block, 0 only 1 block 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"movir X24 16") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"ble X10 X24 __if_intersect_lists_4_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_3_true: movir X20 2") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X16 X16 2") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_5_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_4_false: blei X10 8 __if_intersect_lists_7_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_6_true: movir X20 1") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X16 X16 2") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_5_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_7_false: movir X20 0") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X16 X16 1") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_5_post: movir X24 16") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"ble X11 X24 __if_intersect_lists_10_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_9_true: movir X21 2") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X16 X16 2") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_11_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_10_false: blei X11 8 __if_intersect_lists_13_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_12_true: movir X21 1") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X16 X16 2") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_11_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_13_false: movir X21 0") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X16 X16 1") 
  ## fetch first a
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_11_post: addi X8 X22 0") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"addi X9 X23 0") 
  ## fetch first and last of a
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"blei X20 0 __if_intersect_lists_16_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_15_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 8 X27") 
  ## get bytes
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sli X10 X24 3") 
  ## get 64B aligned offset
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sari X24 X25 6") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sli X25 X25 6") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sub X24 X25 X26") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sari X26 X26 3") 
  ## get addr of lastblock
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"add X8 X25 X22") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"blei X26 7 __if_intersect_lists_19_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_18_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 8 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_19_false: bnei X26 7 __if_intersect_lists_22_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_21_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 7 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_22_false: bnei X26 6 __if_intersect_lists_25_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_24_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 6 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_25_false: bnei X26 5 __if_intersect_lists_28_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_27_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 5 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_28_false: bnei X26 4 __if_intersect_lists_31_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_30_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 4 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_31_false: bnei X26 3 __if_intersect_lists_34_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_33_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 3 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_34_false: bnei X26 2 __if_intersect_lists_37_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_36_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 2 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_37_false: bnei X26 1 __if_intersect_lists_40_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_39_true: send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 1 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_20_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_40_false: subi X22 X22 64") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"send_dmlm_ld_wret X22 three_clique_intersect_constrain::lista_ret_2 8 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_20_post: jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_16_false: blei X10 7 __if_intersect_lists_43_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_42_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 8 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_43_false: bnei X10 7 __if_intersect_lists_46_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_45_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 7 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_46_false: bnei X10 6 __if_intersect_lists_49_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_48_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 6 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_49_false: bnei X10 5 __if_intersect_lists_52_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_51_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 5 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_52_false: bnei X10 4 __if_intersect_lists_55_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_54_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 4 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_55_false: bnei X10 3 __if_intersect_lists_58_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_57_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 3 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_58_false: bnei X10 2 __if_intersect_lists_61_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_60_true: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 2 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_17_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_61_false: send_dmlm_ld_wret X8 three_clique_intersect_constrain::lista_ret_1 1 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_17_post: blei X21 0 __if_intersect_lists_64_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_63_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 8 X27") 
  ## get bytes
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sli X11 X24 3") 
  ## get 64B aligned offset
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sari X24 X25 6") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sli X25 X25 6") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sub X24 X25 X26") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"sari X26 X26 3") 
  ## get addr of lastblock
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"add X9 X25 X23") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"blei X26 7 __if_intersect_lists_67_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_66_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 8 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_67_false: bnei X26 7 __if_intersect_lists_70_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_69_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 7 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_70_false: bnei X26 6 __if_intersect_lists_73_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_72_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 6 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_73_false: bnei X26 5 __if_intersect_lists_76_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_75_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 5 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_76_false: bnei X26 4 __if_intersect_lists_79_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_78_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 4 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_79_false: bnei X26 3 __if_intersect_lists_82_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_81_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 3 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_82_false: bnei X26 2 __if_intersect_lists_85_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_84_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 2 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_85_false: bnei X26 1 __if_intersect_lists_88_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_87_true: send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 1 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_68_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_88_false: subi X23 X23 64") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"send_dmlm_ld_wret X23 three_clique_intersect_constrain::listb_ret_2 8 X27") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_68_post: jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_64_false: blei X11 7 __if_intersect_lists_91_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_90_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 8 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_91_false: bnei X11 7 __if_intersect_lists_94_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_93_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 7 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_94_false: bnei X11 6 __if_intersect_lists_97_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_96_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 6 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_97_false: bnei X11 5 __if_intersect_lists_100_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_99_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 5 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_100_false: bnei X11 4 __if_intersect_lists_103_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_102_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 4 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_103_false: bnei X11 3 __if_intersect_lists_106_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_105_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 3 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_106_false: bnei X11 2 __if_intersect_lists_109_false") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_108_true: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 2 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"jmp __if_intersect_lists_65_post") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_109_false: send_dmlm_ld_wret X9 three_clique_intersect_constrain::listb_ret_1 1 X24") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"__if_intersect_lists_65_post: movrl X20 24(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"movrl X21 32(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_lists.writeAction(f"yield") 
  
  # Writing code for event three_clique_intersect_constrain::lista_ret_1
  tranthree_clique_intersect_constrain__lista_ret_1 = efa.writeEvent('three_clique_intersect_constrain::lista_ret_1')
  ## Update the return count
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"entry: sri X2 X21 20") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"andi X21 X22 7") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"addi X22 X20 1") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"subi X16 X16 1") 
  ## Get the num ops
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"addi X19 X21 72") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"bcpyol X8 X21 X20") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"bnei X16 0 __if_lista_ret_1_2_post") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"__if_lista_ret_1_0_true: movlr 16(X19) X22 0 8") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"bnei X22 0 __if_lista_ret_1_4_false") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"__if_lista_ret_1_3_true: evi X2 X23 three_clique_intersect_constrain::bounds_check 1") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"jmp __if_lista_ret_1_2_post") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"__if_lista_ret_1_4_false: evi X2 X23 three_clique_intersect_constrain::intersect_ab 1") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__lista_ret_1.writeAction(f"__if_lista_ret_1_2_post: yield") 
  
  # Writing code for event three_clique_intersect_constrain::lista_ret_2
  tranthree_clique_intersect_constrain__lista_ret_2 = efa.writeEvent('three_clique_intersect_constrain::lista_ret_2')
  ## Update the return count
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"entry: sri X2 X21 20") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"andi X21 X22 7") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"addi X22 X20 1") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"subi X16 X16 1") 
  ## Get the num ops
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"addi X19 X21 200") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"bcpyol X8 X21 X20") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"bnei X16 0 __if_lista_ret_2_2_post") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"__if_lista_ret_2_0_true: movlr 16(X19) X22 0 8") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"bnei X22 0 __if_lista_ret_2_4_false") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"__if_lista_ret_2_3_true: evi X2 X23 three_clique_intersect_constrain::bounds_check 1") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"jmp __if_lista_ret_2_2_post") 
  ## This will never happen but let's leave it in there
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"__if_lista_ret_2_4_false: evi X2 X23 three_clique_intersect_constrain::intersect_ab 1") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__lista_ret_2.writeAction(f"__if_lista_ret_2_2_post: yield") 
  
  # Writing code for event three_clique_intersect_constrain::listb_ret_1
  tranthree_clique_intersect_constrain__listb_ret_1 = efa.writeEvent('three_clique_intersect_constrain::listb_ret_1')
  ## Update the return count
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"entry: sri X2 X21 20") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"andi X21 X22 7") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"addi X22 X20 1") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"subi X16 X16 1") 
  ## Get the num ops
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"addi X19 X21 136") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"bcpyol X8 X21 X20") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"bnei X16 0 __if_listb_ret_1_2_post") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"__if_listb_ret_1_0_true: movlr 16(X19) X22 0 8") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"bnei X22 0 __if_listb_ret_1_4_false") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"__if_listb_ret_1_3_true: evi X2 X23 three_clique_intersect_constrain::bounds_check 1") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"jmp __if_listb_ret_1_2_post") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"__if_listb_ret_1_4_false: evi X2 X23 three_clique_intersect_constrain::intersect_ab 1") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__listb_ret_1.writeAction(f"__if_listb_ret_1_2_post: yield") 
  
  # Writing code for event three_clique_intersect_constrain::listb_ret_2
  tranthree_clique_intersect_constrain__listb_ret_2 = efa.writeEvent('three_clique_intersect_constrain::listb_ret_2')
  ## Update the return count
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"entry: sri X2 X21 20") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"andi X21 X22 7") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"addi X22 X20 1") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"subi X16 X16 1") 
  ## Get the num ops
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"addi X19 X21 264") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"bcpyol X8 X21 X20") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"bnei X16 0 __if_listb_ret_2_2_post") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"__if_listb_ret_2_0_true: movlr 16(X19) X22 0 8") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"bnei X22 0 __if_listb_ret_2_4_false") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"__if_listb_ret_2_3_true: evi X2 X23 three_clique_intersect_constrain::bounds_check 1") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"jmp __if_listb_ret_2_2_post") 
  ## this will never happen but let's leave it in there
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"__if_listb_ret_2_4_false: evi X2 X23 three_clique_intersect_constrain::intersect_ab 1") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"sendr_wcont X23 X23 X21 X21") 
  tranthree_clique_intersect_constrain__listb_ret_2.writeAction(f"__if_listb_ret_2_2_post: yield") 
  
  # Writing code for event three_clique_intersect_constrain::bounds_check
  tranthree_clique_intersect_constrain__bounds_check = efa.writeEvent('three_clique_intersect_constrain::bounds_check')
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"entry: movlr 72(X19) X20 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movlr 136(X19) X21 0 8") 
  ## last_a as a tmp reg to store threshold
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movlr 344(X19) X22 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movlr 56(X19) X24 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movlr 24(X19) X25 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"clt X20 X22 X26") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"xori X26 X26 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"clt X21 X22 X27") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"xori X27 X27 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"or X26 X27 X28") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"beqi X28 0 __if_bounds_check_2_post") 
  ## bounds check fail - return tc and terminate, v3 < v0
  ##     unsigned long temp2 = lmbuff - LMBASE;
  ##     send_event(size_a, temp2, last_a, IGNRCONT);
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_0_true: addi X7 X19 0") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movir X27 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movrl X27 0(X19) 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"yield_terminate") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_2_post: andi X24 X24 7") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"bnei X24 0 __if_bounds_check_5_post") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_3_true: movir X24 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_5_post: bnei X25 0 __if_bounds_check_7_false") 
  ## last is within the 8 block offset = (size * 8) - 8
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_6_true: addi X24 X26 9") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"subi X26 X27 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movwlr X19(X27,0,0) X22") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"jmp __if_bounds_check_8_post") 
  ## get the offset of the last block's last element 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_7_false: addi X24 X26 25") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"subi X26 X27 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movwlr X19(X27,0,0) X22") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_8_post: movlr 64(X19) X26 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"andi X26 X26 7") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"bnei X26 0 __if_bounds_check_11_post") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_9_true: movir X26 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_11_post: movlr 32(X19) X25 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"bnei X25 0 __if_bounds_check_13_false") 
  ## last is within the 8 block offset = (size * 8) - 8
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_12_true: addi X26 X27 17") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"subi X27 X28 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movwlr X19(X28,0,0) X23") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"jmp __if_bounds_check_14_post") 
  ## get the offset of the last block's last element 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_13_false: addi X26 X27 33") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"subi X27 X28 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movwlr X19(X28,0,0) X23") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_14_post: clt X22 X21 X27") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"clt X23 X20 X28") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"or X27 X28 X29") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"beqi X29 0 __if_bounds_check_17_post") 
  ## bounds check fail - return tc and terminate
  ##     unsigned long temp2 = lmbuff - LMBASE;
  ##     send_event(size_a, temp2, last_a, IGNRCONT);
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_15_true: addi X7 X19 0") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movir X28 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movrl X28 0(X19) 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"yield_terminate") 
  ## bounds check passed now intersect CURRA and CURRB!
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"__if_bounds_check_17_post: movir X28 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movrl X28 16(X19) 0 8") 
  ## now these are iterators change names
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movir X28 0") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movrl X28 24(X19) 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movir X28 0") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movrl X28 32(X19) 0 8") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movir X17 0") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"movir X18 0") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"evi X2 X27 three_clique_intersect_constrain::intersect_ab 1") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"sendr_wcont X27 X27 X25 X25") 
  tranthree_clique_intersect_constrain__bounds_check.writeAction(f"yield") 
  
  # Writing code for event three_clique_intersect_constrain::intersect_ab
  tranthree_clique_intersect_constrain__intersect_ab = efa.writeEvent('three_clique_intersect_constrain::intersect_ab')
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"entry: addi X19 X20 72") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X19 X21 136") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 56(X19) X22 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 64(X19) X23 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 24(X19) X24 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 32(X19) X25 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movir X26 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"sub X22 X24 X27") 
  ## if rem < 8 then that's all that's remaining
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"blei X27 8 __if_intersect_ab_1_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_0_true: movir X22 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_2_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_1_false: addi X27 X22 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_2_post: sub X23 X25 X27") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"blei X27 8 __if_intersect_ab_4_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_3_true: movir X23 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_5_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_4_false: addi X27 X23 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_5_post: movir X26 0") 
  ## tmp reg iter_a = threshold, iter_b = end (0)
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 344(X19) X24 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movir X25 0") 
  ## else walk through the two lists simultaeously
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__while_intersect_ab_6_condition: clt X17 X22 X28") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"clt X18 X23 X29") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"and X28 X29 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"beqi X30 0 __while_intersect_ab_8_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__while_intersect_ab_7_body: movwlr X20(X17,0,0) X28") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movwlr X21(X18,0,0) X29") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"bgt X24 X28 __if_intersect_ab_10_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_9_true: movir X25 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X22 X17 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_11_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_10_false: bgt X24 X29 __if_intersect_ab_13_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_12_true: movir X25 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X22 X17 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_11_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_13_false: ble X29 X28 __if_intersect_ab_16_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_15_true: addi X17 X17 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_11_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_16_false: ble X28 X29 __if_intersect_ab_19_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_18_true: addi X18 X18 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_11_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_19_false: addi X26 X26 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X17 X17 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X18 X18 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_11_post: jmp __while_intersect_ab_6_condition") 
  ## update the loc tc
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__while_intersect_ab_8_post: movlr 0(X19) X29 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"add X29 X26 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movrl X30 0(X19) 0 8") 
  ## if intersect result > v0, end
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"bnei X25 1 __if_intersect_ab_23_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_21_true: addi X7 X19 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movir X29 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movrl X29 0(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"yield_terminate") 
  ## one or both the lists exited --> whichever did fetch that
  ## update iter by how much ever was processed 
  ## check for bounds and fetch
  ## retain offs of the other one 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_23_post: bne X17 X22 __if_intersect_ab_26_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_24_true: movlr 24(X19) X24 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 56(X19) X28 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"add X24 X22 X24") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"bgt X28 X24 __if_intersect_ab_26_post") 
  ## //tc = tc + loc_tc;
  ## loc_size = lmbuff - LMBASE;
  ## send_event(evword, loc_size, tc, IGNRCONT);
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_27_true: addi X7 X19 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movir X24 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movrl X24 0(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"yield_terminate") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_26_post: bne X18 X23 __if_intersect_ab_32_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_30_true: movlr 32(X19) X25 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 64(X19) X28 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"add X25 X23 X25") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"bgt X28 X25 __if_intersect_ab_32_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_33_true: movlr 8(X19) X29 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 0(X19) X30 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 328(X19) X24 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 336(X19) X25 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"print '[DEBUG][NWID %lu] <intersect> TC (%lu, %lu):%lu' X0 X24 X25 X30") 
  ## //tc = tc + loc_tc;
  ## loc_size = lmbuff - LMBASE;
  ## send_event(evword, loc_size, tc, IGNRCONT);
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X7 X19 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movir X24 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movrl X24 0(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"yield_terminate") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_32_post: bne X17 X22 __if_intersect_ab_38_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_36_true: movlr 56(X19) X28 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"sub X28 X24 X27") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 40(X19) X29 0 8") 
  ## calculate 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"sli X24 X30 3") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"add X29 X30 X29") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"blei X27 7 __if_intersect_ab_40_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_39_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 8 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_41_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_40_false: bnei X27 7 __if_intersect_ab_43_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_42_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 7 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_41_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_43_false: bnei X27 6 __if_intersect_ab_46_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_45_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 6 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_41_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_46_false: bnei X27 5 __if_intersect_ab_49_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_48_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 5 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_41_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_49_false: bnei X27 4 __if_intersect_ab_52_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_51_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 4 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_41_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_52_false: bnei X27 3 __if_intersect_ab_55_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_54_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 3 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_41_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_55_false: bnei X27 2 __if_intersect_ab_58_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_57_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 2 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_41_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_58_false: send_dmlm_ld_wret X29 three_clique_intersect_constrain::lista_ret_1 1 X30") 
  ## update
  ##loc_size = lmbuff[TC];
  ##lmbuff[TC] = loc_size + loc_tc;
  ###ifdef DEBUG        
  ##        print("[DEBUG][NWID %lu] <intersect> tc before update:%lu loc:%lu", NETID, loc_size, loc_tc);
  ###endif
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_41_post: movrl X24 24(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movir X17 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X16 X16 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_38_post: bne X18 X23 __if_intersect_ab_62_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_60_true: movlr 64(X19) X28 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"sub X28 X25 X27") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movlr 48(X19) X29 0 8") 
  ## calculate 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"sli X25 X30 3") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"add X29 X30 X29") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"blei X27 7 __if_intersect_ab_64_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_63_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 8 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_65_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_64_false: bnei X27 7 __if_intersect_ab_67_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_66_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 7 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_65_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_67_false: bnei X27 6 __if_intersect_ab_70_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_69_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 6 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_65_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_70_false: bnei X27 5 __if_intersect_ab_73_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_72_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 5 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_65_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_73_false: bnei X27 4 __if_intersect_ab_76_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_75_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 4 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_65_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_76_false: bnei X27 3 __if_intersect_ab_79_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_78_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 3 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_65_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_79_false: bnei X27 2 __if_intersect_ab_82_false") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_81_true: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 2 X30") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"jmp __if_intersect_ab_65_post") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_82_false: send_dmlm_ld_wret X29 three_clique_intersect_constrain::listb_ret_1 1 X30") 
  ## update
  ##loc_size = lmbuff[TC];
  ##lmbuff[TC] = loc_size + loc_tc;
  ###ifdef DEBUG        
  ##        print("[DEBUG][NWID %lu] <intersect> tc before update:%lu loc:%lu", NETID, loc_size, loc_tc);
  ###endif
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_65_post: movrl X25 32(X19) 0 8") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"movir X18 0") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"addi X16 X16 1") 
  tranthree_clique_intersect_constrain__intersect_ab.writeAction(f"__if_intersect_ab_62_post: yield") 
  

