from linker.EFAProgram import efaProgram

## UDWeave version: 0fe75f3 (2026-04-17)

## Global constants

@efaProgram
def EFA_main_master(efa):
  efa.code_level = 'machine'
  state0 = efa.State("udweave_init") #Only one state code 
  efa.add_initId(state0.state_id)
  ## Static declarations
  ## Scoped Variable "num_map_done" uses Register X16, scope (0)
  ## Scoped Variable "iteration" uses Register X17, scope (0)
  ## Scoped Variable "num_lanes" uses Register X18, scope (0)
  ## Scoped Variable "num_map" uses Register X19, scope (0)
  ## Scoped Variable "return_value" uses Register X20, scope (0)
  ## Scoped Variable "return_value2" uses Register X21, scope (0)
  ## Scoped Variable "num_lanes_per_control" uses Register X22, scope (0)
  ## Scoped Variable "control_level" uses Register X23, scope (0)
  ## #define DEBUG
  ## This is all metadata information
  ## Total threads used in BFS
  ## #define NUM_THREADS 245
  ## #define NUM_LANES_PER_MASTER 2048
  ## Each threads in the same lane shared the following scratchpad
  ## send buffer 1 - 17 (16 words)
  ## #define DEBUG
  
  #################################################
  ###### Writing code for thread main_master ######
  #################################################
  # Writing code for event main_master::init
  tranmain_master__init = efa.writeEvent('main_master::init')
  tranmain_master__init.writeAction(f"__entry: addi X7 X24 0") 
  tranmain_master__init.writeAction(f"bneiu X15 0 __if_init_2_post") 
  tranmain_master__init.writeAction(f"__if_init_0_true: print 'BFS Start'") 
  tranmain_master__init.writeAction(f"movir X25 0") 
  tranmain_master__init.writeAction(f"movrl X25 0(X24) 0 8") 
  tranmain_master__init.writeAction(f"__if_init_2_post: addi X8 X18 0") 
  tranmain_master__init.writeAction(f"movir X25 1") 
  tranmain_master__init.writeAction(f"sl X25 X14 X25") 
  tranmain_master__init.writeAction(f"subi X8 X22 1") 
  tranmain_master__init.writeAction(f"sr X22 X14 X26") 
  tranmain_master__init.writeAction(f"addi X26 X22 1") 
  tranmain_master__init.writeAction(f"sladdii X11 X26 1 2") 
  tranmain_master__init.writeAction(f"mul X26 X22 X26") 
  tranmain_master__init.writeAction(f"sli X26 X26 3") 
  tranmain_master__init.writeAction(f"bneiu X22 1 __if_init_4_false") 
  tranmain_master__init.writeAction(f"__if_init_3_true: addi X8 X19 0") 
  ## start init 

  tranmain_master__init.writeAction(f"addi X7 X24 8") 
  tranmain_master__init.writeAction(f"movrl X9 0(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X12 24(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X13 32(X24) 0 8") 
  tranmain_master__init.writeAction(f"addi X10 X27 0") 
  tranmain_master__init.writeAction(f"addi X0 X28 0") 
  tranmain_master__init.writeAction(f"add X28 X8 X29") 
  tranmain_master__init.writeAction(f"__while_init_6_condition: ble X29 X28 __while_init_8_post") 
  tranmain_master__init.writeAction(f"__while_init_7_body: movrl X27 8(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X11 16(X24) 0 8") 
  tranmain_master__init.writeAction(f"movir X30 0") 
  tranmain_master__init.writeAction(f"evlb X30 map_master__init") 
  tranmain_master__init.writeAction(f"evi X30 X30 255 4") 
  tranmain_master__init.writeAction(f"ev X30 X30 X28 X28 8") 
  tranmain_master__init.writeAction(f"send_wret X30 main_master::init_done X24 5 X31") 
  tranmain_master__init.writeAction(f"add X27 X26 X27") 
  tranmain_master__init.writeAction(f"addi X28 X28 1") 
  tranmain_master__init.writeAction(f"jmp __while_init_6_condition") 
  tranmain_master__init.writeAction(f"__while_init_8_post: jmp __if_init_5_post") 
  tranmain_master__init.writeAction(f"__if_init_4_false: addi X7 X24 8") 
  tranmain_master__init.writeAction(f"movrl X22 0(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X9 8(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X11 24(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X12 32(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X13 40(X24) 0 8") 
  tranmain_master__init.writeAction(f"movrl X14 48(X24) 0 8") 
  tranmain_master__init.writeAction(f"addi X15 X27 1") 
  tranmain_master__init.writeAction(f"movrl X27 56(X24) 0 8") 
  tranmain_master__init.writeAction(f"addi X10 X27 0") 
  tranmain_master__init.writeAction(f"addi X0 X29 0") 
  tranmain_master__init.writeAction(f"addi X25 X19 0") 
  tranmain_master__init.writeAction(f"mul X22 X25 X28") 
  tranmain_master__init.writeAction(f"add X28 X29 X28") 
  tranmain_master__init.writeAction(f"__while_init_9_condition: ble X28 X29 __if_init_5_post") 
  tranmain_master__init.writeAction(f"__while_init_10_body: movrl X27 16(X24) 0 8") 
  tranmain_master__init.writeAction(f"movir X30 0") 
  tranmain_master__init.writeAction(f"evlb X30 main_master::init") 
  tranmain_master__init.writeAction(f"evi X30 X30 255 4") 
  tranmain_master__init.writeAction(f"ev X30 X30 X29 X29 8") 
  tranmain_master__init.writeAction(f"send_wret X30 main_master::init_done X24 8 X31") 
  tranmain_master__init.writeAction(f"add X29 X22 X29") 
  tranmain_master__init.writeAction(f"add X27 X26 X27") 
  tranmain_master__init.writeAction(f"jmp __while_init_9_condition") 
  tranmain_master__init.writeAction(f"__if_init_5_post: movir X16 0") 
  tranmain_master__init.writeAction(f"addi X12 X17 0") 
  tranmain_master__init.writeAction(f"movir X20 0") 
  tranmain_master__init.writeAction(f"movir X21 0") 
  tranmain_master__init.writeAction(f"addi X7 X24 0") 
  tranmain_master__init.writeAction(f"addi X15 X23 0") 
  tranmain_master__init.writeAction(f"sli X23 X25 1") 
  tranmain_master__init.writeAction(f"addi X25 X25 43") 
  tranmain_master__init.writeAction(f"sri X2 X26 24") 
  tranmain_master__init.writeAction(f"andi X26 X26 255") 
  tranmain_master__init.writeAction(f"movwrl X26 X24(X25,0,0)") 
  tranmain_master__init.writeAction(f"addi X25 X25 1") 
  tranmain_master__init.writeAction(f"movwrl X1 X24(X25,0,0)") 
  tranmain_master__init.writeAction(f"bneiu X15 0 __if_init_14_post") 
  tranmain_master__init.writeAction(f"__if_init_12_true: addi X24 X24 280") 
  tranmain_master__init.writeAction(f"bcpyoli X8 X24 8") 
  tranmain_master__init.writeAction(f"__if_init_14_post: yield") 
  
  # Writing code for event main_master::init_done
  tranmain_master__init_done = efa.writeEvent('main_master::init_done')
  tranmain_master__init_done.writeAction(f"__entry: addi X16 X16 1") 
  tranmain_master__init_done.writeAction(f"bneu X16 X19 __if_init_done_2_post") 
  tranmain_master__init_done.writeAction(f"__if_init_done_0_true: movir X16 0") 
  tranmain_master__init_done.writeAction(f"bneiu X23 0 __if_init_done_4_false") 
  tranmain_master__init_done.writeAction(f"__if_init_done_3_true: evi X2 X24 main_master::start 1") 
  tranmain_master__init_done.writeAction(f"sendr_wret X24 main_master::map_launcher_done X23 X23 X25") 
  ## print("[DEBUG][NWID %lu] <init_done_main> finsh", NETID);

  tranmain_master__init_done.writeAction(f"jmp __if_init_done_2_post") 
  tranmain_master__init_done.writeAction(f"__if_init_done_4_false: addi X7 X24 0") 
  tranmain_master__init_done.writeAction(f"sli X23 X25 1") 
  tranmain_master__init_done.writeAction(f"addi X25 X25 43") 
  tranmain_master__init_done.writeAction(f"addi X25 X25 1") 
  tranmain_master__init_done.writeAction(f"movwlr X24(X25,0,0) X24") 
  tranmain_master__init_done.writeAction(f"movir X25 -1") 
  tranmain_master__init_done.writeAction(f"sri X25 X25 1") 
  tranmain_master__init_done.writeAction(f"sendr_wcont X24 X25 X0 X0") 
  tranmain_master__init_done.writeAction(f"__if_init_done_2_post: yield") 
  
  # Writing code for event main_master::send_to_global_master_thread
  tranmain_master__send_to_global_master_thread = efa.writeEvent('main_master::send_to_global_master_thread')
  tranmain_master__send_to_global_master_thread.writeAction(f"__entry: addi X7 X24 0") 
  tranmain_master__send_to_global_master_thread.writeAction(f"sli X10 X25 1") 
  tranmain_master__send_to_global_master_thread.writeAction(f"addi X25 X25 43") 
  tranmain_master__send_to_global_master_thread.writeAction(f"movwlr X24(X25,0,0) X26") 
  tranmain_master__send_to_global_master_thread.writeAction(f"addi X25 X25 1") 
  tranmain_master__send_to_global_master_thread.writeAction(f"movwrl X1 X24(X25,0,0)") 
  tranmain_master__send_to_global_master_thread.writeAction(f"ev X8 X26 X26 X26 4") 
  tranmain_master__send_to_global_master_thread.writeAction(f"sendr_wcont X26 X1 X9 X9") 
  tranmain_master__send_to_global_master_thread.writeAction(f"yield_terminate") 
  
  # Writing code for event main_master::start
  tranmain_master__start = efa.writeEvent('main_master::start')
  tranmain_master__start.writeAction(f"__entry: movir X20 0") 
  tranmain_master__start.writeAction(f"bneiu X22 1 __if_start_1_false") 
  tranmain_master__start.writeAction(f"__if_start_0_true: evi X2 X26 map_master__start 1") 
  tranmain_master__start.writeAction(f"movir X16 0") 
  tranmain_master__start.writeAction(f"addi X0 X24 0") 
  tranmain_master__start.writeAction(f"add X24 X19 X25") 
  tranmain_master__start.writeAction(f"__while_start_3_condition: ble X25 X24 __while_start_5_post") 
  tranmain_master__start.writeAction(f"__while_start_4_body: ev X26 X29 X24 X24 8") 
  tranmain_master__start.writeAction(f"movir X27 0") 
  tranmain_master__start.writeAction(f"evlb X27 map_master__send_to_map_master_thread") 
  tranmain_master__start.writeAction(f"evi X27 X27 255 4") 
  tranmain_master__start.writeAction(f"ev X27 X27 X24 X24 8") 
  tranmain_master__start.writeAction(f"sendr_wret X27 main_master::map_launcher_done X29 X8 X28") 
  tranmain_master__start.writeAction(f"addi X24 X24 1") 
  tranmain_master__start.writeAction(f"jmp __while_start_3_condition") 
  tranmain_master__start.writeAction(f"__while_start_5_post: jmp __if_start_2_post") 
  tranmain_master__start.writeAction(f"__if_start_1_false: evi X2 X24 main_master::start 1") 
  tranmain_master__start.writeAction(f"addi X0 X26 0") 
  tranmain_master__start.writeAction(f"mul X19 X22 X25") 
  tranmain_master__start.writeAction(f"add X26 X25 X25") 
  tranmain_master__start.writeAction(f"__while_start_6_condition: ble X25 X26 __if_start_2_post") 
  tranmain_master__start.writeAction(f"__while_start_7_body: ev X24 X29 X26 X26 8") 
  tranmain_master__start.writeAction(f"movir X27 0") 
  tranmain_master__start.writeAction(f"evlb X27 main_master::send_to_global_master_thread") 
  tranmain_master__start.writeAction(f"evi X27 X27 255 4") 
  tranmain_master__start.writeAction(f"ev X27 X27 X26 X26 8") 
  tranmain_master__start.writeAction(f"addi X23 X28 1") 
  tranmain_master__start.writeAction(f"sendr3_wret X27 main_master::map_launcher_done X29 X17 X28 X30") 
  tranmain_master__start.writeAction(f"add X26 X22 X26") 
  tranmain_master__start.writeAction(f"jmp __while_start_6_condition") 
  tranmain_master__start.writeAction(f"__if_start_2_post: yield") 
  
  # Writing code for event main_master::map_launcher_done
  tranmain_master__map_launcher_done = efa.writeEvent('main_master::map_launcher_done')
  tranmain_master__map_launcher_done.writeAction(f"__entry: addi X16 X16 1") 
  tranmain_master__map_launcher_done.writeAction(f"add X20 X8 X20") 
  tranmain_master__map_launcher_done.writeAction(f"bneu X16 X19 __if_map_launcher_done_2_post") 
  tranmain_master__map_launcher_done.writeAction(f"__if_map_launcher_done_0_true: movir X16 0") 
  tranmain_master__map_launcher_done.writeAction(f"bneiu X23 0 __if_map_launcher_done_4_false") 
  tranmain_master__map_launcher_done.writeAction(f"__if_map_launcher_done_3_true: evi X2 X25 main_master::map_all_launched 1") 
  tranmain_master__map_launcher_done.writeAction(f"sendr_wret X25 main_master::map_split_launcher_done X23 X23 X26") 
  tranmain_master__map_launcher_done.writeAction(f"sri X20 X25 1") 
  tranmain_master__map_launcher_done.writeAction(f"print '[DEBUG][NWID %lu] <map_launcher_done> update_v:%lu' X0 X25") 
  ## lmbuff[UPDATE_V] = return_value;

  tranmain_master__map_launcher_done.writeAction(f"jmp __if_map_launcher_done_2_post") 
  tranmain_master__map_launcher_done.writeAction(f"__if_map_launcher_done_4_false: addi X7 X25 0") 
  tranmain_master__map_launcher_done.writeAction(f"sli X23 X26 1") 
  tranmain_master__map_launcher_done.writeAction(f"addi X26 X26 43") 
  tranmain_master__map_launcher_done.writeAction(f"addi X26 X26 1") 
  tranmain_master__map_launcher_done.writeAction(f"movwlr X25(X26,0,0) X25") 
  tranmain_master__map_launcher_done.writeAction(f"movir X26 -1") 
  tranmain_master__map_launcher_done.writeAction(f"sri X26 X26 1") 
  tranmain_master__map_launcher_done.writeAction(f"sendr_wcont X25 X26 X20 X20") 
  tranmain_master__map_launcher_done.writeAction(f"__if_map_launcher_done_2_post: yield") 
  
  # Writing code for event main_master::map_all_launched
  tranmain_master__map_all_launched = efa.writeEvent('main_master::map_all_launched')
  tranmain_master__map_all_launched.writeAction(f"__entry: movir X20 0") 
  tranmain_master__map_all_launched.writeAction(f"bneiu X22 1 __if_map_all_launched_1_false") 
  tranmain_master__map_all_launched.writeAction(f"__if_map_all_launched_0_true: evi X2 X25 map_master__map_all_launched 1") 
  tranmain_master__map_all_launched.writeAction(f"addi X0 X26 0") 
  tranmain_master__map_all_launched.writeAction(f"add X26 X19 X24") 
  tranmain_master__map_all_launched.writeAction(f"__while_map_all_launched_3_condition: ble X24 X26 __while_map_all_launched_5_post") 
  tranmain_master__map_all_launched.writeAction(f"__while_map_all_launched_4_body: ev X25 X29 X26 X26 8") 
  tranmain_master__map_all_launched.writeAction(f"movir X27 0") 
  tranmain_master__map_all_launched.writeAction(f"evlb X27 map_master__send_to_map_master_thread") 
  tranmain_master__map_all_launched.writeAction(f"evi X27 X27 255 4") 
  tranmain_master__map_all_launched.writeAction(f"ev X27 X27 X26 X26 8") 
  tranmain_master__map_all_launched.writeAction(f"sendr_wret X27 main_master::map_split_launcher_done X29 X17 X28") 
  tranmain_master__map_all_launched.writeAction(f"addi X26 X26 1") 
  tranmain_master__map_all_launched.writeAction(f"jmp __while_map_all_launched_3_condition") 
  tranmain_master__map_all_launched.writeAction(f"__while_map_all_launched_5_post: jmp __if_map_all_launched_2_post") 
  tranmain_master__map_all_launched.writeAction(f"__if_map_all_launched_1_false: evi X2 X25 main_master::map_all_launched 1") 
  tranmain_master__map_all_launched.writeAction(f"addi X0 X24 0") 
  tranmain_master__map_all_launched.writeAction(f"mul X19 X22 X26") 
  tranmain_master__map_all_launched.writeAction(f"add X24 X26 X26") 
  tranmain_master__map_all_launched.writeAction(f"__while_map_all_launched_6_condition: ble X26 X24 __if_map_all_launched_2_post") 
  tranmain_master__map_all_launched.writeAction(f"__while_map_all_launched_7_body: ev X25 X29 X24 X24 8") 
  tranmain_master__map_all_launched.writeAction(f"movir X27 0") 
  tranmain_master__map_all_launched.writeAction(f"evlb X27 main_master::send_to_global_master_thread") 
  tranmain_master__map_all_launched.writeAction(f"evi X27 X27 255 4") 
  tranmain_master__map_all_launched.writeAction(f"ev X27 X27 X24 X24 8") 
  tranmain_master__map_all_launched.writeAction(f"addi X23 X28 1") 
  tranmain_master__map_all_launched.writeAction(f"sendr3_wret X27 main_master::map_split_launcher_done X29 X17 X28 X30") 
  tranmain_master__map_all_launched.writeAction(f"add X24 X22 X24") 
  tranmain_master__map_all_launched.writeAction(f"jmp __while_map_all_launched_6_condition") 
  tranmain_master__map_all_launched.writeAction(f"__if_map_all_launched_2_post: yield") 
  
  # Writing code for event main_master::map_split_launcher_done
  tranmain_master__map_split_launcher_done = efa.writeEvent('main_master::map_split_launcher_done')
  tranmain_master__map_split_launcher_done.writeAction(f"__entry: addi X16 X16 1") 
  tranmain_master__map_split_launcher_done.writeAction(f"add X20 X8 X20") 
  tranmain_master__map_split_launcher_done.writeAction(f"bneu X16 X19 __if_map_split_launcher_done_2_post") 
  tranmain_master__map_split_launcher_done.writeAction(f"__if_map_split_launcher_done_0_true: movir X16 0") 
  tranmain_master__map_split_launcher_done.writeAction(f"bneiu X23 0 __if_map_split_launcher_done_4_false") 
  tranmain_master__map_split_launcher_done.writeAction(f"__if_map_split_launcher_done_3_true: evi X2 X26 main_master::map_split_all_launched 1") 
  tranmain_master__map_split_launcher_done.writeAction(f"sendr_wret X26 main_master::reduce_launcher_done X23 X23 X24") 
  tranmain_master__map_split_launcher_done.writeAction(f"sri X20 X26 1") 
  tranmain_master__map_split_launcher_done.writeAction(f"print '[DEBUG][NWID %lu] <map_split_launcher_done> update_split_v:%lu' X0 X26") 
  tranmain_master__map_split_launcher_done.writeAction(f"jmp __if_map_split_launcher_done_2_post") 
  tranmain_master__map_split_launcher_done.writeAction(f"__if_map_split_launcher_done_4_false: addi X7 X26 0") 
  tranmain_master__map_split_launcher_done.writeAction(f"sli X23 X24 1") 
  tranmain_master__map_split_launcher_done.writeAction(f"addi X24 X24 43") 
  tranmain_master__map_split_launcher_done.writeAction(f"addi X24 X24 1") 
  tranmain_master__map_split_launcher_done.writeAction(f"movwlr X26(X24,0,0) X26") 
  tranmain_master__map_split_launcher_done.writeAction(f"movir X24 -1") 
  tranmain_master__map_split_launcher_done.writeAction(f"sri X24 X24 1") 
  tranmain_master__map_split_launcher_done.writeAction(f"sendr_wcont X26 X24 X20 X20") 
  tranmain_master__map_split_launcher_done.writeAction(f"__if_map_split_launcher_done_2_post: yield") 
  
  # Writing code for event main_master::map_split_all_launched
  tranmain_master__map_split_all_launched = efa.writeEvent('main_master::map_split_all_launched')
  tranmain_master__map_split_all_launched.writeAction(f"__entry: movir X20 0") 
  tranmain_master__map_split_all_launched.writeAction(f"bneiu X22 1 __if_map_split_all_launched_1_false") 
  tranmain_master__map_split_all_launched.writeAction(f"__if_map_split_all_launched_0_true: evi X2 X26 map_master__map_split_all_launched 1") 
  tranmain_master__map_split_all_launched.writeAction(f"addi X0 X24 0") 
  tranmain_master__map_split_all_launched.writeAction(f"add X24 X19 X25") 
  tranmain_master__map_split_all_launched.writeAction(f"__while_map_split_all_launched_3_condition: ble X25 X24 __while_map_split_all_launched_5_post") 
  tranmain_master__map_split_all_launched.writeAction(f"__while_map_split_all_launched_4_body: ev X26 X29 X24 X24 8") 
  tranmain_master__map_split_all_launched.writeAction(f"movir X27 0") 
  tranmain_master__map_split_all_launched.writeAction(f"evlb X27 map_master__send_to_map_master_thread") 
  tranmain_master__map_split_all_launched.writeAction(f"evi X27 X27 255 4") 
  tranmain_master__map_split_all_launched.writeAction(f"ev X27 X27 X24 X24 8") 
  tranmain_master__map_split_all_launched.writeAction(f"sendr_wret X27 main_master::reduce_launcher_done X29 X24 X28") 
  tranmain_master__map_split_all_launched.writeAction(f"addi X24 X24 1") 
  tranmain_master__map_split_all_launched.writeAction(f"jmp __while_map_split_all_launched_3_condition") 
  tranmain_master__map_split_all_launched.writeAction(f"__while_map_split_all_launched_5_post: jmp __if_map_split_all_launched_2_post") 
  tranmain_master__map_split_all_launched.writeAction(f"__if_map_split_all_launched_1_false: evi X2 X25 main_master::map_split_all_launched 1") 
  tranmain_master__map_split_all_launched.writeAction(f"addi X0 X24 0") 
  tranmain_master__map_split_all_launched.writeAction(f"mul X19 X22 X26") 
  tranmain_master__map_split_all_launched.writeAction(f"add X24 X26 X26") 
  tranmain_master__map_split_all_launched.writeAction(f"__while_map_split_all_launched_6_condition: ble X26 X24 __if_map_split_all_launched_2_post") 
  tranmain_master__map_split_all_launched.writeAction(f"__while_map_split_all_launched_7_body: ev X25 X29 X24 X24 8") 
  tranmain_master__map_split_all_launched.writeAction(f"movir X27 0") 
  tranmain_master__map_split_all_launched.writeAction(f"evlb X27 main_master::send_to_global_master_thread") 
  tranmain_master__map_split_all_launched.writeAction(f"evi X27 X27 255 4") 
  tranmain_master__map_split_all_launched.writeAction(f"ev X27 X27 X24 X24 8") 
  tranmain_master__map_split_all_launched.writeAction(f"addi X23 X28 1") 
  tranmain_master__map_split_all_launched.writeAction(f"sendr3_wret X27 main_master::reduce_launcher_done X29 X17 X28 X30") 
  tranmain_master__map_split_all_launched.writeAction(f"add X24 X22 X24") 
  tranmain_master__map_split_all_launched.writeAction(f"jmp __while_map_split_all_launched_6_condition") 
  tranmain_master__map_split_all_launched.writeAction(f"__if_map_split_all_launched_2_post: yield") 
  
  # Writing code for event main_master::reduce_launcher_done
  tranmain_master__reduce_launcher_done = efa.writeEvent('main_master::reduce_launcher_done')
  tranmain_master__reduce_launcher_done.writeAction(f"__entry: addi X16 X16 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"add X8 X20 X20") 
  tranmain_master__reduce_launcher_done.writeAction(f"add X9 X21 X21") 
  tranmain_master__reduce_launcher_done.writeAction(f"addi X7 X26 0") 
  tranmain_master__reduce_launcher_done.writeAction(f"bneu X16 X19 __if_reduce_launcher_done_2_post") 
  tranmain_master__reduce_launcher_done.writeAction(f"__if_reduce_launcher_done_0_true: movir X16 0") 
  tranmain_master__reduce_launcher_done.writeAction(f"bneiu X23 0 __if_reduce_launcher_done_4_false") 
  tranmain_master__reduce_launcher_done.writeAction(f"__if_reduce_launcher_done_3_true: sri X20 X24 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"print '[Itera %lu]: add queue %lu traversed edges %lu' X17 X24 X21") 
  tranmain_master__reduce_launcher_done.writeAction(f"bneiu X20 0 __if_reduce_launcher_done_7_false") 
  tranmain_master__reduce_launcher_done.writeAction(f"__if_reduce_launcher_done_6_true: print 'BFS finish'") 
  tranmain_master__reduce_launcher_done.writeAction(f"movir X24 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"movrl X24 0(X26) 0 8") 
  tranmain_master__reduce_launcher_done.writeAction(f"yield_terminate") 
  tranmain_master__reduce_launcher_done.writeAction(f"jmp __if_reduce_launcher_done_8_post") 
  tranmain_master__reduce_launcher_done.writeAction(f"__if_reduce_launcher_done_7_false: addi X17 X17 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"movrl X17 312(X26) 0 8") 
  ## lmbuff[CONTROL_LEVEL] = 0;

  tranmain_master__reduce_launcher_done.writeAction(f"addi X7 X24 280") 
  ## unsigned long* local lmbuff_tmp = LMBASE + (SENDBUFFER * 8);

  ## lmbuff_tmp[0] = lmbuff[NUM_LANES_TOTAL];

  ## lmbuff_tmp[1] = lmbuff[GV];

  ## lmbuff_tmp[2] = lmbuff[MAIN_QUEUE_START];

  ## lmbuff_tmp[3] = lmbuff[QUEUE_LENGTH];

  ## lmbuff_tmp[4] = lmbuff[ITERATION];

  ## lmbuff_tmp[5] = lmbuff[NUM_LANES_TOTAL];

  ## lmbuff_tmp[6] = lmbuff[LOG2_NUM_CONTROL_LANE];

  ## lmbuff_tmp[7] = 0;

  tranmain_master__reduce_launcher_done.writeAction(f"evi X2 X25 main_master::init 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"send_wret X25 main_master::init_done X24 8 X29") 
  tranmain_master__reduce_launcher_done.writeAction(f"yield") 
  tranmain_master__reduce_launcher_done.writeAction(f"__if_reduce_launcher_done_8_post: jmp __if_reduce_launcher_done_2_post") 
  tranmain_master__reduce_launcher_done.writeAction(f"__if_reduce_launcher_done_4_false: sli X23 X24 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"addi X24 X24 43") 
  tranmain_master__reduce_launcher_done.writeAction(f"addi X24 X24 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"movwlr X26(X24,0,0) X24") 
  tranmain_master__reduce_launcher_done.writeAction(f"movir X25 -1") 
  tranmain_master__reduce_launcher_done.writeAction(f"sri X25 X25 1") 
  tranmain_master__reduce_launcher_done.writeAction(f"sendr_wcont X24 X25 X20 X21") 
  tranmain_master__reduce_launcher_done.writeAction(f"yield_terminate") 
  tranmain_master__reduce_launcher_done.writeAction(f"__if_reduce_launcher_done_2_post: yield") 
  