from linker.EFAProgram import efaProgram
from linker.EFAsections.StaticDataSection import staticDataType

@efaProgram
def efaProgram_msrUDW(efa):

    ## init_null_state
    init_null_state = efa.State("init_null_state")
    efa.add_state(init_null_state)
    efa.add_initId(init_null_state.state_id)

    ## Add event ids and names:

    ## Broadcast__broadcast_global
    Broadcast__broadcast_global = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_global")
    Broadcast__broadcast_global.writeAction("addi X8 X27 0")
    Broadcast__broadcast_global.writeAction("sri X27 X25 11")
    Broadcast__broadcast_global.writeAction("movir X16 16384")
    Broadcast__broadcast_global.writeAction("bgt X25 X16 GenLinkableBroadcast_rjncy_max_child_modular_eq_zero")
    Broadcast__broadcast_global.writeAction("andi X27 X16 2047")
    Broadcast__broadcast_global.writeAction("beqi X16 0 GenLinkableBroadcast_rjncy_modular_eq_zero")
    Broadcast__broadcast_global.writeAction("addi X25 X25 1")
    Broadcast__broadcast_global.writeAction("jmp GenLinkableBroadcast_rjncy_modular_eq_zero")
    Broadcast__broadcast_global.writeAction("GenLinkableBroadcast_rjncy_max_child_modular_eq_zero: mov_imm2reg X25 16384")
    Broadcast__broadcast_global.writeAction("GenLinkableBroadcast_rjncy_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_global.writeAction("evlb X28 Broadcast__broadcast_node")
    Broadcast__broadcast_global.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_global.writeAction("GenLinkableBroadcast_rjncy_broadcast_loop: lshift X17 X16 11")
    Broadcast__broadcast_global.writeAction("add X0 X16 X16")
    Broadcast__broadcast_global.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_global.writeAction("sendops_wret X28 Broadcast__broadcast_global_fin X8 8 X16")
    Broadcast__broadcast_global.writeAction("addi X17 X17 1")
    Broadcast__broadcast_global.writeAction("blt X17 X25 GenLinkableBroadcast_rjncy_broadcast_loop")
    Broadcast__broadcast_global.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_global.writeAction("yield")

    ## Broadcast__broadcast_node
    Broadcast__broadcast_node = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_node")
    Broadcast__broadcast_node.writeAction("addi X1 X29 0")
    Broadcast__broadcast_node.writeAction("sri X8 X25 6")
    Broadcast__broadcast_node.writeAction("movir X16 32")
    Broadcast__broadcast_node.writeAction("bgt X25 X16 GenLinkableBroadcast_rjncy_max_child_modular_eq_zero")
    Broadcast__broadcast_node.writeAction("andi X8 X16 63")
    Broadcast__broadcast_node.writeAction("beqi X16 0 GenLinkableBroadcast_rjncy_modular_eq_zero")
    Broadcast__broadcast_node.writeAction("addi X25 X25 1")
    Broadcast__broadcast_node.writeAction("jmp GenLinkableBroadcast_rjncy_modular_eq_zero")
    Broadcast__broadcast_node.writeAction("GenLinkableBroadcast_rjncy_max_child_modular_eq_zero: mov_imm2reg X25 32")
    Broadcast__broadcast_node.writeAction("GenLinkableBroadcast_rjncy_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_node.writeAction("evlb X28 Broadcast__broadcast_ud")
    Broadcast__broadcast_node.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_node.writeAction("GenLinkableBroadcast_rjncy_broadcast_loop: lshift X17 X16 6")
    Broadcast__broadcast_node.writeAction("add X0 X16 X16")
    Broadcast__broadcast_node.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_node.writeAction("sendops_wret X28 Broadcast__broadcast_node_fin X8 8 X16")
    Broadcast__broadcast_node.writeAction("addi X17 X17 1")
    Broadcast__broadcast_node.writeAction("blt X17 X25 GenLinkableBroadcast_rjncy_broadcast_loop")
    Broadcast__broadcast_node.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_node.writeAction("yield")

    ## Broadcast__broadcast_ud
    Broadcast__broadcast_ud = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_ud")
    Broadcast__broadcast_ud.writeAction("addi X1 X29 0")
    Broadcast__broadcast_ud.writeAction("movir X25 64")
    Broadcast__broadcast_ud.writeAction("bgt X8 X25 GenLinkableBroadcast_rjncy_modular_eq_zero")
    Broadcast__broadcast_ud.writeAction("addi X8 X25 0")
    Broadcast__broadcast_ud.writeAction("GenLinkableBroadcast_rjncy_modular_eq_zero: evi X2 X28 255 4")
    Broadcast__broadcast_ud.writeAction("ev X28 X28 X9 X9 1")
    Broadcast__broadcast_ud.writeAction("mov_imm2reg X17 0")
    Broadcast__broadcast_ud.writeAction("GenLinkableBroadcast_rjncy_broadcast_loop: add X0 X17 X16")
    Broadcast__broadcast_ud.writeAction("ev X28 X28 X16 X16 8")
    Broadcast__broadcast_ud.writeAction("sendops_wret X28 Broadcast__broadcast_ud_fin X10 6 X16")
    Broadcast__broadcast_ud.writeAction("addi X17 X17 1")
    Broadcast__broadcast_ud.writeAction("blt X17 X25 GenLinkableBroadcast_rjncy_broadcast_loop")
    Broadcast__broadcast_ud.writeAction("mov_imm2reg X26 0")
    Broadcast__broadcast_ud.writeAction("yield")

    ## Broadcast__broadcast_ud_fin
    Broadcast__broadcast_ud_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_ud_fin")
    Broadcast__broadcast_ud_fin.writeAction("addi X26 X26 1")
    Broadcast__broadcast_ud_fin.writeAction("blt X26 X25 GenLinkableBroadcast_rjncy_continue")
    Broadcast__broadcast_ud_fin.writeAction("movir X30 -1")
    Broadcast__broadcast_ud_fin.writeAction("sri X30 X30 1")
    Broadcast__broadcast_ud_fin.writeAction("sendr_wcont X29 X30 X0 X2 ")
    Broadcast__broadcast_ud_fin.writeAction("yield_terminate")
    Broadcast__broadcast_ud_fin.writeAction("GenLinkableBroadcast_rjncy_continue: yield")

    ## Broadcast__broadcast_node_fin
    Broadcast__broadcast_node_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_node_fin")
    Broadcast__broadcast_node_fin.writeAction("addi X26 X26 1")
    Broadcast__broadcast_node_fin.writeAction("blt X26 X25 GenLinkableBroadcast_rjncy_continue")
    Broadcast__broadcast_node_fin.writeAction("sendr_reply X0 X2 X16")
    Broadcast__broadcast_node_fin.writeAction("yield_terminate")
    Broadcast__broadcast_node_fin.writeAction("GenLinkableBroadcast_rjncy_continue: yield")

    ## Broadcast__broadcast_global_fin
    Broadcast__broadcast_global_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_global_fin")
    Broadcast__broadcast_global_fin.writeAction("addi X26 X26 1")
    Broadcast__broadcast_global_fin.writeAction("beq X26 X25 GenLinkableBroadcast_rjncy_global_bcst_finish")
    Broadcast__broadcast_global_fin.writeAction("yield")
    Broadcast__broadcast_global_fin.writeAction("GenLinkableBroadcast_rjncy_global_bcst_finish: sendr_reply X0 X2 X16")
    Broadcast__broadcast_global_fin.writeAction("yieldt")

    ## Broadcast__broadcast_value_to_scratchpad
    Broadcast__broadcast_value_to_scratchpad = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "Broadcast__broadcast_value_to_scratchpad")
    Broadcast__broadcast_value_to_scratchpad.writeAction("sri X8 X16 32")
    Broadcast__broadcast_value_to_scratchpad.writeAction("add X7 X16 X16")
    Broadcast__broadcast_value_to_scratchpad.writeAction("andi X8 X17 15")
    Broadcast__broadcast_value_to_scratchpad.writeAction("bcpyol X9 X16 X17")
    Broadcast__broadcast_value_to_scratchpad.writeAction("sendr_reply X1 X2 X16")
    Broadcast__broadcast_value_to_scratchpad.writeAction("yieldt")

    ## splitPageRankMS__map_shuffle_reduce
    splitPageRankMS__map_shuffle_reduce = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__map_shuffle_reduce")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X7 X20 688")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X1 X31 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("move X31 0(X20) 0 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X8 X16 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X10 X27 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("mul X9 X27 X19")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X2 X21 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("evlb X21 splitPageRankMS__finish_init_udkvmsr")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X7 X20 768")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X11 X29 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("bcpylli X29 X20 16")
    splitPageRankMS__map_shuffle_reduce.writeAction("sendr_wcont X21 X21 X16 X19 ")
    splitPageRankMS__map_shuffle_reduce.writeAction("evi X2 X30 255 4")
    splitPageRankMS__map_shuffle_reduce.writeAction("evlb X30 splitPageRankMS__broadcast_global")
    splitPageRankMS__map_shuffle_reduce.writeAction("movir X17 704")
    splitPageRankMS__map_shuffle_reduce.writeAction("add X7 X17 X17")
    splitPageRankMS__map_shuffle_reduce.writeAction("movrl X27 0(X17) 0 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("movir X18 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("evlb X18 splitPageRankMS__init_sp_lane")
    splitPageRankMS__map_shuffle_reduce.writeAction("movrl X18 8(X17) 0 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("movrl X27  16(X17) 0 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("movrl X0 24(X17) 0 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("send_wcont X30 X21 X17 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X17 X20 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("movir X18 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("evlb X18 splitPageRankMS__init_input_kvset_on_lane")
    splitPageRankMS__map_shuffle_reduce.writeAction("movrl X18 0(X20) 1 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X11 X29 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("bcpylli X29 X20 16")
    splitPageRankMS__map_shuffle_reduce.writeAction("send_wcont X30 X21 X17 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X17 X20 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("movir X18 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("evlb X18 splitPageRankMS__init_output_kvset_on_lane")
    splitPageRankMS__map_shuffle_reduce.writeAction("movrl X18 0(X20) 1 8")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X12 X29 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("bcpylli X29 X20 16")
    splitPageRankMS__map_shuffle_reduce.writeAction("send_wcont X30 X21 X17 8 ")
    splitPageRankMS__map_shuffle_reduce.writeAction("movir X26 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("addi X9 X19 0")
    splitPageRankMS__map_shuffle_reduce.writeAction("yield")

    ## splitPageRankMS__finish_init_udkvmsr
    splitPageRankMS__finish_init_udkvmsr = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__finish_init_udkvmsr")
    splitPageRankMS__finish_init_udkvmsr.writeAction("perflog 1 0 'UDKVMSR Initializat Finished.' ")
    splitPageRankMS__finish_init_udkvmsr.writeAction("addi X26 X26 1")
    splitPageRankMS__finish_init_udkvmsr.writeAction("bgei X26 4 GenLinkableMapShuffleReduceEFA_yrlui_finish_initialize_udkvmsr")
    splitPageRankMS__finish_init_udkvmsr.writeAction("yield")
    splitPageRankMS__finish_init_udkvmsr.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_finish_initialize_udkvmsr: addi X2 X30 0")
    splitPageRankMS__finish_init_udkvmsr.writeAction("evlb X30 splitPageRankMS__init_global_master")
    splitPageRankMS__finish_init_udkvmsr.writeAction("sendr_wcont X30 X31 X16 X19")
    splitPageRankMS__finish_init_udkvmsr.writeAction("yield")

    ## splitPageRankMS__broadcast_global
    splitPageRankMS__broadcast_global = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__broadcast_global")
    splitPageRankMS__broadcast_global.writeAction("addi X8 X27 0")
    splitPageRankMS__broadcast_global.writeAction("sri X27 X25 11")
    splitPageRankMS__broadcast_global.writeAction("movir X16 16384")
    splitPageRankMS__broadcast_global.writeAction("bgt X25 X16 GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero")
    splitPageRankMS__broadcast_global.writeAction("andi X27 X16 2047")
    splitPageRankMS__broadcast_global.writeAction("beqi X16 0 GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__broadcast_global.writeAction("addi X25 X25 1")
    splitPageRankMS__broadcast_global.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__broadcast_global.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero: mov_imm2reg X25 16384")
    splitPageRankMS__broadcast_global.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero: evi X2 X28 255 4")
    splitPageRankMS__broadcast_global.writeAction("evlb X28 splitPageRankMS__broadcast_node")
    splitPageRankMS__broadcast_global.writeAction("mov_imm2reg X17 0")
    splitPageRankMS__broadcast_global.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop: lshift X17 X16 11")
    splitPageRankMS__broadcast_global.writeAction("add X0 X16 X16")
    splitPageRankMS__broadcast_global.writeAction("ev X28 X28 X16 X16 8")
    splitPageRankMS__broadcast_global.writeAction("sendops_wret X28 splitPageRankMS__broadcast_global_fin X8 8 X16")
    splitPageRankMS__broadcast_global.writeAction("addi X17 X17 1")
    splitPageRankMS__broadcast_global.writeAction("blt X17 X25 GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop")
    splitPageRankMS__broadcast_global.writeAction("mov_imm2reg X26 0")
    splitPageRankMS__broadcast_global.writeAction("yield")

    ## splitPageRankMS__broadcast_node
    splitPageRankMS__broadcast_node = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__broadcast_node")
    splitPageRankMS__broadcast_node.writeAction("addi X1 X29 0")
    splitPageRankMS__broadcast_node.writeAction("sri X8 X25 6")
    splitPageRankMS__broadcast_node.writeAction("movir X16 32")
    splitPageRankMS__broadcast_node.writeAction("bgt X25 X16 GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero")
    splitPageRankMS__broadcast_node.writeAction("andi X8 X16 63")
    splitPageRankMS__broadcast_node.writeAction("beqi X16 0 GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__broadcast_node.writeAction("addi X25 X25 1")
    splitPageRankMS__broadcast_node.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__broadcast_node.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero: mov_imm2reg X25 32")
    splitPageRankMS__broadcast_node.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero: evi X2 X28 255 4")
    splitPageRankMS__broadcast_node.writeAction("evlb X28 splitPageRankMS__broadcast_ud")
    splitPageRankMS__broadcast_node.writeAction("mov_imm2reg X17 0")
    splitPageRankMS__broadcast_node.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop: lshift X17 X16 6")
    splitPageRankMS__broadcast_node.writeAction("add X0 X16 X16")
    splitPageRankMS__broadcast_node.writeAction("ev X28 X28 X16 X16 8")
    splitPageRankMS__broadcast_node.writeAction("sendops_wret X28 splitPageRankMS__broadcast_node_fin X8 8 X16")
    splitPageRankMS__broadcast_node.writeAction("addi X17 X17 1")
    splitPageRankMS__broadcast_node.writeAction("blt X17 X25 GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop")
    splitPageRankMS__broadcast_node.writeAction("mov_imm2reg X26 0")
    splitPageRankMS__broadcast_node.writeAction("yield")

    ## splitPageRankMS__broadcast_ud
    splitPageRankMS__broadcast_ud = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__broadcast_ud")
    splitPageRankMS__broadcast_ud.writeAction("addi X1 X29 0")
    splitPageRankMS__broadcast_ud.writeAction("movir X25 64")
    splitPageRankMS__broadcast_ud.writeAction("bgt X8 X25 GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__broadcast_ud.writeAction("addi X8 X25 0")
    splitPageRankMS__broadcast_ud.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero: evi X2 X28 255 4")
    splitPageRankMS__broadcast_ud.writeAction("ev X28 X28 X9 X9 1")
    splitPageRankMS__broadcast_ud.writeAction("mov_imm2reg X17 0")
    splitPageRankMS__broadcast_ud.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop: add X0 X17 X16")
    splitPageRankMS__broadcast_ud.writeAction("ev X28 X28 X16 X16 8")
    splitPageRankMS__broadcast_ud.writeAction("sendops_wret X28 splitPageRankMS__broadcast_ud_fin X10 6 X16")
    splitPageRankMS__broadcast_ud.writeAction("addi X17 X17 1")
    splitPageRankMS__broadcast_ud.writeAction("blt X17 X25 GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop")
    splitPageRankMS__broadcast_ud.writeAction("mov_imm2reg X26 0")
    splitPageRankMS__broadcast_ud.writeAction("yield")

    ## splitPageRankMS__broadcast_ud_fin
    splitPageRankMS__broadcast_ud_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__broadcast_ud_fin")
    splitPageRankMS__broadcast_ud_fin.writeAction("addi X26 X26 1")
    splitPageRankMS__broadcast_ud_fin.writeAction("blt X26 X25 GenLinkableMapShuffleReduceEFA_yrlui_continue")
    splitPageRankMS__broadcast_ud_fin.writeAction("movir X30 -1")
    splitPageRankMS__broadcast_ud_fin.writeAction("sri X30 X30 1")
    splitPageRankMS__broadcast_ud_fin.writeAction("sendr_wcont X29 X30 X0 X2 ")
    splitPageRankMS__broadcast_ud_fin.writeAction("yield_terminate")
    splitPageRankMS__broadcast_ud_fin.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_continue: yield")

    ## splitPageRankMS__broadcast_node_fin
    splitPageRankMS__broadcast_node_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__broadcast_node_fin")
    splitPageRankMS__broadcast_node_fin.writeAction("addi X26 X26 1")
    splitPageRankMS__broadcast_node_fin.writeAction("blt X26 X25 GenLinkableMapShuffleReduceEFA_yrlui_continue")
    splitPageRankMS__broadcast_node_fin.writeAction("sendr_reply X0 X2 X16")
    splitPageRankMS__broadcast_node_fin.writeAction("yield_terminate")
    splitPageRankMS__broadcast_node_fin.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_continue: yield")

    ## splitPageRankMS__broadcast_global_fin
    splitPageRankMS__broadcast_global_fin = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__broadcast_global_fin")
    splitPageRankMS__broadcast_global_fin.writeAction("addi X26 X26 1")
    splitPageRankMS__broadcast_global_fin.writeAction("beq X26 X25 GenLinkableMapShuffleReduceEFA_yrlui_global_bcst_finish")
    splitPageRankMS__broadcast_global_fin.writeAction("yield")
    splitPageRankMS__broadcast_global_fin.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_global_bcst_finish: sendr_reply X0 X2 X16")
    splitPageRankMS__broadcast_global_fin.writeAction("yieldt")

    ## splitPageRankMS__broadcast_value_to_scratchpad
    splitPageRankMS__broadcast_value_to_scratchpad = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__broadcast_value_to_scratchpad")
    splitPageRankMS__broadcast_value_to_scratchpad.writeAction("sri X8 X16 32")
    splitPageRankMS__broadcast_value_to_scratchpad.writeAction("add X7 X16 X16")
    splitPageRankMS__broadcast_value_to_scratchpad.writeAction("andi X8 X17 15")
    splitPageRankMS__broadcast_value_to_scratchpad.writeAction("bcpyol X9 X16 X17")
    splitPageRankMS__broadcast_value_to_scratchpad.writeAction("sendr_reply X1 X2 X16")
    splitPageRankMS__broadcast_value_to_scratchpad.writeAction("yieldt")

    ## splitPageRankMS__init_input_kvset_on_lane
    splitPageRankMS__init_input_kvset_on_lane = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_input_kvset_on_lane")
    splitPageRankMS__init_input_kvset_on_lane.writeAction("movir X16 768")
    splitPageRankMS__init_input_kvset_on_lane.writeAction("add X7 X16 X16")
    splitPageRankMS__init_input_kvset_on_lane.writeAction("bcpyoli X8 X16 2")
    splitPageRankMS__init_input_kvset_on_lane.writeAction("sendr_reply X0 X16 X28")
    splitPageRankMS__init_input_kvset_on_lane.writeAction("yield_terminate")

    ## splitPageRankMS__init_output_kvset_on_lane
    splitPageRankMS__init_output_kvset_on_lane = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_output_kvset_on_lane")
    splitPageRankMS__init_output_kvset_on_lane.writeAction("movir X16 832")
    splitPageRankMS__init_output_kvset_on_lane.writeAction("add X7 X16 X16")
    splitPageRankMS__init_output_kvset_on_lane.writeAction("bcpyoli X8 X16  2")
    splitPageRankMS__init_output_kvset_on_lane.writeAction("sendr_reply X0 X16 X28")
    splitPageRankMS__init_output_kvset_on_lane.writeAction("yield_terminate")

    ## splitPageRankMS__init_sp_lane
    splitPageRankMS__init_sp_lane = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_sp_lane")
    splitPageRankMS__init_sp_lane.writeAction("mov_imm2reg UDPR_0 0")
    splitPageRankMS__init_sp_lane.writeAction("addi X7 X20 640")
    splitPageRankMS__init_sp_lane.writeAction("move UDPR_0 0(X20) 0 8")
    splitPageRankMS__init_sp_lane.writeAction("move UDPR_0 8(X20) 0 8")
    splitPageRankMS__init_sp_lane.writeAction("move UDPR_0 24(X20) 0 8")
    splitPageRankMS__init_sp_lane.writeAction("movir X28 220")
    splitPageRankMS__init_sp_lane.writeAction("move X28 32(X20) 0 8")
    splitPageRankMS__init_sp_lane.writeAction("subi X8 X28 1")
    splitPageRankMS__init_sp_lane.writeAction("move X28 40(X20) 0 8")
    splitPageRankMS__init_sp_lane.writeAction("move X9 56(X20) 0 8")
    splitPageRankMS__init_sp_lane.writeAction("movir X16 -1")
    splitPageRankMS__init_sp_lane.writeAction("movir X19 2048")
    splitPageRankMS__init_sp_lane.writeAction("movir X17 1600")
    splitPageRankMS__init_sp_lane.writeAction("add X7 X17 X17")
    splitPageRankMS__init_sp_lane.writeAction("mov_imm2reg X18 0")
    splitPageRankMS__init_sp_lane.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_init_cache_loop: movwrl X16 X17(X18,1,1)")
    splitPageRankMS__init_sp_lane.writeAction("blt X18 X19 GenLinkableMapShuffleReduceEFA_yrlui_init_cache_loop")
    splitPageRankMS__init_sp_lane.writeAction("sendr_reply X0 X16 X28")
    splitPageRankMS__init_sp_lane.writeAction("yield_terminate")

    ## splitPageRankMS__init_global_master
    splitPageRankMS__init_global_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_global_master")
    splitPageRankMS__init_global_master.writeAction("mul X27 X9 X24")
    splitPageRankMS__init_global_master.writeAction("sri X27 X25 11")
    splitPageRankMS__init_global_master.writeAction("movir X28 16384")
    splitPageRankMS__init_global_master.writeAction("bgt X25 X28 GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero")
    splitPageRankMS__init_global_master.writeAction("andi X27 X28 2047")
    splitPageRankMS__init_global_master.writeAction("beqi X28 0 GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__init_global_master.writeAction("addi X25 X25 1")
    splitPageRankMS__init_global_master.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__init_global_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero: mov_imm2reg X25 16384")
    splitPageRankMS__init_global_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero: mov_imm2reg X22 2048")
    splitPageRankMS__init_global_master.writeAction("bge X27 X22 GenLinkableMapShuffleReduceEFA_yrlui_global_master_full_child")
    splitPageRankMS__init_global_master.writeAction("addi X27 X22 0")
    splitPageRankMS__init_global_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_global_master_full_child: mul X22 X9 X20")
    splitPageRankMS__init_global_master.writeAction("lshift X20 X18 4")
    splitPageRankMS__init_global_master.writeAction("mov_reg2reg X0 X23")
    splitPageRankMS__init_global_master.writeAction("movir X21 0")
    splitPageRankMS__init_global_master.writeAction("evi X2 X30 255 4")
    splitPageRankMS__init_global_master.writeAction("evlb X30 splitPageRankMS__init_node_master")
    splitPageRankMS__init_global_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_glb_master_loop: ev_update_reg_2             X30 X30 X23 X23 8")
    splitPageRankMS__init_global_master.writeAction("sendr3_wret X30 splitPageRankMS__global_master             X16 X18 X27 X28")
    splitPageRankMS__init_global_master.writeAction("add X22 X23 X23")
    splitPageRankMS__init_global_master.writeAction("add X18 X16 X16 ")
    splitPageRankMS__init_global_master.writeAction("addi X21 X21 1")
    splitPageRankMS__init_global_master.writeAction("blt X21 X25 GenLinkableMapShuffleReduceEFA_yrlui_glb_master_loop")
    splitPageRankMS__init_global_master.writeAction("mul X21 X20 X17")
    splitPageRankMS__init_global_master.writeAction("mov_imm2reg X19 0")
    splitPageRankMS__init_global_master.writeAction("yield")

    ## splitPageRankMS__global_master
    splitPageRankMS__global_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__global_master")
    splitPageRankMS__global_master.writeAction("add X8 X19 X19")
    splitPageRankMS__global_master.writeAction("bge X17 X24 GenLinkableMapShuffleReduceEFA_yrlui_global_master_fin_fetch")
    splitPageRankMS__global_master.writeAction("sendr3_wret X1 splitPageRankMS__global_master             X16 X18 X27 X28")
    splitPageRankMS__global_master.writeAction("add X20 X17 X17")
    splitPageRankMS__global_master.writeAction("add X18 X16 X16 ")
    splitPageRankMS__global_master.writeAction("yield")
    splitPageRankMS__global_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_global_master_fin_fetch: subi X21 X21 1")
    splitPageRankMS__global_master.writeAction("addi X1 X30 0")
    splitPageRankMS__global_master.writeAction("evlb X30 splitPageRankMS__termiante_node_master")
    splitPageRankMS__global_master.writeAction("sendr_wcont X30 X2 X16 X16")
    splitPageRankMS__global_master.writeAction("beqi X21 0 GenLinkableMapShuffleReduceEFA_yrlui_global_master_fin_map")
    splitPageRankMS__global_master.writeAction("yield")
    splitPageRankMS__global_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_global_master_fin_map: bnei X19 0 GenLinkableMapShuffleReduceEFA_yrlui_global_master_init_sync")
    splitPageRankMS__global_master.writeAction("movir X28 -1")
    splitPageRankMS__global_master.writeAction("sri X28 X28 1")
    splitPageRankMS__global_master.writeAction("sendr_wcont X31 X28 X27 X19")
    splitPageRankMS__global_master.writeAction("yieldt")
    splitPageRankMS__global_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_global_master_init_sync: evi X2 X30 255 4")
    splitPageRankMS__global_master.writeAction("evlb X30 splitPageRankMS__init_global_snyc")
    splitPageRankMS__global_master.writeAction("addi X2 X28 0")
    splitPageRankMS__global_master.writeAction("evlb X28 splitPageRankMS__cache_flush")
    splitPageRankMS__global_master.writeAction("sendr_wcont X30 X28 X27 X19")
    splitPageRankMS__global_master.writeAction("yield")

    ## splitPageRankMS__cache_flush
    splitPageRankMS__cache_flush = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__cache_flush")
    splitPageRankMS__cache_flush.writeAction("movir X20 704")
    splitPageRankMS__cache_flush.writeAction("add X20 X7 X20")
    splitPageRankMS__cache_flush.writeAction("movrl X27 0(X20) 0 8")
    splitPageRankMS__cache_flush.writeAction("movir X28 0")
    splitPageRankMS__cache_flush.writeAction("evlb X28 splitPageRankMS__combine_flush_lane")
    splitPageRankMS__cache_flush.writeAction("movrl X28 8(X20) 0 8")
    splitPageRankMS__cache_flush.writeAction("evi X2 X30 255 4")
    splitPageRankMS__cache_flush.writeAction("evlb X30 splitPageRankMS__broadcast_global")
    splitPageRankMS__cache_flush.writeAction("send_wret X30 splitPageRankMS__cache_flush_return X20 8 X28")
    splitPageRankMS__cache_flush.writeAction("yield")

    ## splitPageRankMS__cache_flush_return
    splitPageRankMS__cache_flush_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__cache_flush_return")
    splitPageRankMS__cache_flush_return.writeAction("print ' '")
    splitPageRankMS__cache_flush_return.writeAction("print '[DEBUG][NWID %ld][splitPageRankMS::cache_flush_return] Finish flushing the cache. UDKVMSR program splitPageRankMS terminates, number of reduce task process = %ld. Return to user continuation %lu' X0 X19 X31")
    splitPageRankMS__cache_flush_return.writeAction("movir X28 -1")
    splitPageRankMS__cache_flush_return.writeAction("sri X28 X28 1")
    splitPageRankMS__cache_flush_return.writeAction("sendr_wcont X31 X28 X19 X19")
    splitPageRankMS__cache_flush_return.writeAction("yieldt")

    ## splitPageRankMS__init_node_master
    splitPageRankMS__init_node_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_node_master")
    splitPageRankMS__init_node_master.writeAction("mov_reg2reg X1 X31")
    splitPageRankMS__init_node_master.writeAction("mov_reg2reg X8 X16")
    splitPageRankMS__init_node_master.writeAction("mov_reg2reg X10 X27")
    splitPageRankMS__init_node_master.writeAction("sri X27 X25 6")
    splitPageRankMS__init_node_master.writeAction("movir X28 32")
    splitPageRankMS__init_node_master.writeAction("bgt X25 X28 GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero")
    splitPageRankMS__init_node_master.writeAction("andi X27 X28 63")
    splitPageRankMS__init_node_master.writeAction("beqi X28 0 GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__init_node_master.writeAction("addi X25 X25 1")
    splitPageRankMS__init_node_master.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__init_node_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_child_modular_eq_zero: mov_imm2reg X25 32")
    splitPageRankMS__init_node_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero: add X9 X16 X24")
    splitPageRankMS__init_node_master.writeAction("mov_imm2reg X21 0")
    splitPageRankMS__init_node_master.writeAction("mov_imm2reg X22 64")
    splitPageRankMS__init_node_master.writeAction("bge X27 X22 GenLinkableMapShuffleReduceEFA_yrlui_node_master_full_child")
    splitPageRankMS__init_node_master.writeAction("addi X27 X22 0")
    splitPageRankMS__init_node_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_node_master_full_child: div X9 X25 X18")
    splitPageRankMS__init_node_master.writeAction("addi X0 X23 0")
    splitPageRankMS__init_node_master.writeAction("evi X2 X30 255 4")
    splitPageRankMS__init_node_master.writeAction("evlb X30 splitPageRankMS__init_updown_master")
    splitPageRankMS__init_node_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_node_master_loop: ev X30 X30 X23 X23 8")
    splitPageRankMS__init_node_master.writeAction("sendr3_wret X30 splitPageRankMS__node_master             X16 X18 X27 X28")
    splitPageRankMS__init_node_master.writeAction("add X22 X23 X23")
    splitPageRankMS__init_node_master.writeAction("add X18 X16 X16 ")
    splitPageRankMS__init_node_master.writeAction("addi X21 X21 1")
    splitPageRankMS__init_node_master.writeAction("blt X21 X25 GenLinkableMapShuffleReduceEFA_yrlui_node_master_loop")
    splitPageRankMS__init_node_master.writeAction("mov_imm2reg X19 0")
    splitPageRankMS__init_node_master.writeAction("yield")

    ## splitPageRankMS__node_master
    splitPageRankMS__node_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__node_master")
    splitPageRankMS__node_master.writeAction("add X8 X19 X19")
    splitPageRankMS__node_master.writeAction("bge X16 X24 GenLinkableMapShuffleReduceEFA_yrlui_node_master_fin_fetch")
    splitPageRankMS__node_master.writeAction("sendr3_wret X1 splitPageRankMS__node_master             X16 X18 X27 X28")
    splitPageRankMS__node_master.writeAction("add X18 X16 X16 ")
    splitPageRankMS__node_master.writeAction("yield")
    splitPageRankMS__node_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_node_master_fin_fetch: subi X21 X21 1")
    splitPageRankMS__node_master.writeAction("addi X1 X30 0")
    splitPageRankMS__node_master.writeAction("evlb X30 splitPageRankMS__terminate_updown_master")
    splitPageRankMS__node_master.writeAction("sendr_wcont X30 X2 X16 X22")
    splitPageRankMS__node_master.writeAction("beqi X21 0 GenLinkableMapShuffleReduceEFA_yrlui_node_master_fin_partition")
    splitPageRankMS__node_master.writeAction("yield")
    splitPageRankMS__node_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_node_master_fin_partition: sendr_wret X31 splitPageRankMS__init_node_master             X19 X19 X28")
    splitPageRankMS__node_master.writeAction("mov_imm2reg X19 0")
    splitPageRankMS__node_master.writeAction("yield")

    ## splitPageRankMS__termiante_node_master
    splitPageRankMS__termiante_node_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__termiante_node_master")
    splitPageRankMS__termiante_node_master.writeAction("yield_terminate")

    ## splitPageRankMS__init_updown_master
    splitPageRankMS__init_updown_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_updown_master")
    splitPageRankMS__init_updown_master.writeAction("mov_reg2reg X1 X31")
    splitPageRankMS__init_updown_master.writeAction("mov_reg2reg X8 X16")
    splitPageRankMS__init_updown_master.writeAction("mov_reg2reg X10 X27")
    splitPageRankMS__init_updown_master.writeAction("movir X25 64")
    splitPageRankMS__init_updown_master.writeAction("bgt X27 X25 GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero")
    splitPageRankMS__init_updown_master.writeAction("addi X27 X25 0")
    splitPageRankMS__init_updown_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_modular_eq_zero: add X9 X16 X24")
    splitPageRankMS__init_updown_master.writeAction("mov_imm2reg X21 0")
    splitPageRankMS__init_updown_master.writeAction("mov_imm2reg X18 16")
    splitPageRankMS__init_updown_master.writeAction("mov_reg2reg X0 X23")
    splitPageRankMS__init_updown_master.writeAction("evi X2 X30 255 4")
    splitPageRankMS__init_updown_master.writeAction("evlb X30 splitPageRankMS__lane_master_init")
    splitPageRankMS__init_updown_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_updown_master_loop: ev X30 X30 X23 X23 8")
    splitPageRankMS__init_updown_master.writeAction("sendr3_wret X30 splitPageRankMS__updown_master             X16 X18 X21 X28")
    splitPageRankMS__init_updown_master.writeAction("addi X23 X23 1")
    splitPageRankMS__init_updown_master.writeAction("add X18 X16 X16 ")
    splitPageRankMS__init_updown_master.writeAction("addi X21 X21 1")
    splitPageRankMS__init_updown_master.writeAction("blt X21 X25 GenLinkableMapShuffleReduceEFA_yrlui_updown_master_loop")
    splitPageRankMS__init_updown_master.writeAction("mov_imm2reg X19 0")
    splitPageRankMS__init_updown_master.writeAction("addi X21 X22 0")
    splitPageRankMS__init_updown_master.writeAction("yield")

    ## splitPageRankMS__updown_master
    splitPageRankMS__updown_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__updown_master")
    splitPageRankMS__updown_master.writeAction("add X8 X19 X19")
    splitPageRankMS__updown_master.writeAction("bge X16 X24 GenLinkableMapShuffleReduceEFA_yrlui_updown_master_fin_fetch")
    splitPageRankMS__updown_master.writeAction("sendr3_wret X1 splitPageRankMS__updown_master                 X16 X18 X22 X28")
    splitPageRankMS__updown_master.writeAction("addi X22 X22 1")
    splitPageRankMS__updown_master.writeAction("add X18 X16 X16 ")
    splitPageRankMS__updown_master.writeAction("yield")
    splitPageRankMS__updown_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_updown_master_fin_fetch: subi X21 X21 1")
    splitPageRankMS__updown_master.writeAction("addi X1 X30 0")
    splitPageRankMS__updown_master.writeAction("evlb X30 splitPageRankMS__lane_master_terminate")
    splitPageRankMS__updown_master.writeAction("sendr_wcont X30 X2 X16 X22")
    splitPageRankMS__updown_master.writeAction("blei X21 0 GenLinkableMapShuffleReduceEFA_yrlui_updown_master_fin_partition")
    splitPageRankMS__updown_master.writeAction("yield")
    splitPageRankMS__updown_master.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_updown_master_fin_partition: sendr_wret X31             splitPageRankMS__init_updown_master X19 X19 X28")
    splitPageRankMS__updown_master.writeAction("mov_imm2reg X19 0")
    splitPageRankMS__updown_master.writeAction("yield")

    ## splitPageRankMS__terminate_updown_master
    splitPageRankMS__terminate_updown_master = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__terminate_updown_master")
    splitPageRankMS__terminate_updown_master.writeAction("yield_terminate")

    ## splitPageRankMS__lane_master_init
    splitPageRankMS__lane_master_init = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__lane_master_init")
    splitPageRankMS__lane_master_init.writeAction("addi X1 X31 0")
    splitPageRankMS__lane_master_init.writeAction("send_dmlm_ld_wret X8 splitPageRankMS__lane_master_read_partition 2 X28")
    splitPageRankMS__lane_master_init.writeAction("movir X16 0")
    splitPageRankMS__lane_master_init.writeAction("movir X17 8")
    splitPageRankMS__lane_master_init.writeAction("mov_imm2reg X19 0")
    splitPageRankMS__lane_master_init.writeAction("addi X7 X22 640")
    splitPageRankMS__lane_master_init.writeAction("move X19 0(X22) 0 8")
    splitPageRankMS__lane_master_init.writeAction("addi X2 X28 0")
    splitPageRankMS__lane_master_init.writeAction("evlb X28 splitPageRankMS__lane_master_loop")
    splitPageRankMS__lane_master_init.writeAction("addi X7 X29 656")
    splitPageRankMS__lane_master_init.writeAction("move X28 0(X29) 0 8")
    splitPageRankMS__lane_master_init.writeAction("addi X2 X20 0")
    splitPageRankMS__lane_master_init.writeAction("evlb X20 splitPageRankMS__lane_master_get_next_return")
    splitPageRankMS__lane_master_init.writeAction("evi X2 X21 255 4")
    splitPageRankMS__lane_master_init.writeAction("evlb X21 splitPageRankMS__kv_map")
    splitPageRankMS__lane_master_init.writeAction("yield")

    ## splitPageRankMS__lane_master_loop
    splitPageRankMS__lane_master_loop = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__lane_master_loop")
    splitPageRankMS__lane_master_loop.writeAction("subi X16 X16 1")
    splitPageRankMS__lane_master_loop.writeAction("beqi X23 1 GenLinkableMapShuffleReduceEFA_yrlui_lane_master_loop_continue")
    splitPageRankMS__lane_master_loop.writeAction("bge X23 X24 GenLinkableMapShuffleReduceEFA_yrlui_lane_master_reach_end")
    splitPageRankMS__lane_master_loop.writeAction("movir X28 131072")
    splitPageRankMS__lane_master_loop.writeAction("muli X28 X28 4")
    splitPageRankMS__lane_master_loop.writeAction("add X23 X28 X28")
    splitPageRankMS__lane_master_loop.writeAction("sendr_wcont X20 X20 X28 X24")
    splitPageRankMS__lane_master_loop.writeAction("send_dmlm_ld X23 X21 8")
    splitPageRankMS__lane_master_loop.writeAction("addi X16 X16 1")
    splitPageRankMS__lane_master_loop.writeAction("movir X23 1")
    splitPageRankMS__lane_master_loop.writeAction("yield")
    splitPageRankMS__lane_master_loop.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_lane_master_reach_end: bgti X16 0 GenLinkableMapShuffleReduceEFA_yrlui_lane_master_loop_continue")
    splitPageRankMS__lane_master_loop.writeAction("movlr 0(X22) X19 0 8")
    splitPageRankMS__lane_master_loop.writeAction("sendr_wret X31 splitPageRankMS__lane_master_init X19 X19 X28")
    splitPageRankMS__lane_master_loop.writeAction("mov_imm2reg X19 0")
    splitPageRankMS__lane_master_loop.writeAction("movrl X19 0(X22) 0 8")
    splitPageRankMS__lane_master_loop.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_lane_master_loop_continue: yield")

    ## splitPageRankMS__lane_master_read_partition
    splitPageRankMS__lane_master_read_partition = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__lane_master_read_partition")
    splitPageRankMS__lane_master_read_partition.writeAction("bge X8 X9 GenLinkableMapShuffleReduceEFA_yrlui_lane_master_empty_partition")
    splitPageRankMS__lane_master_read_partition.writeAction("movir X28 131072")
    splitPageRankMS__lane_master_read_partition.writeAction("muli X28 X28 4")
    splitPageRankMS__lane_master_read_partition.writeAction("add X8 X28 X28")
    splitPageRankMS__lane_master_read_partition.writeAction("sendr_wcont X20 X20 X28 X9")
    splitPageRankMS__lane_master_read_partition.writeAction("send_dmlm_ld X8 X21 8")
    splitPageRankMS__lane_master_read_partition.writeAction("addi X16 X16 1")
    splitPageRankMS__lane_master_read_partition.writeAction("movir X23 1")
    splitPageRankMS__lane_master_read_partition.writeAction("yield")
    splitPageRankMS__lane_master_read_partition.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_lane_master_empty_partition: sendr_wret X31 splitPageRankMS__lane_master_init X19 X19 X28")
    splitPageRankMS__lane_master_read_partition.writeAction("yield")

    ## splitPageRankMS__lane_master_get_next_return
    splitPageRankMS__lane_master_get_next_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__lane_master_get_next_return")
    splitPageRankMS__lane_master_get_next_return.writeAction("bge X16 X17 GenLinkableMapShuffleReduceEFA_yrlui_lane_master_break_iterate_loop")
    splitPageRankMS__lane_master_get_next_return.writeAction("bge X8 X9 GenLinkableMapShuffleReduceEFA_yrlui_lane_master_break_iterate_loop")
    splitPageRankMS__lane_master_get_next_return.writeAction("movir X28 131072")
    splitPageRankMS__lane_master_get_next_return.writeAction("muli X28 X28 4")
    splitPageRankMS__lane_master_get_next_return.writeAction("add X8 X28 X28")
    splitPageRankMS__lane_master_get_next_return.writeAction("sendr_wcont X20 X20 X28 X9")
    splitPageRankMS__lane_master_get_next_return.writeAction("send_dmlm_ld X8 X21 8")
    splitPageRankMS__lane_master_get_next_return.writeAction("addi X16 X16 1")
    splitPageRankMS__lane_master_get_next_return.writeAction("yield")
    splitPageRankMS__lane_master_get_next_return.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_lane_master_break_iterate_loop: movir X23 0")
    splitPageRankMS__lane_master_get_next_return.writeAction("addi X8 X23 0")
    splitPageRankMS__lane_master_get_next_return.writeAction("addi X9 X24 0")
    splitPageRankMS__lane_master_get_next_return.writeAction("yield")
    splitPageRankMS__lane_master_get_next_return.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_lane_master_iterator_pass_end: subi X16 X16 1")
    splitPageRankMS__lane_master_get_next_return.writeAction("addi X8 X23 0")
    splitPageRankMS__lane_master_get_next_return.writeAction("addi X9 X24 0")
    splitPageRankMS__lane_master_get_next_return.writeAction("bgti X16 0 GenLinkableMapShuffleReduceEFA_yrlui_lane_master_loop_continue")
    splitPageRankMS__lane_master_get_next_return.writeAction("movlr 0(X22) X19 0 8")
    splitPageRankMS__lane_master_get_next_return.writeAction("sendr_wret X31 splitPageRankMS__lane_master_init X19 X19 X28")
    splitPageRankMS__lane_master_get_next_return.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_lane_master_loop_continue: yield")

    ## splitPageRankMS__lane_master_terminate
    splitPageRankMS__lane_master_terminate = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__lane_master_terminate")
    splitPageRankMS__lane_master_terminate.writeAction("yield_terminate")

    ## splitPageRankMS__init_global_snyc
    splitPageRankMS__init_global_snyc = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_global_snyc")
    splitPageRankMS__init_global_snyc.writeAction("sri X8 X16 11")
    splitPageRankMS__init_global_snyc.writeAction("movir X28 16384")
    splitPageRankMS__init_global_snyc.writeAction("bgt X16 X28 GenLinkableMapShuffleReduceEFA_yrlui_max_child_max_node")
    splitPageRankMS__init_global_snyc.writeAction("andi X8 X28 2047")
    splitPageRankMS__init_global_snyc.writeAction("beqi X28 0 GenLinkableMapShuffleReduceEFA_yrlui_max_node")
    splitPageRankMS__init_global_snyc.writeAction("addi X16 X16 1")
    splitPageRankMS__init_global_snyc.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_max_node")
    splitPageRankMS__init_global_snyc.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_child_max_node: mov_imm2reg X16 16384")
    splitPageRankMS__init_global_snyc.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_node: addi X16 X16 0")
    splitPageRankMS__init_global_snyc.writeAction("sri X8 X17 6")
    splitPageRankMS__init_global_snyc.writeAction("movir X28 32")
    splitPageRankMS__init_global_snyc.writeAction("bgt X17 X28 GenLinkableMapShuffleReduceEFA_yrlui_max_child_max_ud_per_nd")
    splitPageRankMS__init_global_snyc.writeAction("andi X8 X28 63")
    splitPageRankMS__init_global_snyc.writeAction("beqi X28 0 GenLinkableMapShuffleReduceEFA_yrlui_max_ud_per_nd")
    splitPageRankMS__init_global_snyc.writeAction("addi X17 X17 1")
    splitPageRankMS__init_global_snyc.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_max_ud_per_nd")
    splitPageRankMS__init_global_snyc.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_child_max_ud_per_nd: mov_imm2reg X17 32")
    splitPageRankMS__init_global_snyc.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_ud_per_nd: addi X17 X17 0")
    splitPageRankMS__init_global_snyc.writeAction("movir X18 64")
    splitPageRankMS__init_global_snyc.writeAction("bgt X8 X18 GenLinkableMapShuffleReduceEFA_yrlui_max_ln_per_ud")
    splitPageRankMS__init_global_snyc.writeAction("addi X8 X18 0")
    splitPageRankMS__init_global_snyc.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_max_ln_per_ud: addi X18 X18 0")
    splitPageRankMS__init_global_snyc.writeAction("mov_reg2reg X1 X19")
    splitPageRankMS__init_global_snyc.writeAction("mov_reg2reg X9 X21")
    splitPageRankMS__init_global_snyc.writeAction("evi X2 X30 255 4")
    splitPageRankMS__init_global_snyc.writeAction("evlb X30 splitPageRankMS__init_node_sync")
    splitPageRankMS__init_global_snyc.writeAction("mov_imm2reg X29 0")
    splitPageRankMS__init_global_snyc.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop: lshift X29 X28 11")
    splitPageRankMS__init_global_snyc.writeAction("add X0 X28 X28")
    splitPageRankMS__init_global_snyc.writeAction("ev X30 X30 X28 X28 8")
    splitPageRankMS__init_global_snyc.writeAction("sendr_wret X30 splitPageRankMS__global_sync_return X17 X18  X28")
    splitPageRankMS__init_global_snyc.writeAction("addi X29 X29 1")
    splitPageRankMS__init_global_snyc.writeAction("blt X29 X16 GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop")
    splitPageRankMS__init_global_snyc.writeAction("mov_imm2reg X20 0")
    splitPageRankMS__init_global_snyc.writeAction("mov_imm2reg X22 0")
    splitPageRankMS__init_global_snyc.writeAction("yield")

    ## splitPageRankMS__init_node_sync
    splitPageRankMS__init_node_sync = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_node_sync")
    splitPageRankMS__init_node_sync.writeAction("mov_reg2reg X8 X17")
    splitPageRankMS__init_node_sync.writeAction("evi X2 X30 255 4")
    splitPageRankMS__init_node_sync.writeAction("evlb X30 splitPageRankMS__ud_entry")
    splitPageRankMS__init_node_sync.writeAction("mov_imm2reg X29 0")
    splitPageRankMS__init_node_sync.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop: lshift X29 X28 6")
    splitPageRankMS__init_node_sync.writeAction("add X0 X28 X28")
    splitPageRankMS__init_node_sync.writeAction("ev X30 X30 X28 X28 8")
    splitPageRankMS__init_node_sync.writeAction("sendr_wret X30 splitPageRankMS__node_sync_return X9 EQT  X28")
    splitPageRankMS__init_node_sync.writeAction("addi X29 X29 1")
    splitPageRankMS__init_node_sync.writeAction("blt X29 X17 GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop")
    splitPageRankMS__init_node_sync.writeAction("mov_imm2reg X20 0")
    splitPageRankMS__init_node_sync.writeAction("mov_imm2reg X22 0")
    splitPageRankMS__init_node_sync.writeAction("mov_reg2reg X1 X19")
    splitPageRankMS__init_node_sync.writeAction("yield")

    ## splitPageRankMS__ud_accumulate
    splitPageRankMS__ud_accumulate = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__ud_accumulate")
    splitPageRankMS__ud_accumulate.writeAction("movir UDPR_0 64")
    splitPageRankMS__ud_accumulate.writeAction("mov_imm2reg UDPR_2 0")
    splitPageRankMS__ud_accumulate.writeAction("mov_imm2reg X22 0")
    splitPageRankMS__ud_accumulate.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_accumulate_loop: lshift UDPR_2 UDPR_1 16")
    splitPageRankMS__ud_accumulate.writeAction("add X10 UDPR_1 UDPR_1")
    splitPageRankMS__ud_accumulate.writeAction("addi UDPR_1 UDPR_1 648")
    splitPageRankMS__ud_accumulate.writeAction("move 0(UDPR_1) X28 0 8")
    splitPageRankMS__ud_accumulate.writeAction("add X28 X22 X22")
    splitPageRankMS__ud_accumulate.writeAction("addi UDPR_2 UDPR_2 1")
    splitPageRankMS__ud_accumulate.writeAction("blt UDPR_2 UDPR_0 GenLinkableMapShuffleReduceEFA_yrlui_accumulate_loop")
    splitPageRankMS__ud_accumulate.writeAction("sendr_reply X22 X22 X28")
    splitPageRankMS__ud_accumulate.writeAction("yield_terminate")

    ## splitPageRankMS__global_sync_return
    splitPageRankMS__global_sync_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__global_sync_return")
    splitPageRankMS__global_sync_return.writeAction("addi X20 X20 1")
    splitPageRankMS__global_sync_return.writeAction("add X8 X22 X22")
    splitPageRankMS__global_sync_return.writeAction("blt X20 X16 GenLinkableMapShuffleReduceEFA_yrlui_continue")
    splitPageRankMS__global_sync_return.writeAction("bge X22 X21 GenLinkableMapShuffleReduceEFA_yrlui_sync_finish")
    splitPageRankMS__global_sync_return.writeAction("mov_imm2reg X29 0")
    splitPageRankMS__global_sync_return.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop: lshift X29 X28 11")
    splitPageRankMS__global_sync_return.writeAction("add X0 X28 X28")
    splitPageRankMS__global_sync_return.writeAction("ev X30 X30 X28 X28 8")
    splitPageRankMS__global_sync_return.writeAction("sendr_wret X30 splitPageRankMS__global_sync_return X17 X18  X28")
    splitPageRankMS__global_sync_return.writeAction("addi X29 X29 1")
    splitPageRankMS__global_sync_return.writeAction("blt X29 X16 GenLinkableMapShuffleReduceEFA_yrlui_broadcast_loop")
    splitPageRankMS__global_sync_return.writeAction("mov_imm2reg X20 0")
    splitPageRankMS__global_sync_return.writeAction("mov_imm2reg X22 0")
    splitPageRankMS__global_sync_return.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_continue: yield")
    splitPageRankMS__global_sync_return.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_sync_finish: movir X30 -1")
    splitPageRankMS__global_sync_return.writeAction("sri X30 X30 1")
    splitPageRankMS__global_sync_return.writeAction("sendr_wcont X19 X30 X22 X22")
    splitPageRankMS__global_sync_return.writeAction("yield_terminate")

    ## splitPageRankMS__node_sync_return
    splitPageRankMS__node_sync_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__node_sync_return")
    splitPageRankMS__node_sync_return.writeAction("addi X20 X20 1")
    splitPageRankMS__node_sync_return.writeAction("add X8 X22 X22")
    splitPageRankMS__node_sync_return.writeAction("blt X20 X17 GenLinkableMapShuffleReduceEFA_yrlui_continue")
    splitPageRankMS__node_sync_return.writeAction("sendr_wcont X19 EQT X22 X22")
    splitPageRankMS__node_sync_return.writeAction("yield_terminate")
    splitPageRankMS__node_sync_return.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_continue: yield")

    ## splitPageRankMS__ud_entry
    splitPageRankMS__ud_entry = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__ud_entry")
    splitPageRankMS__ud_entry.writeAction("mov_imm2reg UDPR_5 10")
    splitPageRankMS__ud_entry.writeAction("evi X2 UDPR_8 255 4")
    splitPageRankMS__ud_entry.writeAction("evlb UDPR_8 splitPageRankMS__ud_delay")
    splitPageRankMS__ud_entry.writeAction("movir UDPR_2 6")
    splitPageRankMS__ud_entry.writeAction("sli UDPR_2 UDPR_2 27")
    splitPageRankMS__ud_entry.writeAction("or X0 UDPR_2 UDPR_2")
    splitPageRankMS__ud_entry.writeAction("ev UDPR_8 UDPR_8 UDPR_2 UDPR_2 8")
    splitPageRankMS__ud_entry.writeAction("sendr3_wcont UDPR_8 X1 UDPR_5 UDPR_8 X7")
    splitPageRankMS__ud_entry.writeAction("yieldt")

    ## splitPageRankMS__ud_delay
    splitPageRankMS__ud_delay = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__ud_delay")
    splitPageRankMS__ud_delay.writeAction("beqi X8 0 GenLinkableMapShuffleReduceEFA_yrlui_ud_loop_term")
    splitPageRankMS__ud_delay.writeAction("subi X8 UDPR_5 1")
    splitPageRankMS__ud_delay.writeAction("sendr3_wcont X9 X1 UDPR_5 X9 X10")
    splitPageRankMS__ud_delay.writeAction("yieldt")
    splitPageRankMS__ud_delay.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_ud_loop_term: movir UDPR_2 1")
    splitPageRankMS__ud_delay.writeAction("sli UDPR_2 UDPR_2 27")
    splitPageRankMS__ud_delay.writeAction("or X0 UDPR_2 UDPR_2")
    splitPageRankMS__ud_delay.writeAction("evi X2 UDPR_8 255 4")
    splitPageRankMS__ud_delay.writeAction("evlb UDPR_8 splitPageRankMS__ud_accumulate")
    splitPageRankMS__ud_delay.writeAction("ev UDPR_8 UDPR_8 UDPR_2 UDPR_2 8")
    splitPageRankMS__ud_delay.writeAction("sendr3_wcont UDPR_8 X1 X8 X9 X10")
    splitPageRankMS__ud_delay.writeAction("yieldt")

    ## splitPageRankMS__kv_map_emit
    splitPageRankMS__kv_map_emit = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__kv_map_emit")
    splitPageRankMS__kv_map_emit.writeAction("addi X7 X25 640")
    splitPageRankMS__kv_map_emit.writeAction("movlr 40(X25) X23 0 8")
    splitPageRankMS__kv_map_emit.writeAction("movlr 56(X25) X26 0 8")
    splitPageRankMS__kv_map_emit.writeAction("movir X24 0")
    splitPageRankMS__kv_map_emit.writeAction("hash X8 X24")
    splitPageRankMS__kv_map_emit.writeAction("and X24 X23 X24")
    splitPageRankMS__kv_map_emit.writeAction("add X24 X26 X24")
    splitPageRankMS__kv_map_emit.writeAction("evi X2 X30 255 4")
    splitPageRankMS__kv_map_emit.writeAction("evlb X30 splitPageRankMS__init_reduce_thread")
    splitPageRankMS__kv_map_emit.writeAction("evi X2 X27 255 4")
    splitPageRankMS__kv_map_emit.writeAction("evlb X27 splitPageRankMS__kv_reduce_return")
    splitPageRankMS__kv_map_emit.writeAction("ev X30  X30  X24 X24 8")
    splitPageRankMS__kv_map_emit.writeAction("sendops_wcont X30 X27 X8 2")
    splitPageRankMS__kv_map_emit.writeAction("move 0(X25) X29  0 8")
    splitPageRankMS__kv_map_emit.writeAction("addi X29 X29 1")
    splitPageRankMS__kv_map_emit.writeAction("move X29 0(X25) 0 8")
    splitPageRankMS__kv_map_emit.writeAction("yield_terminate")

    ## splitPageRankMS__kv_reduce_emit
    splitPageRankMS__kv_reduce_emit = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__kv_reduce_emit")
    splitPageRankMS__kv_reduce_emit.writeAction("movir X16 704")
    splitPageRankMS__kv_reduce_emit.writeAction("add X16 X7 X16")
    splitPageRankMS__kv_reduce_emit.writeAction("movlr 832(X7) X28 0 8")
    splitPageRankMS__kv_reduce_emit.writeAction("lshift X8 X29 3")
    splitPageRankMS__kv_reduce_emit.writeAction("add X29 X28 X28")
    splitPageRankMS__kv_reduce_emit.writeAction("addi X2 X29 0")
    splitPageRankMS__kv_reduce_emit.writeAction("evlb X29 splitPageRankMS_output__put_pair_sync")
    splitPageRankMS__kv_reduce_emit.writeAction("addi X28 X16 0")
    splitPageRankMS__kv_reduce_emit.writeAction("sendr_dmlm X16 X29 X9")
    splitPageRankMS__kv_reduce_emit.writeAction("movir X29 1")
    splitPageRankMS__kv_reduce_emit.writeAction("yieldt")

    ## splitPageRankMS_output__put_pair_sync
    splitPageRankMS_output__put_pair_sync = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS_output__put_pair_sync")
    splitPageRankMS_output__put_pair_sync.writeAction("subi X29 X29 1")
    splitPageRankMS_output__put_pair_sync.writeAction("bnei X29 0 GenLinkableMapShuffleReduceEFA_yrlui_continue")
    splitPageRankMS_output__put_pair_sync.writeAction("sendr_wcont X1 X1 X8 X29")
    splitPageRankMS_output__put_pair_sync.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_continue: yield")

    ## splitPageRankMS__kv_map_return
    splitPageRankMS__kv_map_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__kv_map_return")
    splitPageRankMS__kv_map_return.writeAction("addi X7 X16 656")
    splitPageRankMS__kv_map_return.writeAction("move 0(X16) X29 0 8")
    splitPageRankMS__kv_map_return.writeAction("sendops_wcont X29 X2 X8 2")
    splitPageRankMS__kv_map_return.writeAction("yieldt")

    ## splitPageRankMS__init_reduce_thread
    splitPageRankMS__init_reduce_thread = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__init_reduce_thread")
    splitPageRankMS__init_reduce_thread.writeAction("andi X8 X21 2047")
    splitPageRankMS__init_reduce_thread.writeAction("sli X21 X16 4")
    splitPageRankMS__init_reduce_thread.writeAction("add X7 X16 X16")
    splitPageRankMS__init_reduce_thread.writeAction("addi X16 X16 1600")
    splitPageRankMS__init_reduce_thread.writeAction("movlr 0(X16) X17 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("beq X17 X8 GenLinkableMapShuffleReduceEFA_yrlui_cache_hit")
    splitPageRankMS__init_reduce_thread.writeAction("movir X21 1")
    splitPageRankMS__init_reduce_thread.writeAction("sli X21 X21 63")
    splitPageRankMS__init_reduce_thread.writeAction("or X21 X8 X25")
    splitPageRankMS__init_reduce_thread.writeAction("beq X25 X17 GenLinkableMapShuffleReduceEFA_yrlui_cache_hit")
    splitPageRankMS__init_reduce_thread.writeAction("rshift X17 X24 63")
    splitPageRankMS__init_reduce_thread.writeAction("beqi X24 1 GenLinkableMapShuffleReduceEFA_yrlui_cache_evict")
    splitPageRankMS__init_reduce_thread.writeAction("beqi X17 -1 GenLinkableMapShuffleReduceEFA_yrlui_cache_evict")
    splitPageRankMS__init_reduce_thread.writeAction("evi X2 X24 255 4")
    splitPageRankMS__init_reduce_thread.writeAction("sendops_wcont X24 X1 X8 2")
    splitPageRankMS__init_reduce_thread.writeAction("yieldt")
    splitPageRankMS__init_reduce_thread.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_cache_hit: move 8(X16) X22 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("fadd.64 X9 X22 X22")
    splitPageRankMS__init_reduce_thread.writeAction("movrl X22 8(X16) 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("sendr_wcont X1 X2 X8 X17 ")
    splitPageRankMS__init_reduce_thread.writeAction("addi X7 X18 640")
    splitPageRankMS__init_reduce_thread.writeAction("move 8(X18) X24 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("addi X24 X24 1")
    splitPageRankMS__init_reduce_thread.writeAction("move X24 8(X18) 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("yieldt")
    splitPageRankMS__init_reduce_thread.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_cache_evict: addi X7 X18 640")
    splitPageRankMS__init_reduce_thread.writeAction("move 24(X18) X24 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("move 32(X18) X25 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("bgt X25 X24 GenLinkableMapShuffleReduceEFA_yrlui_thread_available")
    splitPageRankMS__init_reduce_thread.writeAction("evi X2 X24 255 4")
    splitPageRankMS__init_reduce_thread.writeAction("sendops_wcont X24 X1 X8 2")
    splitPageRankMS__init_reduce_thread.writeAction("yieldt")
    splitPageRankMS__init_reduce_thread.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_thread_available: addi X24 X24 1")
    splitPageRankMS__init_reduce_thread.writeAction("move X24  24(X18) 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("movrl X8 0(X16) 1 8")
    splitPageRankMS__init_reduce_thread.writeAction("movir X19 0")
    splitPageRankMS__init_reduce_thread.writeAction("beqi X17 -1 GenLinkableMapShuffleReduceEFA_yrlui_skip_flush")
    splitPageRankMS__init_reduce_thread.writeAction("sub X17 X21 X17")
    splitPageRankMS__init_reduce_thread.writeAction("addi X16 X22 0")
    splitPageRankMS__init_reduce_thread.writeAction("addi X7 X18 704")
    splitPageRankMS__init_reduce_thread.writeAction("addi X2 X21 0")
    splitPageRankMS__init_reduce_thread.writeAction("evlb X21 splitPageRankMS__combine_put_pair_ack")
    splitPageRankMS__init_reduce_thread.writeAction("movlr 832(X7) X24 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("lshift X17 X25 3")
    splitPageRankMS__init_reduce_thread.writeAction("add X25 X24 X24")
    splitPageRankMS__init_reduce_thread.writeAction("addi X24 X25 0")
    splitPageRankMS__init_reduce_thread.writeAction("send_dmlm X25 X21 X22 1")
    splitPageRankMS__init_reduce_thread.writeAction("addi X22 X22 8")
    splitPageRankMS__init_reduce_thread.writeAction("addi X19 X19 1")
    splitPageRankMS__init_reduce_thread.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_skip_flush: addi X2 X21 0")
    splitPageRankMS__init_reduce_thread.writeAction("evlb X21 splitPageRankMS__combine_get_pair")
    splitPageRankMS__init_reduce_thread.writeAction("move 832(X7) X24 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("lshift X8 X25 3")
    splitPageRankMS__init_reduce_thread.writeAction("add X25 X24 X24")
    splitPageRankMS__init_reduce_thread.writeAction("send_dmlm_ld X24 X21 1")
    splitPageRankMS__init_reduce_thread.writeAction("move X9 0(X16) 0 8")
    splitPageRankMS__init_reduce_thread.writeAction("addi X8 X17 0")
    splitPageRankMS__init_reduce_thread.writeAction("addi X1 X20 0")
    splitPageRankMS__init_reduce_thread.writeAction("addi X19 X19 1")
    splitPageRankMS__init_reduce_thread.writeAction("yield")

    ## splitPageRankMS__combine_get_pair
    splitPageRankMS__combine_get_pair = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__combine_get_pair")
    splitPageRankMS__combine_get_pair.writeAction("move 0(X16) X22 0 8")
    splitPageRankMS__combine_get_pair.writeAction("fadd.64 X22 X8 X22")
    splitPageRankMS__combine_get_pair.writeAction("move X22 0(X16) 0 8")
    splitPageRankMS__combine_get_pair.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_get_fail: subi X19 X19 1")
    splitPageRankMS__combine_get_pair.writeAction("bnei X19 0 GenLinkableMapShuffleReduceEFA_yrlui_contiue")
    splitPageRankMS__combine_get_pair.writeAction("movir X21 1")
    splitPageRankMS__combine_get_pair.writeAction("sli X21 X21 63")
    splitPageRankMS__combine_get_pair.writeAction("or X21 X17 X17")
    splitPageRankMS__combine_get_pair.writeAction("movrl X17 -8(X16) 0 8")
    splitPageRankMS__combine_get_pair.writeAction("sendr_wcont X20 X2 X2 X17 ")
    splitPageRankMS__combine_get_pair.writeAction("addi X7 X18 640")
    splitPageRankMS__combine_get_pair.writeAction("move 24(X18) X24  0 8")
    splitPageRankMS__combine_get_pair.writeAction("subi X24 X24 1")
    splitPageRankMS__combine_get_pair.writeAction("move X24  24(X18) 0 8")
    splitPageRankMS__combine_get_pair.writeAction("move 8(X18) X24 0 8")
    splitPageRankMS__combine_get_pair.writeAction("addi X24 X24 1")
    splitPageRankMS__combine_get_pair.writeAction("move X24 8(X18) 0 8")
    splitPageRankMS__combine_get_pair.writeAction("yieldt")
    splitPageRankMS__combine_get_pair.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_contiue: yield")

    ## splitPageRankMS__combine_put_pair_ack
    splitPageRankMS__combine_put_pair_ack = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__combine_put_pair_ack")
    splitPageRankMS__combine_put_pair_ack.writeAction("subi X19 X19 1")
    splitPageRankMS__combine_put_pair_ack.writeAction("bnei X19 0 GenLinkableMapShuffleReduceEFA_yrlui_contiue")
    splitPageRankMS__combine_put_pair_ack.writeAction("movir X21 1")
    splitPageRankMS__combine_put_pair_ack.writeAction("sli X21 X21 63")
    splitPageRankMS__combine_put_pair_ack.writeAction("or X21 X17 X17")
    splitPageRankMS__combine_put_pair_ack.writeAction("movrl X17 -8(X16) 0 8")
    splitPageRankMS__combine_put_pair_ack.writeAction("sendr_wcont X20 X2 X2 X17 ")
    splitPageRankMS__combine_put_pair_ack.writeAction("addi X7 X18 640")
    splitPageRankMS__combine_put_pair_ack.writeAction("move 24(X18) X24  0 8")
    splitPageRankMS__combine_put_pair_ack.writeAction("subi X24 X24 1")
    splitPageRankMS__combine_put_pair_ack.writeAction("move X24  24(X18) 0 8")
    splitPageRankMS__combine_put_pair_ack.writeAction("move 8(X18) X24 0 8")
    splitPageRankMS__combine_put_pair_ack.writeAction("addi X24 X24 1")
    splitPageRankMS__combine_put_pair_ack.writeAction("move X24 8(X18) 0 8")
    splitPageRankMS__combine_put_pair_ack.writeAction("yieldt")
    splitPageRankMS__combine_put_pair_ack.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_contiue: yield")

    ## splitPageRankMS__kv_reduce_return
    splitPageRankMS__kv_reduce_return = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__kv_reduce_return")
    splitPageRankMS__kv_reduce_return.writeAction("yieldt")

    ## splitPageRankMS__combine_flush_lane
    splitPageRankMS__combine_flush_lane = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__combine_flush_lane")
    splitPageRankMS__combine_flush_lane.writeAction("addi X1 X17 0")
    splitPageRankMS__combine_flush_lane.writeAction("addi X7 X20 1600")
    splitPageRankMS__combine_flush_lane.writeAction("movir X16 2048")
    splitPageRankMS__combine_flush_lane.writeAction("sli X16 X16 4")
    splitPageRankMS__combine_flush_lane.writeAction("add X16 X20 X16")
    splitPageRankMS__combine_flush_lane.writeAction("movir X19 0")
    splitPageRankMS__combine_flush_lane.writeAction("movir X22 -1")
    splitPageRankMS__combine_flush_lane.writeAction("addi X2 X23 0")
    splitPageRankMS__combine_flush_lane.writeAction("evlb X23 splitPageRankMS__combine_flush_ack")
    splitPageRankMS__combine_flush_lane.writeAction("addi X7 X18 704")
    splitPageRankMS__combine_flush_lane.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_flush_loop: bge X20 X16 GenLinkableMapShuffleReduceEFA_yrlui_break_flush_loop")
    splitPageRankMS__combine_flush_lane.writeAction("movlr 0(X20) X21 0 8")
    splitPageRankMS__combine_flush_lane.writeAction("beq X21 X22 GenLinkableMapShuffleReduceEFA_yrlui_continue_flush_loop")
    splitPageRankMS__combine_flush_lane.writeAction("sli X21 X21 1")
    splitPageRankMS__combine_flush_lane.writeAction("sri X21 X21 1")
    splitPageRankMS__combine_flush_lane.writeAction("addi X20 X20 8")
    splitPageRankMS__combine_flush_lane.writeAction("movlr 832(X7) X24 0 8")
    splitPageRankMS__combine_flush_lane.writeAction("lshift X21 X25 3")
    splitPageRankMS__combine_flush_lane.writeAction("add X25 X24 X24")
    splitPageRankMS__combine_flush_lane.writeAction("addi X24 X25 0")
    splitPageRankMS__combine_flush_lane.writeAction("send_dmlm X25 X23 X20 1")
    splitPageRankMS__combine_flush_lane.writeAction("addi X20 X20 8")
    splitPageRankMS__combine_flush_lane.writeAction("addi X19 X19 1")
    splitPageRankMS__combine_flush_lane.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_flush_loop")
    splitPageRankMS__combine_flush_lane.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_continue_flush_loop: addi X20 X20 16")
    splitPageRankMS__combine_flush_lane.writeAction("jmp GenLinkableMapShuffleReduceEFA_yrlui_flush_loop")
    splitPageRankMS__combine_flush_lane.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_break_flush_loop: beqi X19 0 GenLinkableMapShuffleReduceEFA_yrlui_empty_cache")
    splitPageRankMS__combine_flush_lane.writeAction("yield")
    splitPageRankMS__combine_flush_lane.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_empty_cache: movir X21 -1")
    splitPageRankMS__combine_flush_lane.writeAction("sri X21 X21 1")
    splitPageRankMS__combine_flush_lane.writeAction("sendr_wcont X17 X21 X2 X16 ")
    splitPageRankMS__combine_flush_lane.writeAction("yieldt")

    ## splitPageRankMS__combine_flush_ack
    splitPageRankMS__combine_flush_ack = init_null_state.writeTransition("eventCarry", init_null_state, init_null_state, "splitPageRankMS__combine_flush_ack")
    splitPageRankMS__combine_flush_ack.writeAction("subi X19 X19 1")
    splitPageRankMS__combine_flush_ack.writeAction("bnei X19 0 GenLinkableMapShuffleReduceEFA_yrlui_continue_flush_loop")
    splitPageRankMS__combine_flush_ack.writeAction("movir X21 -1")
    splitPageRankMS__combine_flush_ack.writeAction("sri X21 X21 1")
    splitPageRankMS__combine_flush_ack.writeAction("sendr_wcont X17 X21 X2 X16 ")
    splitPageRankMS__combine_flush_ack.writeAction("yieldt")
    splitPageRankMS__combine_flush_ack.writeAction("GenLinkableMapShuffleReduceEFA_yrlui_continue_flush_loop: yield")