from linker.EFAProgram import efaProgram

## UDWeave version: unknown

## Global constants

@efaProgram
def EFA_vertex_fliter_master(efa):
  efa.code_level = 'machine'
  state0 = efa.State("udweave_init") #Only one state code 
  efa.add_initId(state0.state_id)
  ## Static declarations
  ## Scoped Variable "lmbuff" uses Register X16, scope (0)
  ## Scoped Variable "count" uses Register X17, scope (0)
  ## Scoped Variable "deg" uses Register X18, scope (0)
  ## Scoped Variable "new_offset" uses Register X19, scope (0)
  ## Scoped Variable "deleted_edges" uses Register X20, scope (0)
  ## Scoped Variable "total_edges" uses Register X21, scope (0)
  ## Scoped Variable "nl_ptr_end" uses Register X22, scope (0)
  ## Scoped Variable "read_nl_ptr" uses Register X23, scope (0)
  ## Scoped Variable "write_nl_ptr" uses Register X24, scope (0)
  ## Scoped Variable "read_count_ptr" uses Register X25, scope (0)
  ## Scoped Variable "k" uses Register X26, scope (0)
  ## This is all metadata information
  ## #define DEBUG
  ## This is all metadata information
  ## Each threads in the same lane shared the following scratchpad
  ## #define TOP_TC_OUTPUT 1
  ## send buffer 4 - 13 (9 words)
  ## #define NUM_WRITE 16
  ## #define NUM_INT 18
  ## master, intersection launcher offsets
  ## Each thread's own private scratchpad size: [(THREAD_STATUS << 3) + TID * THREAD_LM_SIZE, (THREAD_STATUS << 3) + (TID+1) * THREAD_LM_SIZE]
  
  ##########################################################
  ###### Writing code for thread vertex_filter_master ######
  ##########################################################
  # Writing code for event vertex_filter_master::launch
  tranvertex_filter_master__launch = efa.writeEvent('vertex_filter_master::launch')
  ## #ifdef DEBUG

  ## print("[DEBUG][NWID %lu] <vertex_filter_master__launch> inputs g_v:%lu, offset_id:%lu", NETID, _g_v, offset_idx);

  ## #endif

  tranvertex_filter_master__launch.writeAction(f"__entry: send_dmlm_ld_wret X9 vertex_filter_master::receive_dram 1 X27") 
  ##         // Fetch V1 8 bytes from g_v[v1]

  ##         long *v_ptr = _g_v + (_v1 << 6);

  ##         lmbuff[V_PTR] = v_ptr;

  ## #ifdef DEBUG        

  ##         print("[DEBUG][NWID %lu] Fetching v1:0x%lX", NETID, v_ptr);

  ## #endif

  ## 		send_dram_read(v_ptr, 6, v1_return);

  tranvertex_filter_master__launch.writeAction(f"movir X27 2000") 
  tranvertex_filter_master__launch.writeAction(f"muli X11 X28 200") 
  tranvertex_filter_master__launch.writeAction(f"add X28 X27 X28") 
  tranvertex_filter_master__launch.writeAction(f"add X7 X28 X16") 
  tranvertex_filter_master__launch.writeAction(f"movrl X1 48(X16) 0 8") 
  tranvertex_filter_master__launch.writeAction(f"movrl X8 56(X16) 0 8") 
  tranvertex_filter_master__launch.writeAction(f"movrl X11 192(X16) 0 8") 
  tranvertex_filter_master__launch.writeAction(f"movir X18 0") 
  tranvertex_filter_master__launch.writeAction(f"movir X17 1") 
  tranvertex_filter_master__launch.writeAction(f"movir X20 0") 
  tranvertex_filter_master__launch.writeAction(f"movir X21 0") 
  tranvertex_filter_master__launch.writeAction(f"addi X10 X26 0") 
  tranvertex_filter_master__launch.writeAction(f"movir X19 0") 
  tranvertex_filter_master__launch.writeAction(f"yield") 
  
  # Writing code for event vertex_filter_master::receive_dram
  tranvertex_filter_master__receive_dram = efa.writeEvent('vertex_filter_master::receive_dram')
  tranvertex_filter_master__receive_dram.writeAction(f"__entry: movlr 56(X16) X28 0 8") 
  tranvertex_filter_master__receive_dram.writeAction(f"sli X8 X27 6") 
  tranvertex_filter_master__receive_dram.writeAction(f"add X28 X27 X28") 
  tranvertex_filter_master__receive_dram.writeAction(f"movrl X28 56(X16) 0 8") 
  tranvertex_filter_master__receive_dram.writeAction(f"send_dmlm_ld_wret X28 vertex_filter_master::v1_return 6 X27") 
  tranvertex_filter_master__receive_dram.writeAction(f"yield") 
  
  # Writing code for event vertex_filter_master::v1_return
  tranvertex_filter_master__v1_return = efa.writeEvent('vertex_filter_master::v1_return')
  ##deg, id, neigh,

  ## send_event(lmbuff[CONT], deleted_edges, op0, lmbuff[VID], IGNRCONT);

  ## yield_terminate;

  tranvertex_filter_master__v1_return.writeAction(f"__entry: add X21 X8 X21") 
  tranvertex_filter_master__v1_return.writeAction(f"bneiu X8 0 __if_v1_return_2_post") 
  ## thread can be returned to master_launcher 

  tranvertex_filter_master__v1_return.writeAction(f"__if_v1_return_0_true: addi X7 X28 32") 
  tranvertex_filter_master__v1_return.writeAction(f"movrl X20 0(X28) 0 8") 
  tranvertex_filter_master__v1_return.writeAction(f"movrl X18 8(X28) 0 8") 
  tranvertex_filter_master__v1_return.writeAction(f"movrl X9 16(X28) 0 8") 
  tranvertex_filter_master__v1_return.writeAction(f"movlr 192(X16) X27 0 8") 
  tranvertex_filter_master__v1_return.writeAction(f"movrl X27 24(X28) 0 8") 
  tranvertex_filter_master__v1_return.writeAction(f"movrl X21 32(X28) 0 8") 
  tranvertex_filter_master__v1_return.writeAction(f"movlr 48(X16) X27 0 8") 
  tranvertex_filter_master__v1_return.writeAction(f"movir X29 -1") 
  tranvertex_filter_master__v1_return.writeAction(f"sri X29 X29 1") 
  tranvertex_filter_master__v1_return.writeAction(f"send_wcont X27 X29 X28 5") 
  ## #ifdef DEBUG        

  ## print("[DEBUG][NWID :%lu]Terminate v:%lu because vertex deg:%lu", NETID, op1, op0);

  ## #endif

  tranvertex_filter_master__v1_return.writeAction(f"yield_terminate") 
  ## Vertex needs to be counted

  tranvertex_filter_master__v1_return.writeAction(f"__if_v1_return_2_post: addi X10 X23 0") 
  tranvertex_filter_master__v1_return.writeAction(f"addi X10 X24 0") 
  tranvertex_filter_master__v1_return.writeAction(f"addi X11 X25 0") 
  tranvertex_filter_master__v1_return.writeAction(f"sli X8 X28 3") 
  tranvertex_filter_master__v1_return.writeAction(f"add X10 X28 X22") 
  tranvertex_filter_master__v1_return.writeAction(f"bleu X22 X23 __if_v1_return_5_post") 
  tranvertex_filter_master__v1_return.writeAction(f"__if_v1_return_3_true: send_dmlm_ld_wret X25 vertex_filter_master::v1_neighs_count 8 X28") 
  ## send_dram_read(read_nl_ptr, 8, v1_neighs);

  tranvertex_filter_master__v1_return.writeAction(f"__if_v1_return_5_post: movir X28 6") 
  tranvertex_filter_master__v1_return.writeAction(f"bcpyol X8 X16 X28") 
  tranvertex_filter_master__v1_return.writeAction(f"yield") 
  
  # Writing code for event vertex_filter_master::v1_neighs_count
  tranvertex_filter_master__v1_neighs_count = efa.writeEvent('vertex_filter_master::v1_neighs_count')
  tranvertex_filter_master__v1_neighs_count.writeAction(f"__entry: addi X16 X28 64") 
  tranvertex_filter_master__v1_neighs_count.writeAction(f"movir X27 8") 
  tranvertex_filter_master__v1_neighs_count.writeAction(f"bcpyol X8 X28 X27") 
  tranvertex_filter_master__v1_neighs_count.writeAction(f"addi X25 X25 64") 
  tranvertex_filter_master__v1_neighs_count.writeAction(f"send_dmlm_ld_wret X23 vertex_filter_master::v1_neighs 8 X28") 
  tranvertex_filter_master__v1_neighs_count.writeAction(f"yield") 
  
  # Writing code for event vertex_filter_master::v1_neighs
  tranvertex_filter_master__v1_neighs = efa.writeEvent('vertex_filter_master::v1_neighs')
  ## Update the return count

  tranvertex_filter_master__v1_neighs.writeAction(f"__entry: addi X16 X28 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X16 X27 128") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bleu X22 X23 __if_v1_neighs_1_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_0_true: addi X8 X29 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 0(X28) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X30 __if_v1_neighs_4_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_3_true: movwrl X29 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X29 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_8_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_6_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_8_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_11_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_9_true: movrl X29 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_11_post: jmp __if_v1_neighs_5_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_4_false: add X20 X30 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_5_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_2_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_1_false: bleiu X19 0 __if_v1_neighs_14_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_12_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_14_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X30 vertex_filter_master::write_return X16 6 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X29 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X30 X29 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_15_condition: bleu X29 X30 __while_v1_neighs_17_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_16_body: send_dmlm_wret X30 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X30 X30 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_15_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_17_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_2_post: bleu X22 X23 __if_v1_neighs_19_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_18_true: addi X9 X30 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 8(X28) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X29 __if_v1_neighs_22_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_21_true: movwrl X30 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X30 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_26_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_24_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_26_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_29_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_27_true: movrl X30 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_29_post: jmp __if_v1_neighs_23_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_22_false: add X20 X29 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_23_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_20_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_19_false: bleiu X19 0 __if_v1_neighs_32_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_30_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_32_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X29 vertex_filter_master::write_return X16 6 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X30 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X29 X30 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_33_condition: bleu X30 X29 __while_v1_neighs_35_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_34_body: send_dmlm_wret X29 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X29 X29 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_33_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_35_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_20_post: bleu X22 X23 __if_v1_neighs_37_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_36_true: addi X10 X30 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 16(X28) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X29 __if_v1_neighs_40_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_39_true: movwrl X30 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X30 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_44_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_42_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_44_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_47_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_45_true: movrl X30 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_47_post: jmp __if_v1_neighs_41_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_40_false: add X20 X29 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_41_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_38_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_37_false: bleiu X19 0 __if_v1_neighs_50_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_48_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_50_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X29 vertex_filter_master::write_return X16 6 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X30 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X29 X30 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_51_condition: bleu X30 X29 __while_v1_neighs_53_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_52_body: send_dmlm_wret X29 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X29 X29 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_51_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_53_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_38_post: bleu X22 X23 __if_v1_neighs_55_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_54_true: addi X11 X29 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X28) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X30 __if_v1_neighs_58_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_57_true: movwrl X29 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X29 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_62_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_60_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_62_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_65_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_63_true: movrl X29 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_65_post: jmp __if_v1_neighs_59_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_58_false: add X20 X30 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_59_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_56_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_55_false: bleiu X19 0 __if_v1_neighs_68_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_66_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_68_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X30 vertex_filter_master::write_return X16 6 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X29 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X30 X29 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_69_condition: bleu X29 X30 __while_v1_neighs_71_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_70_body: send_dmlm_wret X30 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X30 X30 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_69_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_71_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_56_post: bleu X22 X23 __if_v1_neighs_73_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_72_true: addi X12 X30 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 32(X28) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X29 __if_v1_neighs_76_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_75_true: movwrl X30 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X30 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_80_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_78_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_80_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_83_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_81_true: movrl X30 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_83_post: jmp __if_v1_neighs_77_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_76_false: add X20 X29 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_77_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_74_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_73_false: bleiu X19 0 __if_v1_neighs_86_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_84_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_86_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X30 vertex_filter_master::write_return X16 6 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X29 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X30 X29 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_87_condition: bleu X29 X30 __while_v1_neighs_89_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_88_body: send_dmlm_wret X30 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X30 X30 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_87_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_89_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_74_post: bleu X22 X23 __if_v1_neighs_91_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_90_true: addi X13 X30 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 40(X28) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X29 __if_v1_neighs_94_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_93_true: movwrl X30 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X30 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_98_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_96_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_98_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_101_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_99_true: movrl X30 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_101_post: jmp __if_v1_neighs_95_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_94_false: add X20 X29 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_95_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_92_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_91_false: bleiu X19 0 __if_v1_neighs_104_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_102_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_104_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X29 vertex_filter_master::write_return X16 6 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X30 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X29 X30 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_105_condition: bleu X30 X29 __while_v1_neighs_107_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_106_body: send_dmlm_wret X29 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X29 X29 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_105_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_107_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_92_post: bleu X22 X23 __if_v1_neighs_109_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_108_true: addi X14 X30 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 48(X28) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X29 __if_v1_neighs_112_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_111_true: movwrl X30 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X30 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_116_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_114_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_116_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_119_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_117_true: movrl X30 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_119_post: jmp __if_v1_neighs_113_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_112_false: add X20 X29 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_113_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_110_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_109_false: bleiu X19 0 __if_v1_neighs_122_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_120_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_122_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X29 vertex_filter_master::write_return X16 6 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X30 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X29 X30 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_123_condition: bleu X30 X29 __while_v1_neighs_125_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_124_body: send_dmlm_wret X29 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X29 X29 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_123_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_125_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_110_post: bleu X22 X23 __if_v1_neighs_127_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_126_true: addi X15 X29 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X28) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bgt X26 X30 __if_v1_neighs_130_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_129_true: movwrl X29 X27(X19,0,0)") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X19 X19 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movrl X29 40(X16) 0 8") 
  ## updated_edges = updated_edges + 1;

  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X19 8 __if_v1_neighs_134_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_132_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movir X19 0") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X24 X24 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_134_post: addi X18 X18 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"bneiu X18 1 __if_v1_neighs_137_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_135_true: movrl X29 32(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_137_post: jmp __if_v1_neighs_131_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_130_false: add X20 X30 X20") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_131_post: addi X23 X23 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_128_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_127_false: bleiu X19 0 __if_v1_neighs_140_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_138_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_140_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X30 vertex_filter_master::write_return X16 6 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X30 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X29 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X30 X29 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_141_condition: bleu X29 X30 __while_v1_neighs_143_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_142_body: send_dmlm_wret X30 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X30 X30 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_141_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_143_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_128_post: bleu X22 X23 __if_v1_neighs_145_false") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_144_true: send_dmlm_ld_wret X25 vertex_filter_master::v1_neighs_count 8 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __if_v1_neighs_146_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_145_false: bleiu X19 0 __if_v1_neighs_149_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_147_true: send_dmlm_wret X24 vertex_filter_master::write_return X27 8 X29") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_149_post: movrl X18 0(X16) 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 56(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"send_dmlm_wret X29 vertex_filter_master::write_return X16 6 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X7 X28 15920") 
  tranvertex_filter_master__v1_neighs.writeAction(f"movlr 24(X16) X29 0 8") 
  tranvertex_filter_master__v1_neighs.writeAction(f"sli X18 X30 3") 
  tranvertex_filter_master__v1_neighs.writeAction(f"add X29 X30 X30") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_150_condition: bleu X30 X29 __while_v1_neighs_152_post") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_151_body: send_dmlm_wret X29 vertex_filter_master::write_return X28 8 X31") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X17 X17 1") 
  tranvertex_filter_master__v1_neighs.writeAction(f"addi X29 X29 64") 
  tranvertex_filter_master__v1_neighs.writeAction(f"jmp __while_v1_neighs_150_condition") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__while_v1_neighs_152_post: yield") 
  tranvertex_filter_master__v1_neighs.writeAction(f"__if_v1_neighs_146_post: yield") 
  
  # Writing code for event vertex_filter_master::write_return
  tranvertex_filter_master__write_return = efa.writeEvent('vertex_filter_master::write_return')
  tranvertex_filter_master__write_return.writeAction(f"__entry: subi X17 X17 1") 
  tranvertex_filter_master__write_return.writeAction(f"bneiu X17 0 __if_write_return_2_post") 
  tranvertex_filter_master__write_return.writeAction(f"__if_write_return_0_true: addi X7 X28 32") 
  tranvertex_filter_master__write_return.writeAction(f"movrl X20 0(X28) 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movrl X18 8(X28) 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movlr 8(X16) X27 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movrl X27 16(X28) 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movlr 192(X16) X27 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movrl X27 24(X28) 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movrl X21 32(X28) 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movlr 48(X16) X27 0 8") 
  tranvertex_filter_master__write_return.writeAction(f"movir X30 -1") 
  tranvertex_filter_master__write_return.writeAction(f"sri X30 X30 1") 
  tranvertex_filter_master__write_return.writeAction(f"send_wcont X27 X30 X28 5") 
  tranvertex_filter_master__write_return.writeAction(f"yield_terminate") 
  tranvertex_filter_master__write_return.writeAction(f"__if_write_return_2_post: yield") 
  