from linker.EFAProgram import efaProgram

## Global constants

@efaProgram
def EFA_splitPagerankPullDD(efa):
  efa.code_level = 'machine'
  state0 = efa.State("udweave_init") #Only one state code 
  efa.add_initId(state0.state_id)
  ## Static declarations
  ## Scoped Variable "nlist_ptr" uses Register X16, scope (0)
  ## Scoped Variable "vid" uses Register X17, scope (0)
  ## Scoped Variable "new_value" uses Register X18, scope (0)
  ## Scoped Variable "old_value" uses Register X19, scope (0)
  ## Scoped Variable "nlist_bound" uses Register X20, scope (0)
  ## Scoped Variable "num_pending" uses Register X21, scope (0)
  ## Scoped Variable "write_ack_evw" uses Register X22, scope (0)
  ## Param "deg_op" uses Register X8, scope (0->8)
  ## Param "vid_op" uses Register X9, scope (0->8)
  ## Param "neighbors_op" uses Register X10, scope (0->8)
  ## Param "orig_vid_op" uses Register X11, scope (0->8)
  ## Param "split_start_op" uses Register X12, scope (0->8)
  ## Param "split_bound_op" uses Register X13, scope (0->8)
  ## Param "value_op" uses Register X14, scope (0->8)
  ## Param "active_flag" uses Register X15, scope (0->8)
  ## Param "vertex_addr" uses Register X3, scope (0->8)
  ## Scoped Variable "evw" uses Register X23, scope (0->8->10)
  ## Scoped Variable "active" uses Register X24, scope (0->8->10)
  ## Scoped Variable "evw" uses Register X23, scope (0->8->14)
  ## Scoped Variable "tmp_deg" uses Register X24, scope (0->8->14)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->8->14->16->18)
  ## Scoped Variable "value_addr" uses Register X24, scope (0->8->14->16->18)
  ## Scoped Variable "tmp_deg" uses Register X25, scope (0->8->14->16->18)
  ## Scoped Variable "active_flag_addr" uses Register X26, scope (0->8->14->16->18)
  ## Scoped Variable "temp_value" uses Register X27, scope (0->8->14->16->18)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->8->14->16->21)
  ## Scoped Variable "value_addr" uses Register X24, scope (0->8->14->16->21)
  ## Scoped Variable "evw" uses Register X23, scope (0->8->14->24)
  ## Scoped Variable "active" uses Register X24, scope (0->8->14->24)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->8->26)
  ## Scoped Variable "orig_vertex_addr" uses Register X24, scope (0->8->26)
  ## Scoped Variable "evw" uses Register X25, scope (0->8->26)
  ## Param "deg_op" uses Register X8, scope (0->29)
  ## Param "vid_op" uses Register X9, scope (0->29)
  ## Param "neighbors_op" uses Register X10, scope (0->29)
  ## Param "orig_vid_op" uses Register X11, scope (0->29)
  ## Param "split_start_op" uses Register X12, scope (0->29)
  ## Param "split_bound_op" uses Register X13, scope (0->29)
  ## Param "value_op" uses Register X14, scope (0->29)
  ## Param "active_flag" uses Register X15, scope (0->29)
  ## Param "orig_vertex_addr" uses Register X3, scope (0->29)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->29->32)
  ## Scoped Variable "value_addr" uses Register X24, scope (0->29->32)
  ## Scoped Variable "vertex_addr" uses Register X25, scope (0->29->32)
  ## Scoped Variable "tmp_deg" uses Register X26, scope (0->29->32)
  ## Scoped Variable "active_flag_addr" uses Register X27, scope (0->29->32)
  ## Scoped Variable "temp_value" uses Register X28, scope (0->29->32)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->29->36)
  ## Scoped Variable "vertex_addr" uses Register X24, scope (0->29->36)
  ## Scoped Variable "evw" uses Register X25, scope (0->29->36)
  ## Scoped Variable "tmp_deg" uses Register X26, scope (0->29->36)
  ## Param "deg_op" uses Register X8, scope (0->37)
  ## Param "vertex_addr" uses Register X9, scope (0->37)
  ## Scoped Variable "evw" uses Register X23, scope (0->37)
  ## Scoped Variable "max_fetch_size" uses Register X24, scope (0->37)
  ## Scoped Variable "tmp_lm_ptr" uses Register X25, scope (0->37)
  ## Scoped Variable "temp_value" uses Register X26, scope (0->37)
  ## Param "e0" uses Register X8, scope (0->43)
  ## Param "e1" uses Register X9, scope (0->43)
  ## Param "e2" uses Register X10, scope (0->43)
  ## Param "e3" uses Register X11, scope (0->43)
  ## Param "e4" uses Register X12, scope (0->43)
  ## Param "e5" uses Register X13, scope (0->43)
  ## Param "e6" uses Register X14, scope (0->43)
  ## Param "e7" uses Register X15, scope (0->43)
  ## Param "curr_nlist_addr" uses Register X3, scope (0->43)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->43)
  ## Scoped Variable "input_graph" uses Register X24, scope (0->43)
  ## Scoped Variable "tmp_nlist_ptr" uses Register X25, scope (0->43)
  ## Scoped Variable "read_nbor_vertex_evw" uses Register X26, scope (0->43)
  ## Scoped Variable "tmp_vertex_addr" uses Register X27, scope (0->43)
  ## Param "deg_op" uses Register X8, scope (0->62)
  ## Param "vid_op" uses Register X9, scope (0->62)
  ## Param "neighbors_op" uses Register X10, scope (0->62)
  ## Param "orig_vid_op" uses Register X11, scope (0->62)
  ## Param "split_start_op" uses Register X12, scope (0->62)
  ## Param "split_bound_op" uses Register X13, scope (0->62)
  ## Param "value_op" uses Register X14, scope (0->62)
  ## Param "active_flag" uses Register X15, scope (0->62)
  ## Param "vertex_addr" uses Register X3, scope (0->62)
  ## Scoped Variable "evw" uses Register X23, scope (0->62->65)
  ## Scoped Variable "tmp_lm_ptr" uses Register X24, scope (0->62->65)
  ## Scoped Variable "output_v_addr" uses Register X25, scope (0->62->65)
  ## Param "deg_op" uses Register X8, scope (0->67)
  ## Param "vid_op" uses Register X9, scope (0->67)
  ## Param "neighbors_op" uses Register X10, scope (0->67)
  ## Param "orig_vid_op" uses Register X11, scope (0->67)
  ## Param "split_start_op" uses Register X12, scope (0->67)
  ## Param "split_bound_op" uses Register X13, scope (0->67)
  ## Param "value_op" uses Register X14, scope (0->67)
  ## Param "active_flag" uses Register X15, scope (0->67)
  ## Param "vertex_addr" uses Register X3, scope (0->67)
  ## Scoped Variable "active" uses Register X23, scope (0->67)
  ## Scoped Variable "max_fetch_size" uses Register X24, scope (0->67)
  ## Scoped Variable "evw" uses Register X25, scope (0->67)
  ## Scoped Variable "tmp_lm_ptr" uses Register X26, scope (0->67)
  ## Scoped Variable "temp_value" uses Register X27, scope (0->67)
  ## Scoped Variable "tmp_lm_ptr" uses Register X23, scope (0->67->70)
  ## Scoped Variable "flag_addr" uses Register X24, scope (0->67->70)
  ## Scoped Variable "val" uses Register X25, scope (0->67->70)
  ## Scoped Variable "evw" uses Register X23, scope (0->67->73->75)
  ## Scoped Variable "ALPHA" uses Register X23, scope (0->67->78)
  ## Scoped Variable "tmp_val" uses Register X24, scope (0->67->78)
  ## Scoped Variable "weighted_val" uses Register X25, scope (0->67->78)
  ## Scoped Variable "tmp_lm_ptr" uses Register X24, scope (0->67->78->81)
  ## Scoped Variable "tmp" uses Register X25, scope (0->67->78->83)
  ## Scoped Variable "tmp_lm_ptr" uses Register X26, scope (0->67->78->83)
  ## Scoped Variable "N" uses Register X27, scope (0->67->78->83)
  ## Scoped Variable "tmp_eps_ptr" uses Register X24, scope (0->67->86)
  ## Scoped Variable "eps" uses Register X25, scope (0->67->86)
  ## Scoped Variable "diff" uses Register X26, scope (0->67->86)
  ## Scoped Variable "value_addr" uses Register X27, scope (0->67->86)
  ## Param "e0" uses Register X8, scope (0->110)
  ## Param "e1" uses Register X9, scope (0->110)
  ## Param "e2" uses Register X10, scope (0->110)
  ## Param "e3" uses Register X11, scope (0->110)
  ## Param "e4" uses Register X12, scope (0->110)
  ## Param "e5" uses Register X13, scope (0->110)
  ## Param "e6" uses Register X14, scope (0->110)
  ## Param "e7" uses Register X15, scope (0->110)
  ## Param "curr_nlist_addr" uses Register X3, scope (0->110)
  ## Scoped Variable "tmp_nlist_ptr" uses Register X23, scope (0->110)
  ## Scoped Variable "is_active" uses Register X24, scope (0->110)
  ## Scoped Variable "tmp_lm_ptr" uses Register X25, scope (0->110)
  ## Scoped Variable "output_graph" uses Register X26, scope (0->110)
  ## Scoped Variable "tmp_vertex_addr" uses Register X27, scope (0->110)
  ## Param "return_addr" uses Register X8, scope (0->137)
  ## Scoped Variable "evw" uses Register X23, scope (0->137)
  ## Scoped Variable "tmp_lm_ptr" uses Register X16, scope (0)
  ## Param "partition_array" uses Register X8, scope (0->143)
  ## Param "num_orig_vertices" uses Register X9, scope (0->143)
  ## Param "num_lanes" uses Register X10, scope (0->143)
  ## Param "input_vertices" uses Register X11, scope (0->143)
  ## Param "num_vertices" uses Register X12, scope (0->143)
  ## Param "output_vertices" uses Register X13, scope (0->143)
  ## Param "epsilon" uses Register X14, scope (0->143)
  ## Param "alpha" uses Register X15, scope (0->143)
  ## Scoped Variable "partition_parameter" uses Register X17, scope (0->143)
  ## Scoped Variable "send_buffer" uses Register X18, scope (0->143)
  ## Scoped Variable "tmp_double_ptr" uses Register X19, scope (0->143)
  ## Scoped Variable "evw" uses Register X20, scope (0->143)
  ## Param "num_lanes" uses Register X8, scope (0->145)
  ## Param "value" uses Register X9, scope (0->145)
  ## Scoped Variable "tmp_lm_ptr" uses Register X16, scope (0)
  ## Param "partition_array" uses Register X8, scope (0->147)
  ## Param "num_part" uses Register X9, scope (0->147)
  ## Param "num_lanes" uses Register X10, scope (0->147)
  ## Param "input_vertices" uses Register X11, scope (0->147)
  ## Param "num_vertices" uses Register X12, scope (0->147)
  ## Param "output_vertices" uses Register X13, scope (0->147)
  ## Param "epsilon" uses Register X14, scope (0->147)
  ## Param "num_orig_vertices" uses Register X15, scope (0->147)
  ## Scoped Variable "send_buffer" uses Register X17, scope (0->147)
  ## Scoped Variable "tmp_eps_ptr" uses Register X18, scope (0->147)
  ## Scoped Variable "evw" uses Register X19, scope (0->147)
  ## Param "num_lanes" uses Register X8, scope (0->149)
  ## Param "value" uses Register X9, scope (0->149)
  ## Scoped Variable "sibling_ptr" uses Register X16, scope (0)
  ## Scoped Variable "sibling_bound" uses Register X17, scope (0)
  ## Scoped Variable "orig_degree" uses Register X18, scope (0)
  ## Scoped Variable "active_flag" uses Register X19, scope (0)
  ## Scoped Variable "sibling_addr" uses Register X20, scope (0)
  ## Scoped Variable "significant" uses Register X21, scope (0)
  ## Scoped Variable "new_value" uses Register X22, scope (0)
  ## Scoped Variable "num_pending" uses Register X23, scope (0)
  ## Param "deg_op" uses Register X8, scope (0->151)
  ## Param "vid_op" uses Register X9, scope (0->151)
  ## Param "neighbors_op" uses Register X10, scope (0->151)
  ## Param "orig_vid_op" uses Register X11, scope (0->151)
  ## Param "split_start_op" uses Register X12, scope (0->151)
  ## Param "split_bound_op" uses Register X13, scope (0->151)
  ## Param "value_op" uses Register X14, scope (0->151)
  ## Param "active_flag_op" uses Register X15, scope (0->151)
  ## Param "vertex_addr" uses Register X3, scope (0->151)
  ## Scoped Variable "tmp_lm_ptr" uses Register X24, scope (0->151)
  ## Scoped Variable "old_vertex_addr" uses Register X25, scope (0->151)
  ## Scoped Variable "read_old_value_evw" uses Register X26, scope (0->151)
  ## Scoped Variable "tmp_deg" uses Register X24, scope (0->151->154)
  ## Scoped Variable "tmp_lm_ptr" uses Register X25, scope (0->151->154)
  ## Scoped Variable "value_addr" uses Register X26, scope (0->151->154)
  ## Scoped Variable "evw" uses Register X27, scope (0->151->154)
  ## Scoped Variable "clear_flag" uses Register X28, scope (0->151->154)
  ## Scoped Variable "clear_value" uses Register X27, scope (0->151->165)
  ## Scoped Variable "value_addr" uses Register X28, scope (0->151->165)
  ## Scoped Variable "ack_evw" uses Register X29, scope (0->151->165)
  ## Param "deg_op" uses Register X8, scope (0->167)
  ## Param "vid_op" uses Register X9, scope (0->167)
  ## Param "neighbors_op" uses Register X10, scope (0->167)
  ## Param "orig_vid_op" uses Register X11, scope (0->167)
  ## Param "split_start_op" uses Register X12, scope (0->167)
  ## Param "split_bound_op" uses Register X13, scope (0->167)
  ## Param "old_value_op" uses Register X14, scope (0->167)
  ## Param "active_flag_op" uses Register X15, scope (0->167)
  ## Param "old_vertex_addr" uses Register X3, scope (0->167)
  ## Scoped Variable "read_v_evw" uses Register X24, scope (0->167)
  ## Scoped Variable "max_parallelism" uses Register X25, scope (0->167)
  ## Scoped Variable "tmp_lm_ptr" uses Register X26, scope (0->167)
  ## Scoped Variable "ctr" uses Register X27, scope (0->167)
  ## Scoped Variable "value_addr" uses Register X24, scope (0->167->169->171)
  ## Scoped Variable "ack_evw" uses Register X25, scope (0->167->169->171)
  ## Scoped Variable "temp_value" uses Register X26, scope (0->167->169->171->173)
  ## Scoped Variable "ALPHA" uses Register X24, scope (0->167->177)
  ## Scoped Variable "tmp_val" uses Register X25, scope (0->167->177)
  ## Scoped Variable "weighted_val" uses Register X26, scope (0->167->177)
  ## Scoped Variable "tmp_lm_ptr" uses Register X25, scope (0->167->177->179)
  ## Scoped Variable "tmp_lm_ptr" uses Register X26, scope (0->167->177->181)
  ## Scoped Variable "tmp" uses Register X27, scope (0->167->177->181)
  ## Scoped Variable "N" uses Register X28, scope (0->167->177->181)
  ## Scoped Variable "tmp_eps_ptr" uses Register X24, scope (0->167->184)
  ## Scoped Variable "eps" uses Register X25, scope (0->167->184)
  ## Scoped Variable "tmp_val" uses Register X26, scope (0->167->184)
  ## Scoped Variable "diff" uses Register X27, scope (0->167->184)
  ## Scoped Variable "tmp_deg" uses Register X24, scope (0->167->195)
  ## Scoped Variable "value_addr" uses Register X24, scope (0->167->197)
  ## Scoped Variable "ack_evw" uses Register X25, scope (0->167->197)
  ## Scoped Variable "temp_value" uses Register X26, scope (0->167->197->199)
  ## Param "deg_op" uses Register X8, scope (0->206)
  ## Param "vid_op" uses Register X9, scope (0->206)
  ## Param "neighbors_op" uses Register X10, scope (0->206)
  ## Param "orig_vid_op" uses Register X11, scope (0->206)
  ## Param "split_start_op" uses Register X12, scope (0->206)
  ## Param "split_bound_op" uses Register X13, scope (0->206)
  ## Param "value_op" uses Register X14, scope (0->206)
  ## Param "active_flag_op" uses Register X15, scope (0->206)
  ## Param "vertex_addr" uses Register X3, scope (0->206)
  ## Scoped Variable "tmp_lm_ptr" uses Register X24, scope (0->206->213)
  ## Scoped Variable "output_graph" uses Register X25, scope (0->206->213)
  ## Scoped Variable "value_addr" uses Register X26, scope (0->206->213)
  ## Scoped Variable "update_evw" uses Register X27, scope (0->206->213)
  ## Scoped Variable "evw" uses Register X24, scope (0->206->216)
  ## Scoped Variable "max_parallelism" uses Register X25, scope (0->206->216)
  ## Scoped Variable "nlist_ptr" uses Register X26, scope (0->206->216)
  ## Scoped Variable "nlist_bound" uses Register X27, scope (0->206->216)
  ## Scoped Variable "tmp_deg" uses Register X28, scope (0->206->216)
  ## Scoped Variable "tmp_lm_ptr" uses Register X29, scope (0->206->216)
  ## Scoped Variable "temp_value" uses Register X30, scope (0->206->216)
  ## Param "return_addr" uses Register X8, scope (0->224)
  ## Scoped Variable "evw" uses Register X24, scope (0->224->227)
  ## Param "neighbors_op" uses Register X8, scope (0->229)
  ## Param "num_neighbors" uses Register X9, scope (0->229)
  ## Scoped Variable "max_fetch_size" uses Register X24, scope (0->229)
  ## Scoped Variable "evw" uses Register X25, scope (0->229)
  ## Scoped Variable "nlist_ptr" uses Register X26, scope (0->229)
  ## Scoped Variable "nlist_bound" uses Register X27, scope (0->229)
  ## Param "e0" uses Register X8, scope (0->235)
  ## Param "e1" uses Register X9, scope (0->235)
  ## Param "e2" uses Register X10, scope (0->235)
  ## Param "e3" uses Register X11, scope (0->235)
  ## Param "e4" uses Register X12, scope (0->235)
  ## Param "e5" uses Register X13, scope (0->235)
  ## Param "e6" uses Register X14, scope (0->235)
  ## Param "e7" uses Register X15, scope (0->235)
  ## Param "curr_nlist_addr" uses Register X3, scope (0->235)
  ## Scoped Variable "nlist_ptr" uses Register X24, scope (0->235)
  ## Scoped Variable "nlist_bound" uses Register X25, scope (0->235)
  ## Scoped Variable "tmp_nlist_ptr" uses Register X26, scope (0->235)
  ## Scoped Variable "output_graph" uses Register X27, scope (0->235)
  ## Scoped Variable "write_ack_evw" uses Register X28, scope (0->235)
  ## Scoped Variable "tmp_vertex_addr" uses Register X29, scope (0->235)
  ## Scoped Variable "tmp_lm_ptr" uses Register X28, scope (0->235->240)
  ## Param "return_addr" uses Register X8, scope (0->263)
  ## Scoped Variable "evw" uses Register X24, scope (0->263)
  
  ####################################################
  ###### Writing code for thread PageRankPullDD ######
  ####################################################
  # Writing code for event PageRankPullDD::kv_map
  tranPageRankPullDD__kv_map = efa.writeEvent('PageRankPullDD::kv_map')
  ## The vertex has degree 0, skip it
  tranPageRankPullDD__kv_map.writeAction(f"entry: bneiu X8 0 __if_kv_map_2_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_0_true: evi X2 X23 PageRankPullDD::kv_map_return 1") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X24 0") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_wcont X23 X2 X9 X24") 
  tranPageRankPullDD__kv_map.writeAction(f"yield") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_2_post: sli X8 X23 3") 
  tranPageRankPullDD__kv_map.writeAction(f"add X10 X23 X20") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X10 X16 0") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X9 X17 0") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X18 0") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X14 X19 0") 
  tranPageRankPullDD__kv_map.writeAction(f"bne X9 X11 __if_kv_map_10_false") 
  ## Check if the vertex is active. if so, skip it
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_9_true: bnei X15 0 __if_kv_map_14_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_12_true: bne X12 X13 __if_kv_map_16_false") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_15_true: addi X7 X23 792") 
  tranPageRankPullDD__kv_map.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__kv_map.writeAction(f"sli X17 X25 6") 
  tranPageRankPullDD__kv_map.writeAction(f"add X24 X25 X24") 
  tranPageRankPullDD__kv_map.writeAction(f"fcnvt.i64.64 X8 X25")  # This is for casting. May be used later on
  tranPageRankPullDD__kv_map.writeAction(f"fmul.64 X19 X25 X19") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X24 X24 48") 
  tranPageRankPullDD__kv_map.writeAction(f"evi X2 X22 PageRankPullDD::write_value_ack 1") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_dmlm X24 X22 X19") 
  ## Clear active flag in non-split vertices
  tranPageRankPullDD__kv_map.writeAction(f"addi X3 X26 56") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X27 0") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_dmlm X26 X22 X27") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X21 2") 
  tranPageRankPullDD__kv_map.writeAction(f"jmp __if_kv_map_17_post") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_16_false: addi X7 X23 792") 
  tranPageRankPullDD__kv_map.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__kv_map.writeAction(f"sli X17 X25 6") 
  tranPageRankPullDD__kv_map.writeAction(f"add X24 X25 X24") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X24 X24 48") 
  tranPageRankPullDD__kv_map.writeAction(f"evi X2 X22 PageRankPullDD::write_value_ack 1") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_dmlm X24 X22 X19") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X21 1") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_17_post: yield") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_14_post: beq X12 X13 __if_kv_map_29_post") 
  ## This is an original vertex, no need to pull neighbors
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_27_true: evi X2 X23 PageRankPullDD::kv_map_return 1") 
  tranPageRankPullDD__kv_map.writeAction(f"movir X24 0") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_wcont X23 X2 X9 X24") 
  tranPageRankPullDD__kv_map.writeAction(f"yield") 
  ## The vertex is active, start pulling from neighbors
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_29_post: evi X2 X23 PageRankPullDD::pull_neighbors 1") 
  tranPageRankPullDD__kv_map.writeAction(f"sendr_wcont X23 X2 X8 X3") 
  tranPageRankPullDD__kv_map.writeAction(f"fcnvt.i64.64 X8 X24")  # This is for casting. May be used later on
  tranPageRankPullDD__kv_map.writeAction(f"fmul.64 X19 X24 X19") 
  tranPageRankPullDD__kv_map.writeAction(f"yield") 
  tranPageRankPullDD__kv_map.writeAction(f"jmp __if_kv_map_11_post") 
  ## Get the active flags from the original vertices
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_10_false: addi X7 X23 784") 
  tranPageRankPullDD__kv_map.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__kv_map.writeAction(f"sli X11 X25 6") 
  tranPageRankPullDD__kv_map.writeAction(f"add X24 X25 X24") 
  tranPageRankPullDD__kv_map.writeAction(f"evi X2 X25 PageRankPullDD::read_orig_vertex 1") 
  tranPageRankPullDD__kv_map.writeAction(f"send_dmlm_ld X24 X25 8") 
  tranPageRankPullDD__kv_map.writeAction(f"addi X8 X21 0") 
  tranPageRankPullDD__kv_map.writeAction(f"__if_kv_map_11_post: yield") 
  
  # Writing code for event PageRankPullDD::read_orig_vertex
  tranPageRankPullDD__read_orig_vertex = efa.writeEvent('PageRankPullDD::read_orig_vertex')
  ## Check if the vertex is active. if so, skip it
  tranPageRankPullDD__read_orig_vertex.writeAction(f"entry: bnei X15 0 __if_read_orig_vertex_12_true") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"__if_read_orig_vertex_3_true: addi X7 X23 792") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"sli X17 X25 6") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"add X24 X25 X24") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"addi X7 X23 784") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"movlr 0(X23) X25 0 8") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"sli X17 X26 6") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"add X25 X26 X25") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"fcnvt.i64.64 X8 X26")  # This is for casting. May be used later on
  tranPageRankPullDD__read_orig_vertex.writeAction(f"fmul.64 X14 X26 X19") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"addi X24 X24 48") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"evi X2 X22 PageRankPullDD::write_value_ack 1") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"sendr_dmlm X24 X22 X19") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"addi X25 X27 56") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"movir X28 0") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"sendr_dmlm X27 X22 X28") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"movir X21 2") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"yield") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"__if_read_orig_vertex_12_true: addi X7 X23 784") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"sli X17 X25 6") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"add X24 X25 X24") 
  ## The vertex is active, start pulling from neighbors
  tranPageRankPullDD__read_orig_vertex.writeAction(f"evi X2 X25 PageRankPullDD::pull_neighbors 1") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"sendr_wcont X25 X2 X21 X24") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"fcnvt.i64.64 X8 X26")  # This is for casting. May be used later on
  tranPageRankPullDD__read_orig_vertex.writeAction(f"fmul.64 X14 X26 X19") 
  tranPageRankPullDD__read_orig_vertex.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::pull_neighbors
  tranPageRankPullDD__pull_neighbors = efa.writeEvent('PageRankPullDD::pull_neighbors')
  tranPageRankPullDD__pull_neighbors.writeAction(f"entry: movir X21 0") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"evi X2 X23 PageRankPullDD::rd_nlist_return 1") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"movir X24 512") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"__while_pull_neighbors_3_condition: ble X8 X21 __while_pull_neighbors_5_post") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"__while_pull_neighbors_4_body: send_dmlm_ld X16 X23 8") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"addi X21 X21 8") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"bgt X24 X21 __if_pull_neighbors_8_post") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"__if_pull_neighbors_6_true: jmp __while_pull_neighbors_5_post") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"__if_pull_neighbors_8_post: jmp __while_pull_neighbors_3_condition") 
  ## Count active set volume
  tranPageRankPullDD__pull_neighbors.writeAction(f"__while_pull_neighbors_5_post: addi X7 X25 1152") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"movlr 0(X25) X26 0 8") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"add X26 X8 X26") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"movrl X26 0(X25) 0 8") 
  tranPageRankPullDD__pull_neighbors.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::rd_nlist_return
  tranPageRankPullDD__rd_nlist_return = efa.writeEvent('PageRankPullDD::rd_nlist_return')
  tranPageRankPullDD__rd_nlist_return.writeAction(f"entry: ble X20 X16 __if_rd_nlist_return_2_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_0_true: send_dmlm_ld X16 X2 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X21 X21 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_2_post: addi X7 X23 784") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X3 X25 0") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"evi X2 X26 PageRankPullDD::read_nbor_vertex 1") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_5_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_3_true: subi X21 X21 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_5_post: sli X8 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_8_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_6_true: subi X21 X21 7") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_8_post: sli X9 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_11_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_9_true: subi X21 X21 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_11_post: sli X10 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_14_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_12_true: subi X21 X21 5") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_14_post: sli X11 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_17_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_15_true: subi X21 X21 4") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_17_post: sli X12 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_20_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_18_true: subi X21 X21 3") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_20_post: sli X13 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_23_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_21_true: subi X21 X21 2") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_23_post: sli X14 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"addi X25 X25 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"bgt X20 X25 __if_rd_nlist_return_26_post") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_24_true: subi X21 X21 1") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"__if_rd_nlist_return_26_post: sli X15 X28 6") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"add X24 X28 X27") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"send_dmlm_ld X27 X26 8") 
  tranPageRankPullDD__rd_nlist_return.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::read_nbor_vertex
  tranPageRankPullDD__read_nbor_vertex = efa.writeEvent('PageRankPullDD::read_nbor_vertex')
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"entry: fadd.64 X18 X14 X18") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"subi X21 X21 1") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"bnei X21 0 __if_read_nbor_vertex_5_post") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"__if_read_nbor_vertex_3_true: evi X2 X23 PageRankPullDD::update_value 1") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"addi X7 X24 792") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"movlr 0(X24) X25 0 8") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"sli X17 X26 6") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"add X25 X26 X25") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"send_dmlm_ld X25 X23 8") 
  tranPageRankPullDD__read_nbor_vertex.writeAction(f"__if_read_nbor_vertex_5_post: yield") 
  
  # Writing code for event PageRankPullDD::update_value
  tranPageRankPullDD__update_value = efa.writeEvent('PageRankPullDD::update_value')
  tranPageRankPullDD__update_value.writeAction(f"entry: evi X2 X22 PageRankPullDD::write_value_ack 1") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_3_true: addi X7 X23 784") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 0(X23) X24 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"sli X17 X25 6") 
  tranPageRankPullDD__update_value.writeAction(f"add X24 X25 X26") 
  tranPageRankPullDD__update_value.writeAction(f"addi X26 X24 56") 
  tranPageRankPullDD__update_value.writeAction(f"movir X25 0") 
  tranPageRankPullDD__update_value.writeAction(f"sendr_dmlm X24 X22 X25") 
  ## Check if the vertex is a split vertex, if so, propogate the update to original vid
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_9_true: ble X13 X12 __if_update_value_24_true") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_12_true: movir X23 0") 
  tranPageRankPullDD__update_value.writeAction(f"evlb X23 PageRankPullDD::kv_map_emit") 
  tranPageRankPullDD__update_value.writeAction(f"evi X23 X23 255 4") 
  tranPageRankPullDD__update_value.writeAction(f"ev X23 X23 X0 X0 8") 
  tranPageRankPullDD__update_value.writeAction(f"sendr_wcont X23 X2 X11 X18") 
  tranPageRankPullDD__update_value.writeAction(f"movir X21 1") 
  tranPageRankPullDD__update_value.writeAction(f"yield") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_24_true: addi X7 X24 864") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 0(X24) X23 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_27_true: movir X25 1") 
  tranPageRankPullDD__update_value.writeAction(f"fcnvt.i64.64 X25 X24")  # This is for casting. May be used later on
  tranPageRankPullDD__update_value.writeAction(f"addi X7 X26 832") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 24(X26) X25 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"fcnvt.i64.64 X25 X27")  # This is for casting. May be used later on
  tranPageRankPullDD__update_value.writeAction(f"fsub.64 X24 X23 X24") 
  tranPageRankPullDD__update_value.writeAction(f"fdiv.64 X24 X27 X24") 
  tranPageRankPullDD__update_value.writeAction(f"fmul.64 X23 X18 X26") 
  tranPageRankPullDD__update_value.writeAction(f"fadd.64 X26 X24 X25") 
  tranPageRankPullDD__update_value.writeAction(f"addi X25 X18 0") 
  tranPageRankPullDD__update_value.writeAction(f"movir X23 0") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_33_true: addi X7 X24 800") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 0(X24) X25 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"fsub.64 X18 X19 X26") 
  tranPageRankPullDD__update_value.writeAction(f"bgei X26 0 __if_update_value_41_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_39_true: movir X27 -16400") 
  tranPageRankPullDD__update_value.writeAction(f"sli X27 X27 48") 
  tranPageRankPullDD__update_value.writeAction(f"fmul.64 X26 X27 X26") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_41_post: ble X25 X26 __if_update_value_46_false") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_45_true: movir X23 0") 
  tranPageRankPullDD__update_value.writeAction(f"jmp __if_update_value_47_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_46_false: movir X23 1") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_47_post: evi X2 X22 PageRankPullDD::write_value_ack 1") 
  tranPageRankPullDD__update_value.writeAction(f"addi X3 X27 48") 
  tranPageRankPullDD__update_value.writeAction(f"beqiu X23 0 __if_update_value_55_false") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_54_true: sendr_dmlm X27 X22 X18") 
  tranPageRankPullDD__update_value.writeAction(f"jmp __if_update_value_56_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_55_false: sendr_dmlm X27 X22 X19") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_56_post: bneiu X23 0 __if_update_value_65_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_63_true: movir X21 2") 
  tranPageRankPullDD__update_value.writeAction(f"yield") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_65_post: movir X21 0") 
  tranPageRankPullDD__update_value.writeAction(f"movir X24 512") 
  tranPageRankPullDD__update_value.writeAction(f"evi X2 X25 PageRankPullDD::rd_nlist_return_update 1") 
  tranPageRankPullDD__update_value.writeAction(f"addi X10 X16 0") 
  tranPageRankPullDD__update_value.writeAction(f"sli X8 X26 3") 
  tranPageRankPullDD__update_value.writeAction(f"add X10 X26 X20") 
  tranPageRankPullDD__update_value.writeAction(f"__while_update_value_72_condition: ble X8 X21 __while_update_value_74_post") 
  tranPageRankPullDD__update_value.writeAction(f"__while_update_value_73_body: send_dmlm_ld X16 X25 8") 
  tranPageRankPullDD__update_value.writeAction(f"addi X21 X21 8") 
  tranPageRankPullDD__update_value.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__update_value.writeAction(f"bgt X24 X21 __if_update_value_77_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_75_true: jmp __while_update_value_74_post") 
  tranPageRankPullDD__update_value.writeAction(f"__if_update_value_77_post: jmp __while_update_value_72_condition") 
  tranPageRankPullDD__update_value.writeAction(f"__while_update_value_74_post: addi X8 X21 2") 
  ## Count active set volume
  tranPageRankPullDD__update_value.writeAction(f"addi X7 X26 1152") 
  tranPageRankPullDD__update_value.writeAction(f"movlr 0(X26) X27 0 8") 
  tranPageRankPullDD__update_value.writeAction(f"add X27 X8 X27") 
  tranPageRankPullDD__update_value.writeAction(f"movrl X27 0(X26) 0 8") 
  ## if (DEBUG_OUTPUT_FLAG) {
  ##     long *local tmp_lm_ptr = LMBASE + INPUT_GRAPH_PTR_OFFSET;
  ##     value_addr = *tmp_lm_ptr;
  ##     value_addr = value_addr + (vid << VERTEX_LOG2_BSIZE) + (7 * WORD_SIZE);
  ##     long temp_value = 2;
  ##     send_dram_write(value_addr, temp_value, write_ack_evw);
  ##     if (DEBUG_FLAG) {
  ##         value_addr = value_addr - (WORD_SIZE * 7);
  ##         print("[DEBUG][NWID %d][update_value] Write active flag to old vertex %ld (addr=0x%lx) active=%ld", NETID, vid, value_addr, temp_value);
  ##     }
  ##     num_pending = num_pending + 1;
  ## }
  tranPageRankPullDD__update_value.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::rd_nlist_return_update
  tranPageRankPullDD__rd_nlist_return_update = efa.writeEvent('PageRankPullDD::rd_nlist_return_update')
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"entry: ble X20 X16 __if_rd_nlist_return_update_5_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_3_true: send_dmlm_ld X16 X2 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X16 X16 64") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_5_post: addi X3 X23 0") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"movir X24 1") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X7 X25 792") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"movlr 0(X25) X26 0 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sli X8 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_14_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_12_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_14_post: sli X9 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_20_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_18_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_20_post: sli X10 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_26_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_24_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_26_post: sli X11 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_32_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_30_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_32_post: sli X12 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_38_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_36_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_38_post: sli X13 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_44_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_42_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_44_post: sli X14 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X23 X23 8") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"bgt X20 X23 __if_rd_nlist_return_update_50_post") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_48_true: yield") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_50_post: sli X15 X28 6") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"add X26 X28 X29") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"addi X29 X27 56") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"sendr_dmlm X27 X22 X24") 
  tranPageRankPullDD__rd_nlist_return_update.writeAction(f"yield") 
  
  # Writing code for event PageRankPullDD::write_value_ack
  tranPageRankPullDD__write_value_ack = efa.writeEvent('PageRankPullDD::write_value_ack')
  tranPageRankPullDD__write_value_ack.writeAction(f"entry: subi X21 X21 1") 
  tranPageRankPullDD__write_value_ack.writeAction(f"blei X21 0 __if_write_value_ack_5_post") 
  tranPageRankPullDD__write_value_ack.writeAction(f"__if_write_value_ack_3_true: yield") 
  tranPageRankPullDD__write_value_ack.writeAction(f"__if_write_value_ack_5_post: evi X2 X23 PageRankPullDD::kv_map_return 1") 
  tranPageRankPullDD__write_value_ack.writeAction(f"sendr_wcont X23 X2 X17 X21") 
  tranPageRankPullDD__write_value_ack.writeAction(f"yield") 
  
  
  ################################################
  ###### Writing code for thread InitUpDown ######
  ################################################
  # Writing code for event InitUpDown::init
  tranInitUpDown__init = efa.writeEvent('InitUpDown::init')
  tranInitUpDown__init.writeAction(f"entry: print 'Phase 1 Start'") 
  tranInitUpDown__init.writeAction(f"movir X17 3") 
  tranInitUpDown__init.writeAction(f"addi X7 X18 8") 
  tranInitUpDown__init.writeAction(f"movrl X8 0(X18) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X17 8(X18) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X10 16(X18) 0 8") 
  tranInitUpDown__init.writeAction(f"addi X7 X16 768") 
  tranInitUpDown__init.writeAction(f"movrl X11 0(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X12 8(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X11 16(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X13 24(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"addi X7 X19 800") 
  tranInitUpDown__init.writeAction(f"movrl X14 0(X19) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X16 24(X18) 0 8") 
  tranInitUpDown__init.writeAction(f"addi X7 X16 832") 
  tranInitUpDown__init.writeAction(f"movrl X13 0(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X9 8(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X9 16(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X9 24(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"addi X7 X19 864") 
  tranInitUpDown__init.writeAction(f"movrl X15 0(X19) 0 8") 
  tranInitUpDown__init.writeAction(f"movrl X16 32(X18) 0 8") 
  tranInitUpDown__init.writeAction(f"movir X20 0") 
  tranInitUpDown__init.writeAction(f"evlb X20 PageRankPullDD::map_shuffle_reduce") 
  tranInitUpDown__init.writeAction(f"evi X20 X20 255 4") 
  tranInitUpDown__init.writeAction(f"ev X20 X20 X0 X0 8") 
  tranInitUpDown__init.writeAction(f"send_wret X20 InitUpDown::terminate X18 5 X21") 
  tranInitUpDown__init.writeAction(f"addi X7 X16 0") 
  tranInitUpDown__init.writeAction(f"movir X22 0") 
  tranInitUpDown__init.writeAction(f"movrl X22 0(X16) 0 8") 
  tranInitUpDown__init.writeAction(f"yield") 
  
  # Writing code for event InitUpDown::terminate
  tranInitUpDown__terminate = efa.writeEvent('InitUpDown::terminate')
  tranInitUpDown__terminate.writeAction(f"entry: print 'Phase 1 End'") 
  tranInitUpDown__terminate.writeAction(f"movir X18 1") 
  tranInitUpDown__terminate.writeAction(f"movrl X18 0(X16) 0 8") 
  tranInitUpDown__terminate.writeAction(f"yield_terminate") 
  
  
  ###############################################
  ###### Writing code for thread InitMerge ######
  ###############################################
  # Writing code for event InitMerge::init
  tranInitMerge__init = efa.writeEvent('InitMerge::init')
  tranInitMerge__init.writeAction(f"entry: print 'Phase 2: Start merging split vertices.'") 
  tranInitMerge__init.writeAction(f"addi X7 X17 8") 
  tranInitMerge__init.writeAction(f"movrl X8 0(X17) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X9 8(X17) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X10 16(X17) 0 8") 
  tranInitMerge__init.writeAction(f"addi X7 X16 1024") 
  tranInitMerge__init.writeAction(f"movrl X11 0(X16) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X15 8(X16) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X11 16(X16) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X13 24(X16) 0 8") 
  tranInitMerge__init.writeAction(f"addi X7 X18 800") 
  tranInitMerge__init.writeAction(f"movrl X14 0(X18) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X16 24(X17) 0 8") 
  tranInitMerge__init.writeAction(f"addi X7 X16 1088") 
  tranInitMerge__init.writeAction(f"movrl X13 0(X16) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X12 8(X16) 0 8") 
  tranInitMerge__init.writeAction(f"movrl X16 32(X17) 0 8") 
  tranInitMerge__init.writeAction(f"movir X19 0") 
  tranInitMerge__init.writeAction(f"evlb X19 MergeMSR::map_shuffle_reduce") 
  tranInitMerge__init.writeAction(f"evi X19 X19 255 4") 
  tranInitMerge__init.writeAction(f"ev X19 X19 X0 X0 8") 
  tranInitMerge__init.writeAction(f"send_wret X19 InitMerge::terminate X17 5 X20") 
  tranInitMerge__init.writeAction(f"addi X7 X16 0") 
  tranInitMerge__init.writeAction(f"movir X21 0") 
  tranInitMerge__init.writeAction(f"movrl X21 0(X16) 0 8") 
  tranInitMerge__init.writeAction(f"yield") 
  
  # Writing code for event InitMerge::terminate
  tranInitMerge__terminate = efa.writeEvent('InitMerge::terminate')
  tranInitMerge__terminate.writeAction(f"entry: print 'Phase 2: Finish merging split vertices, current active set volume = %lu.' X9") 
  tranInitMerge__terminate.writeAction(f"movir X18 1") 
  tranInitMerge__terminate.writeAction(f"movrl X18 0(X16) 0 8") 
  tranInitMerge__terminate.writeAction(f"yield_terminate") 
  
  
  ##############################################
  ###### Writing code for thread MergeMSR ######
  ##############################################
  # Writing code for event MergeMSR::kv_map
  tranMergeMSR__kv_map = efa.writeEvent('MergeMSR::kv_map')
  ## Set the vertex information
  tranMergeMSR__kv_map.writeAction(f"entry: addi X8 X18 0") 
  tranMergeMSR__kv_map.writeAction(f"addi X12 X16 0") 
  tranMergeMSR__kv_map.writeAction(f"addi X13 X17 0") 
  ## If the vertex is not a split vertex, directly write the weighted value back
  tranMergeMSR__kv_map.writeAction(f"bne X12 X13 __if_kv_map_5_post") 
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_3_true: fcnvt.i64.64 X8 X24")  # This is for casting. May be used later on
  tranMergeMSR__kv_map.writeAction(f"fdiv.64 X14 X24 X22") 
  tranMergeMSR__kv_map.writeAction(f"addi X7 X25 1088") 
  tranMergeMSR__kv_map.writeAction(f"movlr 0(X25) X26 0 8") 
  tranMergeMSR__kv_map.writeAction(f"sli X9 X27 6") 
  tranMergeMSR__kv_map.writeAction(f"add X26 X27 X26") 
  tranMergeMSR__kv_map.writeAction(f"addi X26 X26 48") 
  tranMergeMSR__kv_map.writeAction(f"evi X2 X27 MergeMSR::update_vertex_ack 1") 
  tranMergeMSR__kv_map.writeAction(f"beqi X15 0 __if_kv_map_10_false") 
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_9_true: sendr2_dmlm X26 X27 X22 X15") 
  tranMergeMSR__kv_map.writeAction(f"jmp __if_kv_map_11_post") 
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_10_false: sendr_dmlm X26 X27 X22") 
  ## Clear the flag value of the current graph for the next iteration
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_11_post: movir X28 0") 
  tranMergeMSR__kv_map.writeAction(f"addi X3 X26 48") 
  tranMergeMSR__kv_map.writeAction(f"sendr2_dmlm X26 X27 X28 X28") 
  ## Update the pending counts
  tranMergeMSR__kv_map.writeAction(f"movir X23 2") 
  tranMergeMSR__kv_map.writeAction(f"yield") 
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_5_post: blei X15 0 __if_kv_map_16_false") 
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_15_true: movir X19 1") 
  tranMergeMSR__kv_map.writeAction(f"jmp __if_kv_map_17_post") 
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_16_false: movir X19 0") 
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_17_post: addi X14 X22 0") 
  ## Read the old value from DRAM.
  tranMergeMSR__kv_map.writeAction(f"addi X7 X24 1088") 
  tranMergeMSR__kv_map.writeAction(f"movlr 0(X24) X25 0 8") 
  tranMergeMSR__kv_map.writeAction(f"sli X9 X26 6") 
  tranMergeMSR__kv_map.writeAction(f"add X25 X26 X25") 
  tranMergeMSR__kv_map.writeAction(f"evi X2 X26 MergeMSR::read_old_vertex 1") 
  tranMergeMSR__kv_map.writeAction(f"send_dmlm_ld X25 X26 8") 
  ## Clear the vertex structure for the next iteration
  tranMergeMSR__kv_map.writeAction(f"__if_kv_map_21_true: movir X27 0") 
  tranMergeMSR__kv_map.writeAction(f"addi X3 X28 48") 
  tranMergeMSR__kv_map.writeAction(f"evi X2 X29 MergeMSR::update_vertex_ack 1") 
  tranMergeMSR__kv_map.writeAction(f"sendr2_dmlm X28 X29 X27 X27") 
  tranMergeMSR__kv_map.writeAction(f"movir X23 1") 
  tranMergeMSR__kv_map.writeAction(f"yield") 
  
  # Writing code for event MergeMSR::read_old_vertex
  tranMergeMSR__read_old_vertex = efa.writeEvent('MergeMSR::read_old_vertex')
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_0_true: bne X14 X22 __if_read_old_vertex_15_true") 
  ## No update needed, skip the rest of the process
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_3_true: addi X17 X16 0") 
  tranMergeMSR__read_old_vertex.writeAction(f"addi X3 X24 48") 
  tranMergeMSR__read_old_vertex.writeAction(f"evi X2 X25 MergeMSR::update_vertex_ack 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"or X15 X19 X26") 
  tranMergeMSR__read_old_vertex.writeAction(f"beqi X26 0 __if_read_old_vertex_7_false") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_6_true: movir X26 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"sendr2_dmlm X24 X25 X22 X26") 
  tranMergeMSR__read_old_vertex.writeAction(f"jmp __if_read_old_vertex_8_post") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_7_false: sendr_dmlm X24 X25 X22") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_8_post: addi X23 X23 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"yield") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_15_true: addi X7 X25 864") 
  tranMergeMSR__read_old_vertex.writeAction(f"movlr 0(X25) X24 0 8") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_18_true: addi X7 X26 832") 
  tranMergeMSR__read_old_vertex.writeAction(f"movlr 24(X26) X27 0 8") 
  tranMergeMSR__read_old_vertex.writeAction(f"fcnvt.i64.64 X27 X28")  # This is for casting. May be used later on
  tranMergeMSR__read_old_vertex.writeAction(f"movir X27 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"fcnvt.i64.64 X27 X25")  # This is for casting. May be used later on
  tranMergeMSR__read_old_vertex.writeAction(f"fsub.64 X25 X24 X25") 
  tranMergeMSR__read_old_vertex.writeAction(f"fdiv.64 X25 X28 X25") 
  tranMergeMSR__read_old_vertex.writeAction(f"fmul.64 X24 X22 X27") 
  tranMergeMSR__read_old_vertex.writeAction(f"fadd.64 X27 X25 X26") 
  tranMergeMSR__read_old_vertex.writeAction(f"addi X26 X22 0") 
  ## Detect if the vertex's update is significant
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_24_true: addi X7 X24 800") 
  tranMergeMSR__read_old_vertex.writeAction(f"movlr 0(X24) X25 0 8") 
  tranMergeMSR__read_old_vertex.writeAction(f"fcnvt.i64.64 X8 X26")  # This is for casting. May be used later on
  tranMergeMSR__read_old_vertex.writeAction(f"fmul.64 X14 X26 X26") 
  tranMergeMSR__read_old_vertex.writeAction(f"fsub.64 X22 X26 X27") 
  tranMergeMSR__read_old_vertex.writeAction(f"bgei X27 0 __if_read_old_vertex_32_post") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_30_true: movir X28 -16400") 
  tranMergeMSR__read_old_vertex.writeAction(f"sli X28 X28 48") 
  tranMergeMSR__read_old_vertex.writeAction(f"fmul.64 X27 X28 X27") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_32_post: ble X25 X27 __if_read_old_vertex_37_false") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_36_true: movir X21 0") 
  tranMergeMSR__read_old_vertex.writeAction(f"addi X26 X22 0") 
  tranMergeMSR__read_old_vertex.writeAction(f"jmp __if_read_old_vertex_45_true") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_37_false: movir X21 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_45_true: fcnvt.i64.64 X18 X24")  # This is for casting. May be used later on
  tranMergeMSR__read_old_vertex.writeAction(f"fdiv.64 X22 X24 X22") 
  ## Write back the weighted value and clear the vertex structure for the next iteration
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_48_true: addi X3 X24 48") 
  tranMergeMSR__read_old_vertex.writeAction(f"evi X2 X25 MergeMSR::update_vertex_ack 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"or X15 X19 X26") 
  tranMergeMSR__read_old_vertex.writeAction(f"beqi X26 0 __if_read_old_vertex_52_false") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_51_true: movir X26 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"sendr2_dmlm X24 X25 X22 X26") 
  tranMergeMSR__read_old_vertex.writeAction(f"jmp __if_read_old_vertex_53_post") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_52_false: sendr_dmlm X24 X25 X22") 
  tranMergeMSR__read_old_vertex.writeAction(f"__if_read_old_vertex_53_post: addi X23 X23 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"evi X2 X24 MergeMSR::sibling_rd_return 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"movir X25 512") 
  tranMergeMSR__read_old_vertex.writeAction(f"addi X7 X26 1024") 
  tranMergeMSR__read_old_vertex.writeAction(f"movlr 0(X26) X20 0 8") 
  tranMergeMSR__read_old_vertex.writeAction(f"sli X16 X27 6") 
  tranMergeMSR__read_old_vertex.writeAction(f"add X20 X27 X20") 
  ## Issue DRAM read requests to fetch sibling vertices
  tranMergeMSR__read_old_vertex.writeAction(f"movir X27 0") 
  tranMergeMSR__read_old_vertex.writeAction(f"__while_read_old_vertex_60_condition: clt X16 X13 X28") 
  tranMergeMSR__read_old_vertex.writeAction(f"clt X27 X25 X29") 
  tranMergeMSR__read_old_vertex.writeAction(f"and X28 X29 X30") 
  tranMergeMSR__read_old_vertex.writeAction(f"beqi X30 0 __while_read_old_vertex_62_post") 
  tranMergeMSR__read_old_vertex.writeAction(f"__while_read_old_vertex_61_body: send_dmlm_ld X20 X24 8") 
  tranMergeMSR__read_old_vertex.writeAction(f"addi X16 X16 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"addi X20 X20 64") 
  tranMergeMSR__read_old_vertex.writeAction(f"addi X27 X27 1") 
  tranMergeMSR__read_old_vertex.writeAction(f"jmp __while_read_old_vertex_60_condition") 
  tranMergeMSR__read_old_vertex.writeAction(f"__while_read_old_vertex_62_post: add X23 X27 X23") 
  tranMergeMSR__read_old_vertex.writeAction(f"yield") 
  
  # Writing code for event MergeMSR::sibling_rd_return
  tranMergeMSR__sibling_rd_return = efa.writeEvent('MergeMSR::sibling_rd_return')
  ## If the sibling pointer is within the bounds, continue reading
  tranMergeMSR__sibling_rd_return.writeAction(f"entry: bleu X17 X16 __if_sibling_rd_return_9_true") 
  tranMergeMSR__sibling_rd_return.writeAction(f"__if_sibling_rd_return_0_true: send_dmlm_ld X20 X2 8") 
  tranMergeMSR__sibling_rd_return.writeAction(f"addi X16 X16 1") 
  tranMergeMSR__sibling_rd_return.writeAction(f"addi X20 X20 64") 
  tranMergeMSR__sibling_rd_return.writeAction(f"addi X23 X23 1") 
  tranMergeMSR__sibling_rd_return.writeAction(f"jmp __if_sibling_rd_return_9_true") 
  ## Clear the flag and update the sibling value to be the original vertex's value for the next iteration
  tranMergeMSR__sibling_rd_return.writeAction(f"__if_sibling_rd_return_9_true: or X15 X19 X19") 
  tranMergeMSR__sibling_rd_return.writeAction(f"addi X7 X24 1088") 
  tranMergeMSR__sibling_rd_return.writeAction(f"movlr 0(X24) X25 0 8") 
  tranMergeMSR__sibling_rd_return.writeAction(f"sli X9 X27 6") 
  tranMergeMSR__sibling_rd_return.writeAction(f"add X25 X27 X28") 
  tranMergeMSR__sibling_rd_return.writeAction(f"addi X28 X26 48") 
  tranMergeMSR__sibling_rd_return.writeAction(f"evi X2 X27 MergeMSR::update_vertex_ack 1") 
  ## send_event(update_evw, vertex_addr + (6 * WORD_SIZE), CEVNT);
  tranMergeMSR__sibling_rd_return.writeAction(f"sendr_dmlm X26 X27 X22") 
  tranMergeMSR__sibling_rd_return.writeAction(f"bnei X21 1 __if_sibling_rd_return_17_post") 
  ## Update to the original vertex is significant, need to active all the neighbors
  tranMergeMSR__sibling_rd_return.writeAction(f"__if_sibling_rd_return_15_true: movir X24 0") 
  tranMergeMSR__sibling_rd_return.writeAction(f"evlb X24 MergeMSR::kv_map_emit") 
  tranMergeMSR__sibling_rd_return.writeAction(f"evi X24 X24 255 4") 
  tranMergeMSR__sibling_rd_return.writeAction(f"ev X24 X24 X0 X0 8") 
  tranMergeMSR__sibling_rd_return.writeAction(f"movir X25 512") 
  tranMergeMSR__sibling_rd_return.writeAction(f"addi X10 X26 0") 
  tranMergeMSR__sibling_rd_return.writeAction(f"sli X8 X28 3") 
  tranMergeMSR__sibling_rd_return.writeAction(f"add X10 X28 X27") 
  tranMergeMSR__sibling_rd_return.writeAction(f"addi X8 X28 0") 
  tranMergeMSR__sibling_rd_return.writeAction(f"__while_sibling_rd_return_18_condition: ble X27 X26 __while_sibling_rd_return_20_post") 
  tranMergeMSR__sibling_rd_return.writeAction(f"__while_sibling_rd_return_19_body: ble X25 X28 __if_sibling_rd_return_22_false") 
  tranMergeMSR__sibling_rd_return.writeAction(f"__if_sibling_rd_return_21_true: sendr_wcont X24 X2 X26 X28") 
  tranMergeMSR__sibling_rd_return.writeAction(f"jmp __if_sibling_rd_return_23_post") 
  tranMergeMSR__sibling_rd_return.writeAction(f"__if_sibling_rd_return_22_false: sendr_wcont X24 X2 X26 X25") 
  tranMergeMSR__sibling_rd_return.writeAction(f"__if_sibling_rd_return_23_post: sub X28 X25 X28") 
  tranMergeMSR__sibling_rd_return.writeAction(f"sli X25 X29 3") 
  tranMergeMSR__sibling_rd_return.writeAction(f"add X26 X29 X26") 
  tranMergeMSR__sibling_rd_return.writeAction(f"jmp __while_sibling_rd_return_18_condition") 
  ## Count active set volume
  tranMergeMSR__sibling_rd_return.writeAction(f"__while_sibling_rd_return_20_post: addi X7 X29 1152") 
  tranMergeMSR__sibling_rd_return.writeAction(f"movlr 0(X29) X30 0 8") 
  tranMergeMSR__sibling_rd_return.writeAction(f"add X30 X8 X30") 
  tranMergeMSR__sibling_rd_return.writeAction(f"movrl X30 0(X29) 0 8") 
  tranMergeMSR__sibling_rd_return.writeAction(f"__if_sibling_rd_return_17_post: yield") 
  
  # Writing code for event MergeMSR::update_vertex_ack
  tranMergeMSR__update_vertex_ack = efa.writeEvent('MergeMSR::update_vertex_ack')
  tranMergeMSR__update_vertex_ack.writeAction(f"entry: subi X23 X23 1") 
  tranMergeMSR__update_vertex_ack.writeAction(f"ceqi X23 X24 0") 
  tranMergeMSR__update_vertex_ack.writeAction(f"ceq X16 X17 X25") 
  tranMergeMSR__update_vertex_ack.writeAction(f"and X24 X25 X26") 
  tranMergeMSR__update_vertex_ack.writeAction(f"beqi X26 0 __if_update_vertex_ack_5_post") 
  tranMergeMSR__update_vertex_ack.writeAction(f"__if_update_vertex_ack_3_true: evi X2 X24 MergeMSR::kv_map_return 1") 
  tranMergeMSR__update_vertex_ack.writeAction(f"sendr_wcont X24 X2 X23 X23") 
  tranMergeMSR__update_vertex_ack.writeAction(f"yield") 
  ## Waiting the pending updates to return
  tranMergeMSR__update_vertex_ack.writeAction(f"__if_update_vertex_ack_5_post: yield") 
  
  # Writing code for event MergeMSR::kv_reduce
  tranMergeMSR__kv_reduce = efa.writeEvent('MergeMSR::kv_reduce')
  tranMergeMSR__kv_reduce.writeAction(f"entry: movir X23 0") 
  tranMergeMSR__kv_reduce.writeAction(f"movir X24 512") 
  tranMergeMSR__kv_reduce.writeAction(f"evi X2 X25 MergeMSR::rd_nlist_return_update 1") 
  tranMergeMSR__kv_reduce.writeAction(f"addi X8 X26 0") 
  tranMergeMSR__kv_reduce.writeAction(f"sli X9 X28 3") 
  tranMergeMSR__kv_reduce.writeAction(f"add X8 X28 X27") 
  tranMergeMSR__kv_reduce.writeAction(f"__while_kv_reduce_0_condition: ble X9 X23 __while_kv_reduce_2_post") 
  tranMergeMSR__kv_reduce.writeAction(f"__while_kv_reduce_1_body: send_dmlm_ld X26 X25 8") 
  tranMergeMSR__kv_reduce.writeAction(f"addi X23 X23 8") 
  tranMergeMSR__kv_reduce.writeAction(f"addi X26 X26 64") 
  tranMergeMSR__kv_reduce.writeAction(f"bgt X24 X23 __if_kv_reduce_5_post") 
  tranMergeMSR__kv_reduce.writeAction(f"__if_kv_reduce_3_true: jmp __while_kv_reduce_2_post") 
  tranMergeMSR__kv_reduce.writeAction(f"__if_kv_reduce_5_post: jmp __while_kv_reduce_0_condition") 
  tranMergeMSR__kv_reduce.writeAction(f"__while_kv_reduce_2_post: addi X9 X23 0") 
  tranMergeMSR__kv_reduce.writeAction(f"movir X19 1") 
  tranMergeMSR__kv_reduce.writeAction(f"addi X26 X16 0") 
  tranMergeMSR__kv_reduce.writeAction(f"addi X27 X17 0") 
  tranMergeMSR__kv_reduce.writeAction(f"yield") 
  
  # Writing code for event MergeMSR::rd_nlist_return_update
  tranMergeMSR__rd_nlist_return_update = efa.writeEvent('MergeMSR::rd_nlist_return_update')
  tranMergeMSR__rd_nlist_return_update.writeAction(f"entry: addi X16 X24 0") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X17 X25 0") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"ble X25 X24 __if_rd_nlist_return_update_2_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_0_true: send_dmlm_ld X24 X2 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X24 X24 64") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_2_post: addi X3 X26 0") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_6_true: addi X7 X28 1088") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"movlr 0(X28) X27 0 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"evi X2 X28 MergeMSR::write_value_ack 1") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sli X8 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X26 X26 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"bgt X25 X26 __if_rd_nlist_return_update_14_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_12_true: yield") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_14_post: sli X9 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X26 X26 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"bgt X25 X26 __if_rd_nlist_return_update_20_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_18_true: yield") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_20_post: sli X10 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X26 X26 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"bgt X25 X26 __if_rd_nlist_return_update_26_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_24_true: yield") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_26_post: sli X11 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X26 X26 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"bgt X25 X26 __if_rd_nlist_return_update_32_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_30_true: yield") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_32_post: sli X12 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X26 X26 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"bgt X25 X26 __if_rd_nlist_return_update_38_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_36_true: yield") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_38_post: sli X13 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X26 X26 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"bgt X25 X26 __if_rd_nlist_return_update_44_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_42_true: yield") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_44_post: sli X14 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X26 X26 8") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"bgt X25 X26 __if_rd_nlist_return_update_50_post") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_48_true: yield") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"__if_rd_nlist_return_update_50_post: sli X15 X30 6") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"add X27 X30 X31") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X31 X29 56") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"sendr_dmlm X29 X28 X19") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X24 X16 0") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"addi X25 X17 0") 
  tranMergeMSR__rd_nlist_return_update.writeAction(f"yield") 
  
  # Writing code for event MergeMSR::write_value_ack
  tranMergeMSR__write_value_ack = efa.writeEvent('MergeMSR::write_value_ack')
  tranMergeMSR__write_value_ack.writeAction(f"entry: subi X23 X23 1") 
  tranMergeMSR__write_value_ack.writeAction(f"blei X23 0 __if_write_value_ack_5_post") 
  tranMergeMSR__write_value_ack.writeAction(f"__if_write_value_ack_3_true: yield") 
  tranMergeMSR__write_value_ack.writeAction(f"__if_write_value_ack_5_post: evi X2 X24 MergeMSR::kv_reduce_return 1") 
  tranMergeMSR__write_value_ack.writeAction(f"sendr_wcont X24 X2 X23 X23") 
  tranMergeMSR__write_value_ack.writeAction(f"yield") 
  
